comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        base: auto

ignore:
  # Configuration files
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/*.config.mjs"
  - "**/vitest.config.ts"
  - "**/jest.config.js"
  - "**/eslint.config.js"
  - "**/.eslintrc.*"
  # Build outputs
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  # Dependencies
  - "**/node_modules/**"
  # Test files
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  # Type definitions
  - "**/*.d.ts"