version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: bluelight-hub-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER:-bluelight}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-bluelight}
      - POSTGRES_DB=${DATABASE_NAME:-bluelight-hub}
    restart: unless-stopped
    ports:
      - "9035:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bluelight" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER:-bluelight}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-bluelight}
      - DATABASE_NAME=${DATABASE_NAME:-bluelight-hub}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_data:
    name: bluelight-hub-postgres-data