packages:
  - packages/*
  - .

catalog:
  '@chakra-ui/react': ^3.24.0
  '@emotion/react': ^11.14.0
  '@eslint/js': ^9.32.0
  '@fontsource-variable/inter': ^5.2.6
  '@fontsource-variable/montserrat': ^5.2.6
  '@fontsource-variable/nunito': ^5.2.6
  '@playwright/test': ^1.54.2
  '@playwright/test-runner': ^0.9.24
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/pacer': ^0.13.0
  '@tanstack/react-form': ^1.15.2
  '@tanstack/react-query': 5.84.1
  '@tanstack/react-query-devtools': 5.84.1
  '@tanstack/react-router': ^1.130.12
  '@tanstack/react-router-devtools': ^1.130.13
  '@tanstack/react-store': ^0.7.3
  '@tanstack/router-plugin': ^1.130.15
  '@tauri-apps/api': ^2.7.0
  '@tauri-apps/cli': ^2.7.1
  '@tauri-apps/plugin-http': ^2.5.1
  '@tauri-apps/plugin-store': ^2.3.0
  '@types/jest': ^30.0.0
  '@types/node': 24.1.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react-swc': ^3.11.0
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  consola: ^3.4.2
  eslint: ^9.32.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  globals: ^16.3.0
  jsdom: ^26.1.0
  next-themes: ^0.4.6
  react: 19.1.1
  react-dom: 19.1.1
  react-icons: ^5.5.0
  tailwind-merge: 3.3.1
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  typescript-eslint: 8.38.0
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
