/**
 * Error Codes fuer Notiz-Operationen.
 */
export const NOTIZ_ERROR_CODES = {
  TITEL_REQUIRED: 'NOTIZ_TITEL_REQUIRED',
  TITEL_TOO_LONG: 'NOTIZ_TITEL_TOO_LONG',
  INHALT_TOO_LONG: 'NOTIZ_INHALT_TOO_LONG',
  KATEGORIE_TOO_LONG: 'NOTIZ_KATEGORIE_TOO_LONG',
  ERSTELLT_VON_REQUIRED: 'NOTIZ_ERSTELLT_VON_REQUIRED',
  EINSATZ_ID_REQUIRED: 'NOTIZ_EINSATZ_ID_REQUIRED',
  CREATION_FAILED: 'NOTIZ_CREATION_FAILED',
  SAVE_FAILED: 'NOTIZ_SAVE_FAILED',
  NOT_FOUND: 'NOTIZ_NOT_FOUND',
  ALREADY_DELETED: 'NOTIZ_ALREADY_DELETED',
  NO_CHANGES: 'NOTIZ_NO_CHANGES',
  UPDATE_FAILED: 'NOTIZ_UPDATE_FAILED',
  AKTUALISIERT_VON_REQUIRED: 'NOTIZ_AKTUALISIERT_VON_REQUIRED',
  DELETE_FAILED: 'NOTIZ_DELETE_FAILED',
  GELOESCHT_VON_REQUIRED: 'NOTIZ_GELOESCHT_VON_REQUIRED',

  // Story 8.2: Kategorie-Validierung
  KATEGORIE_ID_INVALID: 'NOTIZ_KATEGORIE_ID_INVALID', // Story 8.2: kategorieId ist ungültiges CUID2 Format
  KATEGORIE_NOT_FOUND: 'NOTIZ_KATEGORIE_NOT_FOUND', // Story 8.2: Kategorie existiert nicht oder wurde gelöscht
  KATEGORIE_WRONG_EINSATZ: 'NOTIZ_KATEGORIE_WRONG_EINSATZ', // Story 8.2: Kategorie gehört zu anderem Einsatz
} as const;
