export enum AlertStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  DISPATCHED = 'DISPATCHED',
  FAILED = 'FAILED',
  RESOLVED = 'RESOLVED',
  SUPPRESSED = 'SUPPRESSED',
}

export enum AlertType {
  MULTIPLE_FAILED_ATTEMPTS = 'MULTIPLE_FAILED_ATTEMPTS',
  BRUTE_FORCE_ATTEMPT = 'BRUTE_FORCE_ATTEMPT',
  SUSPICIOUS_LOGIN = 'SUSPICIOUS_LOGIN',
  ANOMALY_DETECTED = 'ANOMALY_DETECTED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  THREAT_RULE_MATCH = 'THREAT_RULE_MATCH',
}

// Export both as named and default exports to handle different import styles
export default {
  AlertStatus,
  AlertType,
};
