/**
 * Error Codes fuer Kategorie-Operationen (Story 8.1).
 */
export const KATEGORIE_ERROR_CODES = {
  NAME_REQUIRED: 'KATEGORIE_NAME_REQUIRED',
  NAME_TOO_LONG: 'KATEGORIE_NAME_TOO_LONG',
  FARBE_REQUIRED: 'KATEGORIE_FARBE_REQUIRED',
  FARBE_INVALID: 'KATEGORIE_FARBE_INVALID',
  EINSATZ_ID_REQUIRED: 'KATEGORIE_EINSATZ_ID_REQUIRED',
  ERSTELLT_VON_REQUIRED: 'KATEGORIE_ERSTELLT_VON_REQUIRED',
  CREATION_FAILED: 'KATEGORIE_CREATION_FAILED',
  NAME_DUPLICATE: 'KATEGORIE_NAME_DUPLICATE',
  NOT_FOUND: 'KATEGORIE_NOT_FOUND',
  ALREADY_DELETED: 'KATEGORIE_ALREADY_DELETED',
  DELETE_FAILED: 'KATEGORIE_DELETE_FAILED',
  GELOESCHT_VON_REQUIRED: 'KATEGORIE_GELOESCHT_VON_REQUIRED',
} as const;
