module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.ts',
    '!migrations/**/*.ts',
    '!main.ts',
    '!logger/**/*.ts',
    '!**/node_modules/**',
    '!dist/**',
    '!**/test/**',
    '!eslint.config.js',
    '!.eslintrc.*',
    '!**/eslint.config.{js,ts,mjs}',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  transformIgnorePatterns: ['node_modules/(?!(nanoid)/)'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@prisma/generated/prisma/enums$': '<rootDir>/__mocks__/prisma/enums.ts',
    '^@prisma/generated/prisma/client$': '<rootDir>/__mocks__/prisma/client.ts',
    '^@prisma/generated/prisma$': '<rootDir>/__mocks__/prisma/enums.ts',
    '^nanoid$': '<rootDir>/__mocks__/nanoid.ts',
  },
  coverageThreshold: {
    global: {
      branches: 76,
      functions: 79,
      lines: 80,
      statements: 80,
    },
  },
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/test/',
    '/__tests__/audit-performance.spec.ts$',
  ],
};
