/**
 * Error Codes für Führungsrhythmus-Template-Operationen.
 */
export const FUEHRUNGSRHYTHMUS_TEMPLATE_ERROR_CODES = {
  NAME_REQUIRED: 'FR_TEMPLATE_NAME_REQUIRED',
  NAME_TOO_LONG: 'FR_TEMPLATE_NAME_TOO_LONG',
  BESCHREIBUNG_TOO_LONG: 'FR_TEMPLATE_BESCHREIBUNG_TOO_LONG',
  NO_EINTRAEGE: 'FR_TEMPLATE_NO_EINTRAEGE',
  EINTRAG_INVALID: 'FR_TEMPLATE_EINTRAG_INVALID',
  CREATED_BY_REQUIRED: 'FR_TEMPLATE_CREATED_BY_REQUIRED',
  CREATION_FAILED: 'FR_TEMPLATE_CREATION_FAILED',
  NOT_FOUND: 'FR_TEMPLATE_NOT_FOUND',
  ALREADY_DELETED: 'FR_TEMPLATE_ALREADY_DELETED',
  SAVE_FAILED: 'FR_TEMPLATE_SAVE_FAILED',
} as const;
