export const HAZARD_ZONE_ERROR_CODES = {
  EINSATZ_ID_REQUIRED: 'HAZARD_ZONE_EINSATZ_ID_REQUIRED',
  ZONE_ID_REQUIRED: 'HAZARD_ZONE_ZONE_ID_REQUIRED',
  GEFAHRENTYP_INVALID: 'HAZARD_ZONE_GEFAHRENTYP_INVALID',
  GEOMETRY_TYPE_INVALID: 'HAZARD_ZONE_GEOMETRY_TYPE_INVALID',
  GEOMETRY_INVALID: 'HAZARD_ZONE_GEOMETRY_INVALID',
  CREATED_BY_REQUIRED: 'HAZARD_ZONE_CREATED_BY_REQUIRED',
  UPDATED_BY_REQUIRED: 'HAZARD_ZONE_UPDATED_BY_REQUIRED',
  DELETED_BY_REQUIRED: 'HAZARD_ZONE_DELETED_BY_REQUIRED',
  NOT_FOUND: 'HAZARD_ZONE_NOT_FOUND',
} as const;
