/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.99-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddPoiDto
 */
export interface AddPoiDto {
    /**
     * POI-Name
     * @type {string}
     * @memberof AddPoiDto
     */
    name: string;
    /**
     * Koordinate als Lat/Lng oder MGRS
     * @type {object}
     * @memberof AddPoiDto
     */
    coordinate: object;
    /**
     * POI-Kategorie (DRK-Standard)
     * @type {string}
     * @memberof AddPoiDto
     */
    category: AddPoiDtoCategoryEnum;
    /**
     * Zusätzliche Beschreibung (optional)
     * @type {string}
     * @memberof AddPoiDto
     */
    beschreibung?: string;
}


/**
 * @export
 */
export const AddPoiDtoCategoryEnum = {
    Einsatzstelle: 'EINSATZSTELLE',
    Bereitstellungsraum: 'BEREITSTELLUNGSRAUM',
    Gefahrenstelle: 'GEFAHRENSTELLE',
    Wasserentnahmestelle: 'WASSERENTNAHMESTELLE',
    Sonstiges: 'SONSTIGES'
} as const;
export type AddPoiDtoCategoryEnum = typeof AddPoiDtoCategoryEnum[keyof typeof AddPoiDtoCategoryEnum];


/**
 * Check if a given object implements the AddPoiDto interface.
 */
export function instanceOfAddPoiDto(value: object): value is AddPoiDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('coordinate' in value) || value['coordinate'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function AddPoiDtoFromJSON(json: any): AddPoiDto {
    return AddPoiDtoFromJSONTyped(json, false);
}

export function AddPoiDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPoiDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'coordinate': json['coordinate'],
        'category': json['category'],
        'beschreibung': json['beschreibung'] == null ? undefined : json['beschreibung'],
    };
}

export function AddPoiDtoToJSON(json: any): AddPoiDto {
    return AddPoiDtoToJSONTyped(json, false);
}

export function AddPoiDtoToJSONTyped(value?: AddPoiDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'coordinate': value['coordinate'],
        'category': value['category'],
        'beschreibung': value['beschreibung'],
    };
}

