/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HiOrgConnectionInfoDto } from './HiOrgConnectionInfoDto';
import { HiOrgConnectionInfoDtoFromJSON, HiOrgConnectionInfoDtoFromJSONTyped, HiOrgConnectionInfoDtoToJSON, HiOrgConnectionInfoDtoToJSONTyped } from './HiOrgConnectionInfoDto';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
  AuthControllerUnifiedAuth200ResponseMetaFromJSON,
  AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
  AuthControllerUnifiedAuth200ResponseMetaToJSON,
  AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';

/**
 *
 * @export
 * @interface AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response
 */
export interface AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response {
  /**
   *
   * @type {HiOrgConnectionInfoDto}
   * @memberof AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response
   */
  data: HiOrgConnectionInfoDto;
  /**
   *
   * @type {AuthControllerUnifiedAuth200ResponseMeta}
   * @memberof AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response
   */
  meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response interface.
 */
export function instanceOfAdminHiOrgIntegrationControllerTestConnectionVAlpha200Response(value: object): value is AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function AdminHiOrgIntegrationControllerTestConnectionVAlpha200ResponseFromJSON(json: any): AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response {
  return AdminHiOrgIntegrationControllerTestConnectionVAlpha200ResponseFromJSONTyped(json, false);
}

export function AdminHiOrgIntegrationControllerTestConnectionVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: HiOrgConnectionInfoDtoFromJSON(json['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
  };
}

export function AdminHiOrgIntegrationControllerTestConnectionVAlpha200ResponseToJSON(json: any): AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response {
  return AdminHiOrgIntegrationControllerTestConnectionVAlpha200ResponseToJSONTyped(json, false);
}

export function AdminHiOrgIntegrationControllerTestConnectionVAlpha200ResponseToJSONTyped(
  value?: AdminHiOrgIntegrationControllerTestConnectionVAlpha200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: HiOrgConnectionInfoDtoToJSON(value['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
  };
}
