/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthControllerGetIntegrationHealth200ResponseMeta } from './HealthControllerGetIntegrationHealth200ResponseMeta';
import {
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSONTyped,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSONTyped,
} from './HealthControllerGetIntegrationHealth200ResponseMeta';
import type { RefreshTokenResponseDto } from './RefreshTokenResponseDto';
import {
    RefreshTokenResponseDtoFromJSON,
    RefreshTokenResponseDtoFromJSONTyped,
    RefreshTokenResponseDtoToJSON,
    RefreshTokenResponseDtoToJSONTyped,
} from './RefreshTokenResponseDto';

/**
 * 
 * @export
 * @interface AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response
 */
export interface AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response {
    /**
     * 
     * @type {RefreshTokenResponseDto}
     * @memberof AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response
     */
    data: RefreshTokenResponseDto;
    /**
     * 
     * @type {HealthControllerGetIntegrationHealth200ResponseMeta}
     * @memberof AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response
     */
    meta: HealthControllerGetIntegrationHealth200ResponseMeta;
}

/**
 * Check if a given object implements the AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response interface.
 */
export function instanceOfAdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response(value: object): value is AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function AdminHiOrgIntegrationControllerRefreshTokenVAlpha200ResponseFromJSON(json: any): AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response {
    return AdminHiOrgIntegrationControllerRefreshTokenVAlpha200ResponseFromJSONTyped(json, false);
}

export function AdminHiOrgIntegrationControllerRefreshTokenVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': RefreshTokenResponseDtoFromJSON(json['data']),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaFromJSON(json['meta']),
    };
}

export function AdminHiOrgIntegrationControllerRefreshTokenVAlpha200ResponseToJSON(json: any): AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response {
    return AdminHiOrgIntegrationControllerRefreshTokenVAlpha200ResponseToJSONTyped(json, false);
}

export function AdminHiOrgIntegrationControllerRefreshTokenVAlpha200ResponseToJSONTyped(value?: AdminHiOrgIntegrationControllerRefreshTokenVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RefreshTokenResponseDtoToJSON(value['data']),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaToJSON(value['meta']),
    };
}

