/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.99-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlarmierungEmpfaengerResponseDto
 */
export interface AlarmierungEmpfaengerResponseDto {
    /**
     * ID des Empfänger-Eintrags
     * @type {string}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    id: string;
    /**
     * Typ des Empfängers
     * @type {string}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    kind: AlarmierungEmpfaengerResponseDtoKindEnum;
    /**
     * ID des Fahrzeugs (nur bei kind=fahrzeug)
     * @type {string}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    fahrzeugId?: string | null;
    /**
     * ID der Person (nur bei kind=person)
     * @type {string}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    personId?: string | null;
    /**
     * ID der Einheit (nur bei kind=einheit)
     * @type {string}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    einheitId?: string | null;
    /**
     * Name-Snapshot zum Zeitpunkt der Zuordnung
     * @type {string}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    nameSnapshot: string;
    /**
     * Zeitpunkt der Alarmierung des Empfängers
     * @type {Date}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    alarmiertAm: Date;
    /**
     * Ausgerückt-Zeitpunkt (FMS 3 oder manuell)
     * @type {Date}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    ausgeruecktAm?: Date | null;
    /**
     * Vor-Ort-Zeitpunkt (FMS 4 oder manuell)
     * @type {Date}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    vorOrtAm?: Date | null;
    /**
     * Wieder-Frei-Zeitpunkt (FMS 1/2 oder manuell)
     * @type {Date}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    wiederFreiAm?: Date | null;
    /**
     * Letzter empfangener FMS-Status
     * @type {number}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    letzterFmsStatus?: number | null;
    /**
     * Reaktionszeit in Sekunden (alarmiertAm → vorOrtAm). Null, solange vorOrtAm nicht gesetzt.
     * @type {number}
     * @memberof AlarmierungEmpfaengerResponseDto
     */
    reaktionszeitSekunden?: number | null;
}


/**
 * @export
 */
export const AlarmierungEmpfaengerResponseDtoKindEnum = {
    Fahrzeug: 'fahrzeug',
    Person: 'person',
    Einheit: 'einheit'
} as const;
export type AlarmierungEmpfaengerResponseDtoKindEnum = typeof AlarmierungEmpfaengerResponseDtoKindEnum[keyof typeof AlarmierungEmpfaengerResponseDtoKindEnum];


/**
 * Check if a given object implements the AlarmierungEmpfaengerResponseDto interface.
 */
export function instanceOfAlarmierungEmpfaengerResponseDto(value: object): value is AlarmierungEmpfaengerResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('nameSnapshot' in value) || value['nameSnapshot'] === undefined) return false;
    if (!('alarmiertAm' in value) || value['alarmiertAm'] === undefined) return false;
    return true;
}

export function AlarmierungEmpfaengerResponseDtoFromJSON(json: any): AlarmierungEmpfaengerResponseDto {
    return AlarmierungEmpfaengerResponseDtoFromJSONTyped(json, false);
}

export function AlarmierungEmpfaengerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlarmierungEmpfaengerResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'fahrzeugId': json['fahrzeugId'] == null ? undefined : json['fahrzeugId'],
        'personId': json['personId'] == null ? undefined : json['personId'],
        'einheitId': json['einheitId'] == null ? undefined : json['einheitId'],
        'nameSnapshot': json['nameSnapshot'],
        'alarmiertAm': (new Date(json['alarmiertAm'])),
        'ausgeruecktAm': json['ausgeruecktAm'] == null ? undefined : (new Date(json['ausgeruecktAm'])),
        'vorOrtAm': json['vorOrtAm'] == null ? undefined : (new Date(json['vorOrtAm'])),
        'wiederFreiAm': json['wiederFreiAm'] == null ? undefined : (new Date(json['wiederFreiAm'])),
        'letzterFmsStatus': json['letzterFmsStatus'] == null ? undefined : json['letzterFmsStatus'],
        'reaktionszeitSekunden': json['reaktionszeitSekunden'] == null ? undefined : json['reaktionszeitSekunden'],
    };
}

export function AlarmierungEmpfaengerResponseDtoToJSON(json: any): AlarmierungEmpfaengerResponseDto {
    return AlarmierungEmpfaengerResponseDtoToJSONTyped(json, false);
}

export function AlarmierungEmpfaengerResponseDtoToJSONTyped(value?: AlarmierungEmpfaengerResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'fahrzeugId': value['fahrzeugId'],
        'personId': value['personId'],
        'einheitId': value['einheitId'],
        'nameSnapshot': value['nameSnapshot'],
        'alarmiertAm': ((value['alarmiertAm']).toISOString()),
        'ausgeruecktAm': value['ausgeruecktAm'] == null ? undefined : ((value['ausgeruecktAm'] as any).toISOString()),
        'vorOrtAm': value['vorOrtAm'] == null ? undefined : ((value['vorOrtAm'] as any).toISOString()),
        'wiederFreiAm': value['wiederFreiAm'] == null ? undefined : ((value['wiederFreiAm'] as any).toISOString()),
        'letzterFmsStatus': value['letzterFmsStatus'],
        'reaktionszeitSekunden': value['reaktionszeitSekunden'],
    };
}

