/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.61-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserResponseDto
 */
export interface AuthUserResponseDto {
    /**
     * Eindeutige ID des Benutzers
     * @type {string}
     * @memberof AuthUserResponseDto
     */
    id: string;
    /**
     * Benutzername
     * @type {string}
     * @memberof AuthUserResponseDto
     */
    username: string;
    /**
     * Rolle des Benutzers
     * @type {string}
     * @memberof AuthUserResponseDto
     */
    role: AuthUserResponseDtoRoleEnum;
    /**
     * Gibt an, ob der Benutzer aktiv ist
     * @type {boolean}
     * @memberof AuthUserResponseDto
     */
    isActive: boolean;
    /**
     * Zeitpunkt der letzten Anmeldung
     * @type {object}
     * @memberof AuthUserResponseDto
     */
    lastLoginAt?: object | null;
    /**
     * Zeitpunkt der Erstellung
     * @type {Date}
     * @memberof AuthUserResponseDto
     */
    createdAt: Date;
    /**
     * Zeitpunkt der letzten Aktualisierung
     * @type {Date}
     * @memberof AuthUserResponseDto
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const AuthUserResponseDtoRoleEnum = {
    SuperAdmin: 'SUPER_ADMIN',
    Admin: 'ADMIN',
    User: 'USER'
} as const;
export type AuthUserResponseDtoRoleEnum = typeof AuthUserResponseDtoRoleEnum[keyof typeof AuthUserResponseDtoRoleEnum];


/**
 * Check if a given object implements the AuthUserResponseDto interface.
 */
export function instanceOfAuthUserResponseDto(value: object): value is AuthUserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AuthUserResponseDtoFromJSON(json: any): AuthUserResponseDto {
    return AuthUserResponseDtoFromJSONTyped(json, false);
}

export function AuthUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'role': json['role'],
        'isActive': json['isActive'],
        'lastLoginAt': json['lastLoginAt'] == null ? undefined : json['lastLoginAt'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function AuthUserResponseDtoToJSON(json: any): AuthUserResponseDto {
    return AuthUserResponseDtoToJSONTyped(json, false);
}

export function AuthUserResponseDtoToJSONTyped(value?: AuthUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'role': value['role'],
        'isActive': value['isActive'],
        'lastLoginAt': value['lastLoginAt'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

