/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
  AuthControllerUnifiedAuth200ResponseMetaFromJSON,
  AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
  AuthControllerUnifiedAuth200ResponseMetaToJSON,
  AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { AdminStatusDto } from './AdminStatusDto';
import { AdminStatusDtoFromJSON, AdminStatusDtoFromJSONTyped, AdminStatusDtoToJSON, AdminStatusDtoToJSONTyped } from './AdminStatusDto';

/**
 *
 * @export
 * @interface AuthControllerGetAdminStatus200Response
 */
export interface AuthControllerGetAdminStatus200Response {
  /**
   *
   * @type {AdminStatusDto}
   * @memberof AuthControllerGetAdminStatus200Response
   */
  data: AdminStatusDto;
  /**
   *
   * @type {AuthControllerUnifiedAuth200ResponseMeta}
   * @memberof AuthControllerGetAdminStatus200Response
   */
  meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the AuthControllerGetAdminStatus200Response interface.
 */
export function instanceOfAuthControllerGetAdminStatus200Response(value: object): value is AuthControllerGetAdminStatus200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function AuthControllerGetAdminStatus200ResponseFromJSON(json: any): AuthControllerGetAdminStatus200Response {
  return AuthControllerGetAdminStatus200ResponseFromJSONTyped(json, false);
}

export function AuthControllerGetAdminStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerGetAdminStatus200Response {
  if (json == null) {
    return json;
  }
  return {
    data: AdminStatusDtoFromJSON(json['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
  };
}

export function AuthControllerGetAdminStatus200ResponseToJSON(json: any): AuthControllerGetAdminStatus200Response {
  return AuthControllerGetAdminStatus200ResponseToJSONTyped(json, false);
}

export function AuthControllerGetAdminStatus200ResponseToJSONTyped(value?: AuthControllerGetAdminStatus200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: AdminStatusDtoToJSON(value['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
  };
}
