/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
  AuthControllerUnifiedAuth200ResponseMetaFromJSON,
  AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
  AuthControllerUnifiedAuth200ResponseMetaToJSON,
  AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { AdminSetupResponseDto } from './AdminSetupResponseDto';
import { AdminSetupResponseDtoFromJSON, AdminSetupResponseDtoFromJSONTyped, AdminSetupResponseDtoToJSON, AdminSetupResponseDtoToJSONTyped } from './AdminSetupResponseDto';

/**
 *
 * @export
 * @interface AuthControllerAdminSetup200Response
 */
export interface AuthControllerAdminSetup200Response {
  /**
   *
   * @type {AdminSetupResponseDto}
   * @memberof AuthControllerAdminSetup200Response
   */
  data: AdminSetupResponseDto;
  /**
   *
   * @type {AuthControllerUnifiedAuth200ResponseMeta}
   * @memberof AuthControllerAdminSetup200Response
   */
  meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the AuthControllerAdminSetup200Response interface.
 */
export function instanceOfAuthControllerAdminSetup200Response(value: object): value is AuthControllerAdminSetup200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function AuthControllerAdminSetup200ResponseFromJSON(json: any): AuthControllerAdminSetup200Response {
  return AuthControllerAdminSetup200ResponseFromJSONTyped(json, false);
}

export function AuthControllerAdminSetup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerAdminSetup200Response {
  if (json == null) {
    return json;
  }
  return {
    data: AdminSetupResponseDtoFromJSON(json['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
  };
}

export function AuthControllerAdminSetup200ResponseToJSON(json: any): AuthControllerAdminSetup200Response {
  return AuthControllerAdminSetup200ResponseToJSONTyped(json, false);
}

export function AuthControllerAdminSetup200ResponseToJSONTyped(value?: AuthControllerAdminSetup200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: AdminSetupResponseDtoToJSON(value['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
  };
}
