/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.79-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BefehlHistorieEventDto } from './BefehlHistorieEventDto';
import {
    BefehlHistorieEventDtoFromJSON,
    BefehlHistorieEventDtoFromJSONTyped,
    BefehlHistorieEventDtoToJSON,
    BefehlHistorieEventDtoToJSONTyped,
} from './BefehlHistorieEventDto';

/**
 * 
 * @export
 * @interface BefehlHistorieTimelineDto
 */
export interface BefehlHistorieTimelineDto {
    /**
     * 
     * @type {string}
     * @memberof BefehlHistorieTimelineDto
     */
    befehlId: string;
    /**
     * 
     * @type {string}
     * @memberof BefehlHistorieTimelineDto
     */
    befehlNummer: string;
    /**
     * 
     * @type {string}
     * @memberof BefehlHistorieTimelineDto
     */
    aktuellerStatus: string;
    /**
     * 
     * @type {Array<BefehlHistorieEventDto>}
     * @memberof BefehlHistorieTimelineDto
     */
    events: Array<BefehlHistorieEventDto>;
}

/**
 * Check if a given object implements the BefehlHistorieTimelineDto interface.
 */
export function instanceOfBefehlHistorieTimelineDto(value: object): value is BefehlHistorieTimelineDto {
    if (!('befehlId' in value) || value['befehlId'] === undefined) return false;
    if (!('befehlNummer' in value) || value['befehlNummer'] === undefined) return false;
    if (!('aktuellerStatus' in value) || value['aktuellerStatus'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function BefehlHistorieTimelineDtoFromJSON(json: any): BefehlHistorieTimelineDto {
    return BefehlHistorieTimelineDtoFromJSONTyped(json, false);
}

export function BefehlHistorieTimelineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BefehlHistorieTimelineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'befehlId': json['befehlId'],
        'befehlNummer': json['befehlNummer'],
        'aktuellerStatus': json['aktuellerStatus'],
        'events': ((json['events'] as Array<any>).map(BefehlHistorieEventDtoFromJSON)),
    };
}

export function BefehlHistorieTimelineDtoToJSON(json: any): BefehlHistorieTimelineDto {
    return BefehlHistorieTimelineDtoToJSONTyped(json, false);
}

export function BefehlHistorieTimelineDtoToJSONTyped(value?: BefehlHistorieTimelineDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'befehlId': value['befehlId'],
        'befehlNummer': value['befehlNummer'],
        'aktuellerStatus': value['aktuellerStatus'],
        'events': ((value['events'] as Array<any>).map(BefehlHistorieEventDtoToJSON)),
    };
}

