/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeteiligterFreitextDto
 */
export interface BeteiligterFreitextDto {
    /**
     * 
     * @type {string}
     * @memberof BeteiligterFreitextDto
     */
    kind: BeteiligterFreitextDtoKindEnum;
    /**
     * Frei eingegebener Name (1–200)
     * @type {string}
     * @memberof BeteiligterFreitextDto
     */
    name: string;
    /**
     * Optionale Rolle (≤ 100)
     * @type {string}
     * @memberof BeteiligterFreitextDto
     */
    rolle?: string;
}


/**
 * @export
 */
export const BeteiligterFreitextDtoKindEnum = {
    Freitext: 'freitext'
} as const;
export type BeteiligterFreitextDtoKindEnum = typeof BeteiligterFreitextDtoKindEnum[keyof typeof BeteiligterFreitextDtoKindEnum];


/**
 * Check if a given object implements the BeteiligterFreitextDto interface.
 */
export function instanceOfBeteiligterFreitextDto(value: object): value is BeteiligterFreitextDto {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BeteiligterFreitextDtoFromJSON(json: any): BeteiligterFreitextDto {
    return BeteiligterFreitextDtoFromJSONTyped(json, false);
}

export function BeteiligterFreitextDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeteiligterFreitextDto {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'name': json['name'],
        'rolle': json['rolle'] == null ? undefined : json['rolle'],
    };
}

export function BeteiligterFreitextDtoToJSON(json: any): BeteiligterFreitextDto {
    return BeteiligterFreitextDtoToJSONTyped(json, false);
}

export function BeteiligterFreitextDtoToJSONTyped(value?: BeteiligterFreitextDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'name': value['name'],
        'rolle': value['rolle'],
    };
}

