/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.37
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FahrzeugtypSollbesatzungDto } from './FahrzeugtypSollbesatzungDto';
import {
  FahrzeugtypSollbesatzungDtoFromJSON,
  FahrzeugtypSollbesatzungDtoFromJSONTyped,
  FahrzeugtypSollbesatzungDtoToJSON,
  FahrzeugtypSollbesatzungDtoToJSONTyped,
} from './FahrzeugtypSollbesatzungDto';

/**
 *
 * @export
 * @interface CreateFahrzeugtypDto
 */
export interface CreateFahrzeugtypDto {
  /**
   * Eindeutiger Code (z.B. RTW, NEF, KTW) - wird automatisch auf UPPERCASE normalisiert
   * @type {string}
   * @memberof CreateFahrzeugtypDto
   */
  code: string;
  /**
   * Vollständige Bezeichnung
   * @type {string}
   * @memberof CreateFahrzeugtypDto
   */
  bezeichnung: string;
  /**
   * Kategorie des Fahrzeugtyps
   * @type {string}
   * @memberof CreateFahrzeugtypDto
   */
  kategorie: CreateFahrzeugtypDtoKategorieEnum;
  /**
   * Soll-Besetzung pro Rolle (JSONB)
   * @type {FahrzeugtypSollbesatzungDto}
   * @memberof CreateFahrzeugtypDto
   */
  sollbesatzung?: FahrzeugtypSollbesatzungDto;
  /**
   * Optionale Beschreibung
   * @type {string}
   * @memberof CreateFahrzeugtypDto
   */
  beschreibung?: string;
}

/**
 * @export
 */
export const CreateFahrzeugtypDtoKategorieEnum = {
  Rettungsdienst: 'RETTUNGSDIENST',
  Fuehrung: 'FUEHRUNG',
  Transport: 'TRANSPORT',
  Sonstiges: 'SONSTIGES',
} as const;
export type CreateFahrzeugtypDtoKategorieEnum = (typeof CreateFahrzeugtypDtoKategorieEnum)[keyof typeof CreateFahrzeugtypDtoKategorieEnum];

/**
 * Check if a given object implements the CreateFahrzeugtypDto interface.
 */
export function instanceOfCreateFahrzeugtypDto(value: object): value is CreateFahrzeugtypDto {
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('bezeichnung' in value) || value['bezeichnung'] === undefined) return false;
  if (!('kategorie' in value) || value['kategorie'] === undefined) return false;
  return true;
}

export function CreateFahrzeugtypDtoFromJSON(json: any): CreateFahrzeugtypDto {
  return CreateFahrzeugtypDtoFromJSONTyped(json, false);
}

export function CreateFahrzeugtypDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFahrzeugtypDto {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'],
    bezeichnung: json['bezeichnung'],
    kategorie: json['kategorie'],
    sollbesatzung: json['sollbesatzung'] == null ? undefined : FahrzeugtypSollbesatzungDtoFromJSON(json['sollbesatzung']),
    beschreibung: json['beschreibung'] == null ? undefined : json['beschreibung'],
  };
}

export function CreateFahrzeugtypDtoToJSON(json: any): CreateFahrzeugtypDto {
  return CreateFahrzeugtypDtoToJSONTyped(json, false);
}

export function CreateFahrzeugtypDtoToJSONTyped(value?: CreateFahrzeugtypDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    bezeichnung: value['bezeichnung'],
    kategorie: value['kategorie'],
    sollbesatzung: FahrzeugtypSollbesatzungDtoToJSON(value['sollbesatzung']),
    beschreibung: value['beschreibung'],
  };
}
