/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateStammFahrzeugDto
 */
export interface CreateStammFahrzeugDto {
  /**
   * Fahrzeugbezeichnung (z.B. "RTW 1", "KTW 2")
   * @type {string}
   * @memberof CreateStammFahrzeugDto
   */
  rufname: string;
  /**
   * Funkrufzeichen (UNIQUE) - z.B. "Rotkreuz 83/1"
   * @type {string}
   * @memberof CreateStammFahrzeugDto
   */
  funkrufname: string;
  /**
   * Fahrzeugtyp-ID (FK zu Fahrzeugtyp aus Epic 1) - IMMUTABLE
   * @type {string}
   * @memberof CreateStammFahrzeugDto
   */
  fahrzeugtypId: string;
  /**
   * Kfz-Kennzeichen (z.B. "DA-RK 101")
   * @type {string}
   * @memberof CreateStammFahrzeugDto
   */
  kennzeichen?: string;
  /**
   * Baujahr des Fahrzeugs
   * @type {number}
   * @memberof CreateStammFahrzeugDto
   */
  baujahr?: number;
  /**
   * BOS-Funkkennung
   * @type {string}
   * @memberof CreateStammFahrzeugDto
   */
  funkkenungBOS?: string;
}

/**
 * Check if a given object implements the CreateStammFahrzeugDto interface.
 */
export function instanceOfCreateStammFahrzeugDto(value: object): value is CreateStammFahrzeugDto {
  if (!('rufname' in value) || value['rufname'] === undefined) return false;
  if (!('funkrufname' in value) || value['funkrufname'] === undefined) return false;
  if (!('fahrzeugtypId' in value) || value['fahrzeugtypId'] === undefined) return false;
  return true;
}

export function CreateStammFahrzeugDtoFromJSON(json: any): CreateStammFahrzeugDto {
  return CreateStammFahrzeugDtoFromJSONTyped(json, false);
}

export function CreateStammFahrzeugDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStammFahrzeugDto {
  if (json == null) {
    return json;
  }
  return {
    rufname: json['rufname'],
    funkrufname: json['funkrufname'],
    fahrzeugtypId: json['fahrzeugtypId'],
    kennzeichen: json['kennzeichen'] == null ? undefined : json['kennzeichen'],
    baujahr: json['baujahr'] == null ? undefined : json['baujahr'],
    funkkenungBOS: json['funkkenungBOS'] == null ? undefined : json['funkkenungBOS'],
  };
}

export function CreateStammFahrzeugDtoToJSON(json: any): CreateStammFahrzeugDto {
  return CreateStammFahrzeugDtoToJSONTyped(json, false);
}

export function CreateStammFahrzeugDtoToJSONTyped(value?: CreateStammFahrzeugDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    rufname: value['rufname'],
    funkrufname: value['funkrufname'],
    fahrzeugtypId: value['fahrzeugtypId'],
    kennzeichen: value['kennzeichen'],
    baujahr: value['baujahr'],
    funkkenungBOS: value['funkkenungBOS'],
  };
}
