/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.34
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreatePoiDto
 */
export interface CreatePoiDto {
  /**
   * ID der zugehörigen Lagekarte
   * @type {string}
   * @memberof CreatePoiDto
   */
  lagekarteId: string;
  /**
   * Typ des POI (z.B. EINSATZORT, FAHRZEUG, GEFAHRENQUELLE)
   * @type {string}
   * @memberof CreatePoiDto
   */
  type: CreatePoiDtoTypeEnum;
  /**
   * Name/Bezeichnung des POI
   * @type {string}
   * @memberof CreatePoiDto
   */
  name?: string;
  /**
   * MGRS Koordinaten (primäres Format, alternativ zu latitude/longitude oder adresse)
   * @type {string}
   * @memberof CreatePoiDto
   */
  mgrs?: string;
  /**
   * Adresse für automatisches Geocoding
   * @type {string}
   * @memberof CreatePoiDto
   */
  adresse?: string;
  /**
   * Geografische Breite (optional, wird aus MGRS berechnet oder manuell angegeben)
   * @type {number}
   * @memberof CreatePoiDto
   */
  latitude?: number;
  /**
   * Geografische Länge (optional, wird aus MGRS berechnet oder manuell angegeben)
   * @type {number}
   * @memberof CreatePoiDto
   */
  longitude?: number;
  /**
   * Icon-Identifier für Kartendarstellung
   * @type {string}
   * @memberof CreatePoiDto
   */
  icon?: string;
  /**
   * Zusätzliche Metadaten als JSON
   * @type {object}
   * @memberof CreatePoiDto
   */
  metadata?: object;
}

/**
 * @export
 */
export const CreatePoiDtoTypeEnum = {
  Einsatzort: 'EINSATZORT',
  Einsatzabschnitt: 'EINSATZABSCHNITT',
  Einsatzleitung: 'EINSATZLEITUNG',
  Fahrzeug: 'FAHRZEUG',
  Einheit: 'EINHEIT',
  Gefahrenquelle: 'GEFAHRENQUELLE',
  Sperrbereich: 'SPERRBEREICH',
  Versorgungspunkt: 'VERSORGUNGSPUNKT',
  Bereitstellungsraum: 'BEREITSTELLUNGSRAUM',
  Behandlungsplatz: 'BEHANDLUNGSPLATZ',
  Sammelstelle: 'SAMMELSTELLE',
  Unterkunft: 'UNTERKUNFT',
  Sonstiges: 'SONSTIGES',
} as const;
export type CreatePoiDtoTypeEnum = (typeof CreatePoiDtoTypeEnum)[keyof typeof CreatePoiDtoTypeEnum];

/**
 * Check if a given object implements the CreatePoiDto interface.
 */
export function instanceOfCreatePoiDto(value: object): value is CreatePoiDto {
  if (!('lagekarteId' in value) || value['lagekarteId'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  return true;
}

export function CreatePoiDtoFromJSON(json: any): CreatePoiDto {
  return CreatePoiDtoFromJSONTyped(json, false);
}

export function CreatePoiDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePoiDto {
  if (json == null) {
    return json;
  }
  return {
    lagekarteId: json['lagekarteId'],
    type: json['type'],
    name: json['name'] == null ? undefined : json['name'],
    mgrs: json['mgrs'] == null ? undefined : json['mgrs'],
    adresse: json['adresse'] == null ? undefined : json['adresse'],
    latitude: json['latitude'] == null ? undefined : json['latitude'],
    longitude: json['longitude'] == null ? undefined : json['longitude'],
    icon: json['icon'] == null ? undefined : json['icon'],
    metadata: json['metadata'] == null ? undefined : json['metadata'],
  };
}

export function CreatePoiDtoToJSON(json: any): CreatePoiDto {
  return CreatePoiDtoToJSONTyped(json, false);
}

export function CreatePoiDtoToJSONTyped(value?: CreatePoiDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    lagekarteId: value['lagekarteId'],
    type: value['type'],
    name: value['name'],
    mgrs: value['mgrs'],
    adresse: value['adresse'],
    latitude: value['latitude'],
    longitude: value['longitude'],
    icon: value['icon'],
    metadata: value['metadata'],
  };
}
