/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.94-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisconnectResponseDto
 */
export interface DisconnectResponseDto {
    /**
     * Wurde die Integration erfolgreich getrennt?
     * @type {boolean}
     * @memberof DisconnectResponseDto
     */
    disconnected: boolean;
    /**
     * Zeitpunkt der Trennung
     * @type {Date}
     * @memberof DisconnectResponseDto
     */
    disconnectedAt: Date;
}

/**
 * Check if a given object implements the DisconnectResponseDto interface.
 */
export function instanceOfDisconnectResponseDto(value: object): value is DisconnectResponseDto {
    if (!('disconnected' in value) || value['disconnected'] === undefined) return false;
    if (!('disconnectedAt' in value) || value['disconnectedAt'] === undefined) return false;
    return true;
}

export function DisconnectResponseDtoFromJSON(json: any): DisconnectResponseDto {
    return DisconnectResponseDtoFromJSONTyped(json, false);
}

export function DisconnectResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisconnectResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'disconnected': json['disconnected'],
        'disconnectedAt': (new Date(json['disconnectedAt'])),
    };
}

export function DisconnectResponseDtoToJSON(json: any): DisconnectResponseDto {
    return DisconnectResponseDtoToJSONTyped(json, false);
}

export function DisconnectResponseDtoToJSONTyped(value?: DisconnectResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disconnected': value['disconnected'],
        'disconnectedAt': ((value['disconnectedAt']).toISOString()),
    };
}

