/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.80-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EinsatzEinheitPersonDto } from './EinsatzEinheitPersonDto';
import {
    EinsatzEinheitPersonDtoFromJSON,
    EinsatzEinheitPersonDtoFromJSONTyped,
    EinsatzEinheitPersonDtoToJSON,
    EinsatzEinheitPersonDtoToJSONTyped,
} from './EinsatzEinheitPersonDto';
import type { EinsatzEinheitFahrzeugPersonDto } from './EinsatzEinheitFahrzeugPersonDto';
import {
    EinsatzEinheitFahrzeugPersonDtoFromJSON,
    EinsatzEinheitFahrzeugPersonDtoFromJSONTyped,
    EinsatzEinheitFahrzeugPersonDtoToJSON,
    EinsatzEinheitFahrzeugPersonDtoToJSONTyped,
} from './EinsatzEinheitFahrzeugPersonDto';

/**
 * 
 * @export
 * @interface EinsatzEinheitDetailsDto
 */
export interface EinsatzEinheitDetailsDto {
    /**
     * Eindeutige ID der EinsatzEinheit (CUID2)
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    id: string;
    /**
     * Einsatz-ID zu dem diese Einheit gehört (UUID)
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    einsatzId: string;
    /**
     * Übergeordnete Einheit-ID (CUID2), null für Root-Einheiten
     * @type {object}
     * @memberof EinsatzEinheitDetailsDto
     */
    parentId?: object | null;
    /**
     * Name der Einheit
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    name: string;
    /**
     * Typ der taktischen Einheit
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    typ: EinsatzEinheitDetailsDtoTypEnum;
    /**
     * Funktion/Aufgabe der Einheit
     * @type {object}
     * @memberof EinsatzEinheitDetailsDto
     */
    funktion?: object | null;
    /**
     * Aktueller Status der Einheit
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    status: EinsatzEinheitDetailsDtoStatusEnum;
    /**
     * EinsatzPerson-ID des Einheitenführers (CUID2)
     * @type {object}
     * @memberof EinsatzEinheitDetailsDto
     */
    einheitenfuehrerId?: object | null;
    /**
     * Name des Einheitenführers (Vorname Nachname)
     * @type {object}
     * @memberof EinsatzEinheitDetailsDto
     */
    einheitenfuehrerName?: object | null;
    /**
     * Soll-Stärke (geplante Personenanzahl)
     * @type {number}
     * @memberof EinsatzEinheitDetailsDto
     */
    sollStaerke: number;
    /**
     * Ist-Stärke (tatsächlich zugewiesene Personen)
     * @type {number}
     * @memberof EinsatzEinheitDetailsDto
     */
    istStaerke: number;
    /**
     * Aktueller Auftrag der Einheit
     * @type {object}
     * @memberof EinsatzEinheitDetailsDto
     */
    auftrag?: object | null;
    /**
     * Einsatzort der Einheit
     * @type {object}
     * @memberof EinsatzEinheitDetailsDto
     */
    einsatzort?: object | null;
    /**
     * Erstellungszeitpunkt (ISO 8601)
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    createdAt: string;
    /**
     * Letzte Aktualisierung (ISO 8601)
     * @type {string}
     * @memberof EinsatzEinheitDetailsDto
     */
    updatedAt: string;
    /**
     * Explizit zugewiesene Personen der Einheit
     * @type {Array<EinsatzEinheitPersonDto>}
     * @memberof EinsatzEinheitDetailsDto
     */
    personen: Array<EinsatzEinheitPersonDto>;
    /**
     * Implizit zugewiesene Personen über Fahrzeug-Besatzung (nicht einzeln entfernbar)
     * @type {Array<EinsatzEinheitFahrzeugPersonDto>}
     * @memberof EinsatzEinheitDetailsDto
     */
    fahrzeugPersonen: Array<EinsatzEinheitFahrzeugPersonDto>;
    /**
     * Einheitenführer (aufgelöste Person), null wenn nicht besetzt
     * @type {EinsatzEinheitPersonDto}
     * @memberof EinsatzEinheitDetailsDto
     */
    einheitenfuehrer?: EinsatzEinheitPersonDto | null;
}


/**
 * @export
 */
export const EinsatzEinheitDetailsDtoTypEnum = {
    Trupp: 'TRUPP',
    Staffel: 'STAFFEL',
    Gruppe: 'GRUPPE',
    Zug: 'ZUG',
    Abschnitt: 'ABSCHNITT'
} as const;
export type EinsatzEinheitDetailsDtoTypEnum = typeof EinsatzEinheitDetailsDtoTypEnum[keyof typeof EinsatzEinheitDetailsDtoTypEnum];

/**
 * @export
 */
export const EinsatzEinheitDetailsDtoStatusEnum = {
    Aufgestellt: 'AUFGESTELLT',
    Einsatzbereit: 'EINSATZBEREIT',
    ImEinsatz: 'IM_EINSATZ',
    InReserve: 'IN_RESERVE',
    Aufgeloest: 'AUFGELOEST'
} as const;
export type EinsatzEinheitDetailsDtoStatusEnum = typeof EinsatzEinheitDetailsDtoStatusEnum[keyof typeof EinsatzEinheitDetailsDtoStatusEnum];


/**
 * Check if a given object implements the EinsatzEinheitDetailsDto interface.
 */
export function instanceOfEinsatzEinheitDetailsDto(value: object): value is EinsatzEinheitDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('einsatzId' in value) || value['einsatzId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('typ' in value) || value['typ'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sollStaerke' in value) || value['sollStaerke'] === undefined) return false;
    if (!('istStaerke' in value) || value['istStaerke'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('personen' in value) || value['personen'] === undefined) return false;
    if (!('fahrzeugPersonen' in value) || value['fahrzeugPersonen'] === undefined) return false;
    return true;
}

export function EinsatzEinheitDetailsDtoFromJSON(json: any): EinsatzEinheitDetailsDto {
    return EinsatzEinheitDetailsDtoFromJSONTyped(json, false);
}

export function EinsatzEinheitDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzEinheitDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'einsatzId': json['einsatzId'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'name': json['name'],
        'typ': json['typ'],
        'funktion': json['funktion'] == null ? undefined : json['funktion'],
        'status': json['status'],
        'einheitenfuehrerId': json['einheitenfuehrerId'] == null ? undefined : json['einheitenfuehrerId'],
        'einheitenfuehrerName': json['einheitenfuehrerName'] == null ? undefined : json['einheitenfuehrerName'],
        'sollStaerke': json['sollStaerke'],
        'istStaerke': json['istStaerke'],
        'auftrag': json['auftrag'] == null ? undefined : json['auftrag'],
        'einsatzort': json['einsatzort'] == null ? undefined : json['einsatzort'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'personen': ((json['personen'] as Array<any>).map(EinsatzEinheitPersonDtoFromJSON)),
        'fahrzeugPersonen': ((json['fahrzeugPersonen'] as Array<any>).map(EinsatzEinheitFahrzeugPersonDtoFromJSON)),
        'einheitenfuehrer': json['einheitenfuehrer'] == null ? undefined : EinsatzEinheitPersonDtoFromJSON(json['einheitenfuehrer']),
    };
}

export function EinsatzEinheitDetailsDtoToJSON(json: any): EinsatzEinheitDetailsDto {
    return EinsatzEinheitDetailsDtoToJSONTyped(json, false);
}

export function EinsatzEinheitDetailsDtoToJSONTyped(value?: EinsatzEinheitDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'einsatzId': value['einsatzId'],
        'parentId': value['parentId'],
        'name': value['name'],
        'typ': value['typ'],
        'funktion': value['funktion'],
        'status': value['status'],
        'einheitenfuehrerId': value['einheitenfuehrerId'],
        'einheitenfuehrerName': value['einheitenfuehrerName'],
        'sollStaerke': value['sollStaerke'],
        'istStaerke': value['istStaerke'],
        'auftrag': value['auftrag'],
        'einsatzort': value['einsatzort'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'personen': ((value['personen'] as Array<any>).map(EinsatzEinheitPersonDtoToJSON)),
        'fahrzeugPersonen': ((value['fahrzeugPersonen'] as Array<any>).map(EinsatzEinheitFahrzeugPersonDtoToJSON)),
        'einheitenfuehrer': EinsatzEinheitPersonDtoToJSON(value['einheitenfuehrer']),
    };
}

