/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.46
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
  AuthControllerUnifiedAuth200ResponseMetaFromJSON,
  AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
  AuthControllerUnifiedAuth200ResponseMetaToJSON,
  AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { CompletenessResponseDto } from './CompletenessResponseDto';
import { CompletenessResponseDtoFromJSON, CompletenessResponseDtoFromJSONTyped, CompletenessResponseDtoToJSON, CompletenessResponseDtoToJSONTyped } from './CompletenessResponseDto';

/**
 *
 * @export
 * @interface EinsatzControllerGetCompletenessVAlpha200Response
 */
export interface EinsatzControllerGetCompletenessVAlpha200Response {
  /**
   *
   * @type {CompletenessResponseDto}
   * @memberof EinsatzControllerGetCompletenessVAlpha200Response
   */
  data: CompletenessResponseDto;
  /**
   *
   * @type {AuthControllerUnifiedAuth200ResponseMeta}
   * @memberof EinsatzControllerGetCompletenessVAlpha200Response
   */
  meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the EinsatzControllerGetCompletenessVAlpha200Response interface.
 */
export function instanceOfEinsatzControllerGetCompletenessVAlpha200Response(value: object): value is EinsatzControllerGetCompletenessVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseFromJSON(json: any): EinsatzControllerGetCompletenessVAlpha200Response {
  return EinsatzControllerGetCompletenessVAlpha200ResponseFromJSONTyped(json, false);
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzControllerGetCompletenessVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: CompletenessResponseDtoFromJSON(json['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
  };
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseToJSON(json: any): EinsatzControllerGetCompletenessVAlpha200Response {
  return EinsatzControllerGetCompletenessVAlpha200ResponseToJSONTyped(json, false);
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseToJSONTyped(value?: EinsatzControllerGetCompletenessVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: CompletenessResponseDtoToJSON(value['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
  };
}
