/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EinsatzEinheitFahrzeugPersonDto
 */
export interface EinsatzEinheitFahrzeugPersonDto {
    /**
     * EinsatzPerson ID (CUID2)
     * @type {string}
     * @memberof EinsatzEinheitFahrzeugPersonDto
     */
    id: string;
    /**
     * Vorname der Person
     * @type {string}
     * @memberof EinsatzEinheitFahrzeugPersonDto
     */
    vorname: string;
    /**
     * Nachname der Person
     * @type {string}
     * @memberof EinsatzEinheitFahrzeugPersonDto
     */
    nachname: string;
    /**
     * Funktion der Person
     * @type {string}
     * @memberof EinsatzEinheitFahrzeugPersonDto
     */
    funktion: string;
    /**
     * Funkrufname der Person
     * @type {object}
     * @memberof EinsatzEinheitFahrzeugPersonDto
     */
    funkrufname?: object | null;
    /**
     * Funkrufname des Fahrzeugs, dem die Person als Besatzung zugewiesen ist
     * @type {string}
     * @memberof EinsatzEinheitFahrzeugPersonDto
     */
    fahrzeugFunkrufname: string;
}

/**
 * Check if a given object implements the EinsatzEinheitFahrzeugPersonDto interface.
 */
export function instanceOfEinsatzEinheitFahrzeugPersonDto(value: object): value is EinsatzEinheitFahrzeugPersonDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('vorname' in value) || value['vorname'] === undefined) return false;
    if (!('nachname' in value) || value['nachname'] === undefined) return false;
    if (!('funktion' in value) || value['funktion'] === undefined) return false;
    if (!('fahrzeugFunkrufname' in value) || value['fahrzeugFunkrufname'] === undefined) return false;
    return true;
}

export function EinsatzEinheitFahrzeugPersonDtoFromJSON(json: any): EinsatzEinheitFahrzeugPersonDto {
    return EinsatzEinheitFahrzeugPersonDtoFromJSONTyped(json, false);
}

export function EinsatzEinheitFahrzeugPersonDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzEinheitFahrzeugPersonDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'vorname': json['vorname'],
        'nachname': json['nachname'],
        'funktion': json['funktion'],
        'funkrufname': json['funkrufname'] == null ? undefined : json['funkrufname'],
        'fahrzeugFunkrufname': json['fahrzeugFunkrufname'],
    };
}

export function EinsatzEinheitFahrzeugPersonDtoToJSON(json: any): EinsatzEinheitFahrzeugPersonDto {
    return EinsatzEinheitFahrzeugPersonDtoToJSONTyped(json, false);
}

export function EinsatzEinheitFahrzeugPersonDtoToJSONTyped(value?: EinsatzEinheitFahrzeugPersonDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'vorname': value['vorname'],
        'nachname': value['nachname'],
        'funktion': value['funktion'],
        'funkrufname': value['funkrufname'],
        'fahrzeugFunkrufname': value['fahrzeugFunkrufname'],
    };
}

