/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
  AuthControllerUnifiedAuth200ResponseMetaFromJSON,
  AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
  AuthControllerUnifiedAuth200ResponseMetaToJSON,
  AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { EinsatzDetailsDto } from './EinsatzDetailsDto';
import { EinsatzDetailsDtoFromJSON, EinsatzDetailsDtoFromJSONTyped, EinsatzDetailsDtoToJSON, EinsatzDetailsDtoToJSONTyped } from './EinsatzDetailsDto';

/**
 *
 * @export
 * @interface EinsatzControllerGetEinsatzDetailsVAlpha200Response
 */
export interface EinsatzControllerGetEinsatzDetailsVAlpha200Response {
  /**
   *
   * @type {EinsatzDetailsDto}
   * @memberof EinsatzControllerGetEinsatzDetailsVAlpha200Response
   */
  data: EinsatzDetailsDto;
  /**
   *
   * @type {AuthControllerUnifiedAuth200ResponseMeta}
   * @memberof EinsatzControllerGetEinsatzDetailsVAlpha200Response
   */
  meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the EinsatzControllerGetEinsatzDetailsVAlpha200Response interface.
 */
export function instanceOfEinsatzControllerGetEinsatzDetailsVAlpha200Response(value: object): value is EinsatzControllerGetEinsatzDetailsVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function EinsatzControllerGetEinsatzDetailsVAlpha200ResponseFromJSON(json: any): EinsatzControllerGetEinsatzDetailsVAlpha200Response {
  return EinsatzControllerGetEinsatzDetailsVAlpha200ResponseFromJSONTyped(json, false);
}

export function EinsatzControllerGetEinsatzDetailsVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzControllerGetEinsatzDetailsVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: EinsatzDetailsDtoFromJSON(json['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
  };
}

export function EinsatzControllerGetEinsatzDetailsVAlpha200ResponseToJSON(json: any): EinsatzControllerGetEinsatzDetailsVAlpha200Response {
  return EinsatzControllerGetEinsatzDetailsVAlpha200ResponseToJSONTyped(json, false);
}

export function EinsatzControllerGetEinsatzDetailsVAlpha200ResponseToJSONTyped(value?: EinsatzControllerGetEinsatzDetailsVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: EinsatzDetailsDtoToJSON(value['data']),
    meta: AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
  };
}
