/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInner } from './EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInner';
import {
  EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInnerFromJSON,
  EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInnerFromJSONTyped,
  EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInnerToJSON,
  EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInnerToJSONTyped,
} from './EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInner';

/**
 *
 * @export
 * @interface EinsatzControllerGetCompletenessVAlpha200Response
 */
export interface EinsatzControllerGetCompletenessVAlpha200Response {
  /**
   *
   * @type {number}
   * @memberof EinsatzControllerGetCompletenessVAlpha200Response
   */
  score?: number;
  /**
   *
   * @type {boolean}
   * @memberof EinsatzControllerGetCompletenessVAlpha200Response
   */
  isComplete?: boolean;
  /**
   *
   * @type {Array<EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInner>}
   * @memberof EinsatzControllerGetCompletenessVAlpha200Response
   */
  missingFields?: Array<EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInner>;
}

/**
 * Check if a given object implements the EinsatzControllerGetCompletenessVAlpha200Response interface.
 */
export function instanceOfEinsatzControllerGetCompletenessVAlpha200Response(value: object): value is EinsatzControllerGetCompletenessVAlpha200Response {
  return true;
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseFromJSON(json: any): EinsatzControllerGetCompletenessVAlpha200Response {
  return EinsatzControllerGetCompletenessVAlpha200ResponseFromJSONTyped(json, false);
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzControllerGetCompletenessVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    score: json['score'] == null ? undefined : json['score'],
    isComplete: json['isComplete'] == null ? undefined : json['isComplete'],
    missingFields: json['missingFields'] == null ? undefined : (json['missingFields'] as Array<any>).map(EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInnerFromJSON),
  };
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseToJSON(json: any): EinsatzControllerGetCompletenessVAlpha200Response {
  return EinsatzControllerGetCompletenessVAlpha200ResponseToJSONTyped(json, false);
}

export function EinsatzControllerGetCompletenessVAlpha200ResponseToJSONTyped(value?: EinsatzControllerGetCompletenessVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    score: value['score'],
    isComplete: value['isComplete'],
    missingFields: value['missingFields'] == null ? undefined : (value['missingFields'] as Array<any>).map(EinsatzControllerGetCompletenessVAlpha200ResponseMissingFieldsInnerToJSON),
  };
}
