/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EinsatzListItemDto } from './EinsatzListItemDto';
import { EinsatzListItemDtoFromJSON, EinsatzListItemDtoFromJSONTyped, EinsatzListItemDtoToJSON, EinsatzListItemDtoToJSONTyped } from './EinsatzListItemDto';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
  AuthControllerUnifiedAuth200ResponseMetaFromJSON,
  AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
  AuthControllerUnifiedAuth200ResponseMetaToJSON,
  AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { UserControllerFindAllBasicVAlpha200ResponsePagination } from './UserControllerFindAllBasicVAlpha200ResponsePagination';
import {
  UserControllerFindAllBasicVAlpha200ResponsePaginationFromJSON,
  UserControllerFindAllBasicVAlpha200ResponsePaginationFromJSONTyped,
  UserControllerFindAllBasicVAlpha200ResponsePaginationToJSON,
  UserControllerFindAllBasicVAlpha200ResponsePaginationToJSONTyped,
} from './UserControllerFindAllBasicVAlpha200ResponsePagination';

/**
 *
 * @export
 * @interface EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response
 */
export interface EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response {
  /**
   *
   * @type {Array<EinsatzListItemDto>}
   * @memberof EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response
   */
  data: Array<EinsatzListItemDto>;
  /**
   *
   * @type {AuthControllerUnifiedAuth200ResponseMeta}
   * @memberof EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response
   */
  meta: AuthControllerUnifiedAuth200ResponseMeta;
  /**
   *
   * @type {UserControllerFindAllBasicVAlpha200ResponsePagination}
   * @memberof EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response
   */
  pagination?: UserControllerFindAllBasicVAlpha200ResponsePagination;
}

/**
 * Check if a given object implements the EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response interface.
 */
export function instanceOfEinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response(value: object): value is EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200ResponseFromJSON(json: any): EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response {
  return EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200ResponseFromJSONTyped(json, false);
}

export function EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(EinsatzListItemDtoFromJSON),
    meta: AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
    pagination: json['pagination'] == null ? undefined : UserControllerFindAllBasicVAlpha200ResponsePaginationFromJSON(json['pagination']),
  };
}

export function EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200ResponseToJSON(json: any): EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response {
  return EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200ResponseToJSONTyped(json, false);
}

export function EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200ResponseToJSONTyped(
  value?: EinsatzControllerGetActiveEinsaetzeWithCountsVAlpha200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(EinsatzListItemDtoToJSON),
    meta: AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
    pagination: UserControllerFindAllBasicVAlpha200ResponsePaginationToJSON(value['pagination']),
  };
}
