/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EinsatzResponseDto } from './EinsatzResponseDto';
import { EinsatzResponseDtoFromJSON, EinsatzResponseDtoFromJSONTyped, EinsatzResponseDtoToJSON, EinsatzResponseDtoToJSONTyped } from './EinsatzResponseDto';
import type { EinsatzControllerFindAllVAlpha200ResponseMeta } from './EinsatzControllerFindAllVAlpha200ResponseMeta';
import {
  EinsatzControllerFindAllVAlpha200ResponseMetaFromJSON,
  EinsatzControllerFindAllVAlpha200ResponseMetaFromJSONTyped,
  EinsatzControllerFindAllVAlpha200ResponseMetaToJSON,
  EinsatzControllerFindAllVAlpha200ResponseMetaToJSONTyped,
} from './EinsatzControllerFindAllVAlpha200ResponseMeta';

/**
 *
 * @export
 * @interface EinsatzControllerCreateVAlpha200Response
 */
export interface EinsatzControllerCreateVAlpha200Response {
  /**
   *
   * @type {EinsatzResponseDto}
   * @memberof EinsatzControllerCreateVAlpha200Response
   */
  data: EinsatzResponseDto;
  /**
   *
   * @type {EinsatzControllerFindAllVAlpha200ResponseMeta}
   * @memberof EinsatzControllerCreateVAlpha200Response
   */
  meta: EinsatzControllerFindAllVAlpha200ResponseMeta;
}

/**
 * Check if a given object implements the EinsatzControllerCreateVAlpha200Response interface.
 */
export function instanceOfEinsatzControllerCreateVAlpha200Response(value: object): value is EinsatzControllerCreateVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function EinsatzControllerCreateVAlpha200ResponseFromJSON(json: any): EinsatzControllerCreateVAlpha200Response {
  return EinsatzControllerCreateVAlpha200ResponseFromJSONTyped(json, false);
}

export function EinsatzControllerCreateVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzControllerCreateVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: EinsatzResponseDtoFromJSON(json['data']),
    meta: EinsatzControllerFindAllVAlpha200ResponseMetaFromJSON(json['meta']),
  };
}

export function EinsatzControllerCreateVAlpha200ResponseToJSON(json: any): EinsatzControllerCreateVAlpha200Response {
  return EinsatzControllerCreateVAlpha200ResponseToJSONTyped(json, false);
}

export function EinsatzControllerCreateVAlpha200ResponseToJSONTyped(value?: EinsatzControllerCreateVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: EinsatzResponseDtoToJSON(value['data']),
    meta: EinsatzControllerFindAllVAlpha200ResponseMetaToJSON(value['meta']),
  };
}
