/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErforderlicheQualifikationDto
 */
export interface ErforderlicheQualifikationDto {
    /**
     * ID der Qualifikation
     * @type {string}
     * @memberof ErforderlicheQualifikationDto
     */
    qualifikationId: string;
    /**
     * Name der Qualifikation
     * @type {string}
     * @memberof ErforderlicheQualifikationDto
     */
    qualifikationName: string;
    /**
     * Abkürzung der Qualifikation
     * @type {string}
     * @memberof ErforderlicheQualifikationDto
     */
    qualifikationAbkuerzung: string;
    /**
     * Ob diese Qualifikation Pflicht ist
     * @type {boolean}
     * @memberof ErforderlicheQualifikationDto
     */
    istPflicht: boolean;
}

/**
 * Check if a given object implements the ErforderlicheQualifikationDto interface.
 */
export function instanceOfErforderlicheQualifikationDto(value: object): value is ErforderlicheQualifikationDto {
    if (!('qualifikationId' in value) || value['qualifikationId'] === undefined) return false;
    if (!('qualifikationName' in value) || value['qualifikationName'] === undefined) return false;
    if (!('qualifikationAbkuerzung' in value) || value['qualifikationAbkuerzung'] === undefined) return false;
    if (!('istPflicht' in value) || value['istPflicht'] === undefined) return false;
    return true;
}

export function ErforderlicheQualifikationDtoFromJSON(json: any): ErforderlicheQualifikationDto {
    return ErforderlicheQualifikationDtoFromJSONTyped(json, false);
}

export function ErforderlicheQualifikationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErforderlicheQualifikationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'qualifikationId': json['qualifikationId'],
        'qualifikationName': json['qualifikationName'],
        'qualifikationAbkuerzung': json['qualifikationAbkuerzung'],
        'istPflicht': json['istPflicht'],
    };
}

export function ErforderlicheQualifikationDtoToJSON(json: any): ErforderlicheQualifikationDto {
    return ErforderlicheQualifikationDtoToJSONTyped(json, false);
}

export function ErforderlicheQualifikationDtoToJSONTyped(value?: ErforderlicheQualifikationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qualifikationId': value['qualifikationId'],
        'qualifikationName': value['qualifikationName'],
        'qualifikationAbkuerzung': value['qualifikationAbkuerzung'],
        'istPflicht': value['istPflicht'],
    };
}

