/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.70-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErinnerungStatistikDto } from './ErinnerungStatistikDto';
import {
    ErinnerungStatistikDtoFromJSON,
    ErinnerungStatistikDtoFromJSONTyped,
    ErinnerungStatistikDtoToJSON,
    ErinnerungStatistikDtoToJSONTyped,
} from './ErinnerungStatistikDto';
import type { HealthControllerGetIntegrationHealth200ResponseMeta } from './HealthControllerGetIntegrationHealth200ResponseMeta';
import {
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSONTyped,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSONTyped,
} from './HealthControllerGetIntegrationHealth200ResponseMeta';

/**
 * 
 * @export
 * @interface ErinnerungControllerGetStatistikVAlpha200Response
 */
export interface ErinnerungControllerGetStatistikVAlpha200Response {
    /**
     * 
     * @type {ErinnerungStatistikDto}
     * @memberof ErinnerungControllerGetStatistikVAlpha200Response
     */
    data: ErinnerungStatistikDto;
    /**
     * 
     * @type {HealthControllerGetIntegrationHealth200ResponseMeta}
     * @memberof ErinnerungControllerGetStatistikVAlpha200Response
     */
    meta: HealthControllerGetIntegrationHealth200ResponseMeta;
}

/**
 * Check if a given object implements the ErinnerungControllerGetStatistikVAlpha200Response interface.
 */
export function instanceOfErinnerungControllerGetStatistikVAlpha200Response(value: object): value is ErinnerungControllerGetStatistikVAlpha200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ErinnerungControllerGetStatistikVAlpha200ResponseFromJSON(json: any): ErinnerungControllerGetStatistikVAlpha200Response {
    return ErinnerungControllerGetStatistikVAlpha200ResponseFromJSONTyped(json, false);
}

export function ErinnerungControllerGetStatistikVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErinnerungControllerGetStatistikVAlpha200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ErinnerungStatistikDtoFromJSON(json['data']),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaFromJSON(json['meta']),
    };
}

export function ErinnerungControllerGetStatistikVAlpha200ResponseToJSON(json: any): ErinnerungControllerGetStatistikVAlpha200Response {
    return ErinnerungControllerGetStatistikVAlpha200ResponseToJSONTyped(json, false);
}

export function ErinnerungControllerGetStatistikVAlpha200ResponseToJSONTyped(value?: ErinnerungControllerGetStatistikVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ErinnerungStatistikDtoToJSON(value['data']),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaToJSON(value['meta']),
    };
}

