/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
    AuthControllerUnifiedAuth200ResponseMetaFromJSON,
    AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
    AuthControllerUnifiedAuth200ResponseMetaToJSON,
    AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { ErinnerungEtbHistoryDto } from './ErinnerungEtbHistoryDto';
import {
    ErinnerungEtbHistoryDtoFromJSON,
    ErinnerungEtbHistoryDtoFromJSONTyped,
    ErinnerungEtbHistoryDtoToJSON,
    ErinnerungEtbHistoryDtoToJSONTyped,
} from './ErinnerungEtbHistoryDto';

/**
 * 
 * @export
 * @interface ErinnerungControllerGetEtbHistoryVAlpha200Response
 */
export interface ErinnerungControllerGetEtbHistoryVAlpha200Response {
    /**
     * 
     * @type {ErinnerungEtbHistoryDto}
     * @memberof ErinnerungControllerGetEtbHistoryVAlpha200Response
     */
    data: ErinnerungEtbHistoryDto;
    /**
     * 
     * @type {AuthControllerUnifiedAuth200ResponseMeta}
     * @memberof ErinnerungControllerGetEtbHistoryVAlpha200Response
     */
    meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the ErinnerungControllerGetEtbHistoryVAlpha200Response interface.
 */
export function instanceOfErinnerungControllerGetEtbHistoryVAlpha200Response(value: object): value is ErinnerungControllerGetEtbHistoryVAlpha200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ErinnerungControllerGetEtbHistoryVAlpha200ResponseFromJSON(json: any): ErinnerungControllerGetEtbHistoryVAlpha200Response {
    return ErinnerungControllerGetEtbHistoryVAlpha200ResponseFromJSONTyped(json, false);
}

export function ErinnerungControllerGetEtbHistoryVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErinnerungControllerGetEtbHistoryVAlpha200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ErinnerungEtbHistoryDtoFromJSON(json['data']),
        'meta': AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
    };
}

export function ErinnerungControllerGetEtbHistoryVAlpha200ResponseToJSON(json: any): ErinnerungControllerGetEtbHistoryVAlpha200Response {
    return ErinnerungControllerGetEtbHistoryVAlpha200ResponseToJSONTyped(json, false);
}

export function ErinnerungControllerGetEtbHistoryVAlpha200ResponseToJSONTyped(value?: ErinnerungControllerGetEtbHistoryVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ErinnerungEtbHistoryDtoToJSON(value['data']),
        'meta': AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
    };
}

