/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiMeta } from "./ApiMeta";
import {
  ApiMetaFromJSON,
  ApiMetaFromJSONTyped,
  ApiMetaToJSON,
  ApiMetaToJSONTyped,
} from "./ApiMeta";
import type { EtbAttachment } from "./EtbAttachment";
import {
  EtbAttachmentFromJSON,
  EtbAttachmentFromJSONTyped,
  EtbAttachmentToJSON,
  EtbAttachmentToJSONTyped,
} from "./EtbAttachment";

/**
 *
 * @export
 * @interface EtbAttachmentsResponse
 */
export interface EtbAttachmentsResponse {
  /**
   * Metadaten zur Antwort
   * @type {ApiMeta}
   * @memberof EtbAttachmentsResponse
   */
  meta: ApiMeta;
  /**
   * Optionale Nachricht
   * @type {string}
   * @memberof EtbAttachmentsResponse
   */
  message?: string;
  /**
   * Liste von ETB-Anlagen
   * @type {Array<EtbAttachment>}
   * @memberof EtbAttachmentsResponse
   */
  data: Array<EtbAttachment>;
}

/**
 * Check if a given object implements the EtbAttachmentsResponse interface.
 */
export function instanceOfEtbAttachmentsResponse(
  value: object,
): value is EtbAttachmentsResponse {
  if (!("meta" in value) || value["meta"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function EtbAttachmentsResponseFromJSON(
  json: any,
): EtbAttachmentsResponse {
  return EtbAttachmentsResponseFromJSONTyped(json, false);
}

export function EtbAttachmentsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EtbAttachmentsResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json["meta"]),
    message: json["message"] == null ? undefined : json["message"],
    data: (json["data"] as Array<any>).map(EtbAttachmentFromJSON),
  };
}

export function EtbAttachmentsResponseToJSON(
  json: any,
): EtbAttachmentsResponse {
  return EtbAttachmentsResponseToJSONTyped(json, false);
}

export function EtbAttachmentsResponseToJSONTyped(
  value?: EtbAttachmentsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value["meta"]),
    message: value["message"],
    data: (value["data"] as Array<any>).map(EtbAttachmentToJSON),
  };
}
