/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiMeta } from "./ApiMeta";
import {
  ApiMetaFromJSON,
  ApiMetaFromJSONTyped,
  ApiMetaToJSON,
  ApiMetaToJSONTyped,
} from "./ApiMeta";
import type { EtbEntriesData } from "./EtbEntriesData";
import {
  EtbEntriesDataFromJSON,
  EtbEntriesDataFromJSONTyped,
  EtbEntriesDataToJSON,
  EtbEntriesDataToJSONTyped,
} from "./EtbEntriesData";

/**
 *
 * @export
 * @interface EtbEntriesResponse
 */
export interface EtbEntriesResponse {
  /**
   * Metadaten zur Antwort
   * @type {ApiMeta}
   * @memberof EtbEntriesResponse
   */
  meta: ApiMeta;
  /**
   * Optionale Nachricht
   * @type {string}
   * @memberof EtbEntriesResponse
   */
  message?: string;
  /**
   * ETB-Einträge und Gesamtzahl
   * @type {EtbEntriesData}
   * @memberof EtbEntriesResponse
   */
  data: EtbEntriesData;
}

/**
 * Check if a given object implements the EtbEntriesResponse interface.
 */
export function instanceOfEtbEntriesResponse(
  value: object,
): value is EtbEntriesResponse {
  if (!("meta" in value) || value["meta"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function EtbEntriesResponseFromJSON(json: any): EtbEntriesResponse {
  return EtbEntriesResponseFromJSONTyped(json, false);
}

export function EtbEntriesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EtbEntriesResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json["meta"]),
    message: json["message"] == null ? undefined : json["message"],
    data: EtbEntriesDataFromJSON(json["data"]),
  };
}

export function EtbEntriesResponseToJSON(json: any): EtbEntriesResponse {
  return EtbEntriesResponseToJSONTyped(json, false);
}

export function EtbEntriesResponseToJSONTyped(
  value?: EtbEntriesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value["meta"]),
    message: value["message"],
    data: EtbEntriesDataToJSON(value["data"]),
  };
}
