/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.56-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { A } from './A';
import {
    AFromJSON,
    AFromJSONTyped,
    AToJSON,
    AToJSONTyped,
} from './A';

/**
 * 
 * @export
 * @interface EtbSnapshotDto
 */
export interface EtbSnapshotDto {
    /**
     * Versionsnummer zum Snapshot-Zeitpunkt
     * @type {number}
     * @memberof EtbSnapshotDto
     */
    version: number;
    /**
     * Zeitpunkt der Snapshot-Erstellung
     * @type {Date}
     * @memberof EtbSnapshotDto
     */
    snapshotAt: Date;
    /**
     * Alle Einträge zum Snapshot-Zeitpunkt
     * @type {Array<Array<A>>}
     * @memberof EtbSnapshotDto
     */
    eintraege: Array<Array<A>>;
}

/**
 * Check if a given object implements the EtbSnapshotDto interface.
 */
export function instanceOfEtbSnapshotDto(value: object): value is EtbSnapshotDto {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('snapshotAt' in value) || value['snapshotAt'] === undefined) return false;
    if (!('eintraege' in value) || value['eintraege'] === undefined) return false;
    return true;
}

export function EtbSnapshotDtoFromJSON(json: any): EtbSnapshotDto {
    return EtbSnapshotDtoFromJSONTyped(json, false);
}

export function EtbSnapshotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EtbSnapshotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'snapshotAt': (new Date(json['snapshotAt'])),
        'eintraege': json['eintraege'],
    };
}

export function EtbSnapshotDtoToJSON(json: any): EtbSnapshotDto {
    return EtbSnapshotDtoToJSONTyped(json, false);
}

export function EtbSnapshotDtoToJSONTyped(value?: EtbSnapshotDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'snapshotAt': ((value['snapshotAt']).toISOString()),
        'eintraege': value['eintraege'],
    };
}

