/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.91-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FuehrungsrhythmusActivationGroupDto } from './FuehrungsrhythmusActivationGroupDto';
import {
    FuehrungsrhythmusActivationGroupDtoFromJSON,
    FuehrungsrhythmusActivationGroupDtoFromJSONTyped,
    FuehrungsrhythmusActivationGroupDtoToJSON,
    FuehrungsrhythmusActivationGroupDtoToJSONTyped,
} from './FuehrungsrhythmusActivationGroupDto';

/**
 * 
 * @export
 * @interface FuehrungsrhythmusStatistikDto
 */
export interface FuehrungsrhythmusStatistikDto {
    /**
     * Aktivierungen
     * @type {Array<FuehrungsrhythmusActivationGroupDto>}
     * @memberof FuehrungsrhythmusStatistikDto
     */
    activations: Array<FuehrungsrhythmusActivationGroupDto>;
    /**
     * Gesamtanzahl Aktivierungen
     * @type {number}
     * @memberof FuehrungsrhythmusStatistikDto
     */
    totalActivations: number;
    /**
     * Gesamtanzahl Zyklen ueber alle Aktivierungen
     * @type {number}
     * @memberof FuehrungsrhythmusStatistikDto
     */
    totalCycles: number;
    /**
     * Durchschnittliche Abschlussrate (0.0 - 1.0)
     * @type {number}
     * @memberof FuehrungsrhythmusStatistikDto
     */
    avgCompletionRate: number;
    /**
     * Gesamtanzahl Eskalationen
     * @type {number}
     * @memberof FuehrungsrhythmusStatistikDto
     */
    totalEscalations: number;
    /**
     * Gesamt-Snooze-Rate (0.0 - 1.0)
     * @type {number}
     * @memberof FuehrungsrhythmusStatistikDto
     */
    overallSnoozeRate: number;
}

/**
 * Check if a given object implements the FuehrungsrhythmusStatistikDto interface.
 */
export function instanceOfFuehrungsrhythmusStatistikDto(value: object): value is FuehrungsrhythmusStatistikDto {
    if (!('activations' in value) || value['activations'] === undefined) return false;
    if (!('totalActivations' in value) || value['totalActivations'] === undefined) return false;
    if (!('totalCycles' in value) || value['totalCycles'] === undefined) return false;
    if (!('avgCompletionRate' in value) || value['avgCompletionRate'] === undefined) return false;
    if (!('totalEscalations' in value) || value['totalEscalations'] === undefined) return false;
    if (!('overallSnoozeRate' in value) || value['overallSnoozeRate'] === undefined) return false;
    return true;
}

export function FuehrungsrhythmusStatistikDtoFromJSON(json: any): FuehrungsrhythmusStatistikDto {
    return FuehrungsrhythmusStatistikDtoFromJSONTyped(json, false);
}

export function FuehrungsrhythmusStatistikDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FuehrungsrhythmusStatistikDto {
    if (json == null) {
        return json;
    }
    return {
        
        'activations': ((json['activations'] as Array<any>).map(FuehrungsrhythmusActivationGroupDtoFromJSON)),
        'totalActivations': json['totalActivations'],
        'totalCycles': json['totalCycles'],
        'avgCompletionRate': json['avgCompletionRate'],
        'totalEscalations': json['totalEscalations'],
        'overallSnoozeRate': json['overallSnoozeRate'],
    };
}

export function FuehrungsrhythmusStatistikDtoToJSON(json: any): FuehrungsrhythmusStatistikDto {
    return FuehrungsrhythmusStatistikDtoToJSONTyped(json, false);
}

export function FuehrungsrhythmusStatistikDtoToJSONTyped(value?: FuehrungsrhythmusStatistikDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activations': ((value['activations'] as Array<any>).map(FuehrungsrhythmusActivationGroupDtoToJSON)),
        'totalActivations': value['totalActivations'],
        'totalCycles': value['totalCycles'],
        'avgCompletionRate': value['avgCompletionRate'],
        'totalEscalations': value['totalEscalations'],
        'overallSnoozeRate': value['overallSnoozeRate'],
    };
}

