/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.91-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GefahrenmatrixBewertungDto } from './GefahrenmatrixBewertungDto';
import {
    GefahrenmatrixBewertungDtoFromJSON,
    GefahrenmatrixBewertungDtoFromJSONTyped,
    GefahrenmatrixBewertungDtoToJSON,
    GefahrenmatrixBewertungDtoToJSONTyped,
} from './GefahrenmatrixBewertungDto';
import type { HealthControllerGetIntegrationHealth200ResponseMeta } from './HealthControllerGetIntegrationHealth200ResponseMeta';
import {
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSONTyped,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSONTyped,
} from './HealthControllerGetIntegrationHealth200ResponseMeta';

/**
 * 
 * @export
 * @interface GefahrenmatrixControllerUpdateBewertungVAlpha200Response
 */
export interface GefahrenmatrixControllerUpdateBewertungVAlpha200Response {
    /**
     * 
     * @type {GefahrenmatrixBewertungDto}
     * @memberof GefahrenmatrixControllerUpdateBewertungVAlpha200Response
     */
    data: GefahrenmatrixBewertungDto;
    /**
     * 
     * @type {HealthControllerGetIntegrationHealth200ResponseMeta}
     * @memberof GefahrenmatrixControllerUpdateBewertungVAlpha200Response
     */
    meta: HealthControllerGetIntegrationHealth200ResponseMeta;
}

/**
 * Check if a given object implements the GefahrenmatrixControllerUpdateBewertungVAlpha200Response interface.
 */
export function instanceOfGefahrenmatrixControllerUpdateBewertungVAlpha200Response(value: object): value is GefahrenmatrixControllerUpdateBewertungVAlpha200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GefahrenmatrixControllerUpdateBewertungVAlpha200ResponseFromJSON(json: any): GefahrenmatrixControllerUpdateBewertungVAlpha200Response {
    return GefahrenmatrixControllerUpdateBewertungVAlpha200ResponseFromJSONTyped(json, false);
}

export function GefahrenmatrixControllerUpdateBewertungVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GefahrenmatrixControllerUpdateBewertungVAlpha200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GefahrenmatrixBewertungDtoFromJSON(json['data']),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaFromJSON(json['meta']),
    };
}

export function GefahrenmatrixControllerUpdateBewertungVAlpha200ResponseToJSON(json: any): GefahrenmatrixControllerUpdateBewertungVAlpha200Response {
    return GefahrenmatrixControllerUpdateBewertungVAlpha200ResponseToJSONTyped(json, false);
}

export function GefahrenmatrixControllerUpdateBewertungVAlpha200ResponseToJSONTyped(value?: GefahrenmatrixControllerUpdateBewertungVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GefahrenmatrixBewertungDtoToJSON(value['data']),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaToJSON(value['meta']),
    };
}

