/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.89-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthControllerGetIntegrationHealth200ResponseMeta
 */
export interface HealthControllerGetIntegrationHealth200ResponseMeta {
    /**
     * 
     * @type {Date}
     * @memberof HealthControllerGetIntegrationHealth200ResponseMeta
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof HealthControllerGetIntegrationHealth200ResponseMeta
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof HealthControllerGetIntegrationHealth200ResponseMeta
     */
    requestId: string;
}

/**
 * Check if a given object implements the HealthControllerGetIntegrationHealth200ResponseMeta interface.
 */
export function instanceOfHealthControllerGetIntegrationHealth200ResponseMeta(value: object): value is HealthControllerGetIntegrationHealth200ResponseMeta {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function HealthControllerGetIntegrationHealth200ResponseMetaFromJSON(json: any): HealthControllerGetIntegrationHealth200ResponseMeta {
    return HealthControllerGetIntegrationHealth200ResponseMetaFromJSONTyped(json, false);
}

export function HealthControllerGetIntegrationHealth200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthControllerGetIntegrationHealth200ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': (new Date(json['timestamp'])),
        'version': json['version'],
        'requestId': json['requestId'],
    };
}

export function HealthControllerGetIntegrationHealth200ResponseMetaToJSON(json: any): HealthControllerGetIntegrationHealth200ResponseMeta {
    return HealthControllerGetIntegrationHealth200ResponseMetaToJSONTyped(json, false);
}

export function HealthControllerGetIntegrationHealth200ResponseMetaToJSONTyped(value?: HealthControllerGetIntegrationHealth200ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': ((value['timestamp']).toISOString()),
        'version': value['version'],
        'requestId': value['requestId'],
    };
}

