/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.36
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ImportPersonResultItemDto
 */
export interface ImportPersonResultItemDto {
  /**
   * HiOrg Username
   * @type {string}
   * @memberof ImportPersonResultItemDto
   */
  username: string;
  /**
   * Vorname
   * @type {string}
   * @memberof ImportPersonResultItemDto
   */
  vorname: string;
  /**
   * Nachname
   * @type {string}
   * @memberof ImportPersonResultItemDto
   */
  nachname: string;
  /**
   * Import-Status
   * @type {string}
   * @memberof ImportPersonResultItemDto
   */
  status: ImportPersonResultItemDtoStatusEnum;
  /**
   * Fehlergrund (nur bei status="failed")
   * @type {string}
   * @memberof ImportPersonResultItemDto
   */
  error?: string;
  /**
   * ID der erstellten/aktualisierten StammPerson
   * @type {string}
   * @memberof ImportPersonResultItemDto
   */
  stammPersonId?: string;
  /**
   * Anzahl erfolgreich gemappter Qualifikationen
   * @type {number}
   * @memberof ImportPersonResultItemDto
   */
  qualifikationenMapped: number;
  /**
   * Anzahl nicht gemappter Qualifikationen (Warnung)
   * @type {number}
   * @memberof ImportPersonResultItemDto
   */
  qualifikationenUnmapped: number;
}

/**
 * @export
 */
export const ImportPersonResultItemDtoStatusEnum = {
  Created: 'created',
  Updated: 'updated',
  Skipped: 'skipped',
  Failed: 'failed',
} as const;
export type ImportPersonResultItemDtoStatusEnum = (typeof ImportPersonResultItemDtoStatusEnum)[keyof typeof ImportPersonResultItemDtoStatusEnum];

/**
 * Check if a given object implements the ImportPersonResultItemDto interface.
 */
export function instanceOfImportPersonResultItemDto(value: object): value is ImportPersonResultItemDto {
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('vorname' in value) || value['vorname'] === undefined) return false;
  if (!('nachname' in value) || value['nachname'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  if (!('qualifikationenMapped' in value) || value['qualifikationenMapped'] === undefined) return false;
  if (!('qualifikationenUnmapped' in value) || value['qualifikationenUnmapped'] === undefined) return false;
  return true;
}

export function ImportPersonResultItemDtoFromJSON(json: any): ImportPersonResultItemDto {
  return ImportPersonResultItemDtoFromJSONTyped(json, false);
}

export function ImportPersonResultItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportPersonResultItemDto {
  if (json == null) {
    return json;
  }
  return {
    username: json['username'],
    vorname: json['vorname'],
    nachname: json['nachname'],
    status: json['status'],
    error: json['error'] == null ? undefined : json['error'],
    stammPersonId: json['stammPersonId'] == null ? undefined : json['stammPersonId'],
    qualifikationenMapped: json['qualifikationenMapped'],
    qualifikationenUnmapped: json['qualifikationenUnmapped'],
  };
}

export function ImportPersonResultItemDtoToJSON(json: any): ImportPersonResultItemDto {
  return ImportPersonResultItemDtoToJSONTyped(json, false);
}

export function ImportPersonResultItemDtoToJSONTyped(value?: ImportPersonResultItemDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    username: value['username'],
    vorname: value['vorname'],
    nachname: value['nachname'],
    status: value['status'],
    error: value['error'],
    stammPersonId: value['stammPersonId'],
    qualifikationenMapped: value['qualifikationenMapped'],
    qualifikationenUnmapped: value['qualifikationenUnmapped'],
  };
}
