/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.104-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteCodeCreatorDto
 */
export interface InviteCodeCreatorDto {
    /**
     * ID des Erstellers (Admin)
     * @type {string}
     * @memberof InviteCodeCreatorDto
     */
    id: string;
    /**
     * Anzeigename des Erstellers
     * @type {string}
     * @memberof InviteCodeCreatorDto
     */
    displayName: string;
}

/**
 * Check if a given object implements the InviteCodeCreatorDto interface.
 */
export function instanceOfInviteCodeCreatorDto(value: object): value is InviteCodeCreatorDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function InviteCodeCreatorDtoFromJSON(json: any): InviteCodeCreatorDto {
    return InviteCodeCreatorDtoFromJSONTyped(json, false);
}

export function InviteCodeCreatorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteCodeCreatorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['displayName'],
    };
}

export function InviteCodeCreatorDtoToJSON(json: any): InviteCodeCreatorDto {
    return InviteCodeCreatorDtoToJSONTyped(json, false);
}

export function InviteCodeCreatorDtoToJSONTyped(value?: InviteCodeCreatorDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
    };
}

