/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.83-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KategorieResponseDto
 */
export interface KategorieResponseDto {
    /**
     * Eindeutige ID der Kategorie
     * @type {string}
     * @memberof KategorieResponseDto
     */
    id: string;
    /**
     * Name der Kategorie
     * @type {string}
     * @memberof KategorieResponseDto
     */
    name: string;
    /**
     * Farbe der Kategorie als Hex-Code
     * @type {string}
     * @memberof KategorieResponseDto
     */
    farbe: string;
    /**
     * Einsatz ID
     * @type {string}
     * @memberof KategorieResponseDto
     */
    einsatzId: string;
    /**
     * Erstellt von (User ID)
     * @type {string}
     * @memberof KategorieResponseDto
     */
    erstelltVon: string;
    /**
     * Name des Erstellers
     * @type {string}
     * @memberof KategorieResponseDto
     */
    erstelltVonName?: string | null;
    /**
     * Erstellt am (ISO-8601)
     * @type {string}
     * @memberof KategorieResponseDto
     */
    createdAt: string;
    /**
     * Zuletzt aktualisiert (ISO-8601)
     * @type {string}
     * @memberof KategorieResponseDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the KategorieResponseDto interface.
 */
export function instanceOfKategorieResponseDto(value: object): value is KategorieResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('farbe' in value) || value['farbe'] === undefined) return false;
    if (!('einsatzId' in value) || value['einsatzId'] === undefined) return false;
    if (!('erstelltVon' in value) || value['erstelltVon'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function KategorieResponseDtoFromJSON(json: any): KategorieResponseDto {
    return KategorieResponseDtoFromJSONTyped(json, false);
}

export function KategorieResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KategorieResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'farbe': json['farbe'],
        'einsatzId': json['einsatzId'],
        'erstelltVon': json['erstelltVon'],
        'erstelltVonName': json['erstelltVonName'] == null ? undefined : json['erstelltVonName'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function KategorieResponseDtoToJSON(json: any): KategorieResponseDto {
    return KategorieResponseDtoToJSONTyped(json, false);
}

export function KategorieResponseDtoToJSONTyped(value?: KategorieResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'farbe': value['farbe'],
        'einsatzId': value['einsatzId'],
        'erstelltVon': value['erstelltVon'],
        'erstelltVonName': value['erstelltVonName'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

