/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.56-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBefehlEmpfaengerDto } from './CreateBefehlEmpfaengerDto';
import {
    CreateBefehlEmpfaengerDtoFromJSON,
    CreateBefehlEmpfaengerDtoFromJSONTyped,
    CreateBefehlEmpfaengerDtoToJSON,
    CreateBefehlEmpfaengerDtoToJSONTyped,
} from './CreateBefehlEmpfaengerDto';

/**
 * 
 * @export
 * @interface KorrigiereBefehlDto
 */
export interface KorrigiereBefehlDto {
    /**
     * Empfaenger mit Name und optionaler User-ID (min 1)
     * @type {Array<CreateBefehlEmpfaengerDto>}
     * @memberof KorrigiereBefehlDto
     */
    empfaenger: Array<CreateBefehlEmpfaengerDto>;
    /**
     * Befehlsgeber Display-Name
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    befehlsgeber: string;
    /**
     * Ersteller User-ID
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    erstellerId: string;
    /**
     * Auftrag (Pflicht, min 3 Zeichen)
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    auftrag: string;
    /**
     * Zeitvorgabe (optional)
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    zeitvorgabe?: string;
    /**
     * Ereignis (EAMZW)
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    ereignis?: string;
    /**
     * Mittel (EAMZW)
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    mittel?: string;
    /**
     * Ziel (EAMZW)
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    ziel?: string;
    /**
     * Weg (EAMZW)
     * @type {string}
     * @memberof KorrigiereBefehlDto
     */
    weg?: string;
}

/**
 * Check if a given object implements the KorrigiereBefehlDto interface.
 */
export function instanceOfKorrigiereBefehlDto(value: object): value is KorrigiereBefehlDto {
    if (!('empfaenger' in value) || value['empfaenger'] === undefined) return false;
    if (!('befehlsgeber' in value) || value['befehlsgeber'] === undefined) return false;
    if (!('erstellerId' in value) || value['erstellerId'] === undefined) return false;
    if (!('auftrag' in value) || value['auftrag'] === undefined) return false;
    return true;
}

export function KorrigiereBefehlDtoFromJSON(json: any): KorrigiereBefehlDto {
    return KorrigiereBefehlDtoFromJSONTyped(json, false);
}

export function KorrigiereBefehlDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KorrigiereBefehlDto {
    if (json == null) {
        return json;
    }
    return {
        
        'empfaenger': ((json['empfaenger'] as Array<any>).map(CreateBefehlEmpfaengerDtoFromJSON)),
        'befehlsgeber': json['befehlsgeber'],
        'erstellerId': json['erstellerId'],
        'auftrag': json['auftrag'],
        'zeitvorgabe': json['zeitvorgabe'] == null ? undefined : json['zeitvorgabe'],
        'ereignis': json['ereignis'] == null ? undefined : json['ereignis'],
        'mittel': json['mittel'] == null ? undefined : json['mittel'],
        'ziel': json['ziel'] == null ? undefined : json['ziel'],
        'weg': json['weg'] == null ? undefined : json['weg'],
    };
}

export function KorrigiereBefehlDtoToJSON(json: any): KorrigiereBefehlDto {
    return KorrigiereBefehlDtoToJSONTyped(json, false);
}

export function KorrigiereBefehlDtoToJSONTyped(value?: KorrigiereBefehlDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'empfaenger': ((value['empfaenger'] as Array<any>).map(CreateBefehlEmpfaengerDtoToJSON)),
        'befehlsgeber': value['befehlsgeber'],
        'erstellerId': value['erstellerId'],
        'auftrag': value['auftrag'],
        'zeitvorgabe': value['zeitvorgabe'],
        'ereignis': value['ereignis'],
        'mittel': value['mittel'],
        'ziel': value['ziel'],
        'weg': value['weg'],
    };
}

