/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface KraeftePoisPropertiesDto
 */
export interface KraeftePoisPropertiesDto {
  /**
   * Funkrufname des Fahrzeugs
   * @type {string}
   * @memberof KraeftePoisPropertiesDto
   */
  name: string;
  /**
   * Aktueller FMS-Status (0-9)
   * @type {number}
   * @memberof KraeftePoisPropertiesDto
   */
  status: number;
  /**
   * Lesbares Status-Label (customLabel oder standardLabel)
   * @type {string}
   * @memberof KraeftePoisPropertiesDto
   */
  statusLabel: string;
  /**
   * Farbe des Status als Hex-Code
   * @type {object}
   * @memberof KraeftePoisPropertiesDto
   */
  statusFarbe: object | null;
  /**
   * Taktische Staerke (aus Fahrzeugtyp Sollbesatzung)
   * @type {object}
   * @memberof KraeftePoisPropertiesDto
   */
  staerke: object | null;
  /**
   * Fahrzeugtyp-Code fuer Icon-Mapping
   * @type {string}
   * @memberof KraeftePoisPropertiesDto
   */
  fahrzeugtypCode: string;
  /**
   * Timestamp der letzten Positions-Aktualisierung (ISO 8601)
   * @type {string}
   * @memberof KraeftePoisPropertiesDto
   */
  positionTimestamp: string;
}

/**
 * Check if a given object implements the KraeftePoisPropertiesDto interface.
 */
export function instanceOfKraeftePoisPropertiesDto(value: object): value is KraeftePoisPropertiesDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  if (!('statusLabel' in value) || value['statusLabel'] === undefined) return false;
  if (!('statusFarbe' in value) || value['statusFarbe'] === undefined) return false;
  if (!('staerke' in value) || value['staerke'] === undefined) return false;
  if (!('fahrzeugtypCode' in value) || value['fahrzeugtypCode'] === undefined) return false;
  if (!('positionTimestamp' in value) || value['positionTimestamp'] === undefined) return false;
  return true;
}

export function KraeftePoisPropertiesDtoFromJSON(json: any): KraeftePoisPropertiesDto {
  return KraeftePoisPropertiesDtoFromJSONTyped(json, false);
}

export function KraeftePoisPropertiesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KraeftePoisPropertiesDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    status: json['status'],
    statusLabel: json['statusLabel'],
    statusFarbe: json['statusFarbe'],
    staerke: json['staerke'],
    fahrzeugtypCode: json['fahrzeugtypCode'],
    positionTimestamp: json['positionTimestamp'],
  };
}

export function KraeftePoisPropertiesDtoToJSON(json: any): KraeftePoisPropertiesDto {
  return KraeftePoisPropertiesDtoToJSONTyped(json, false);
}

export function KraeftePoisPropertiesDtoToJSONTyped(value?: KraeftePoisPropertiesDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    status: value['status'],
    statusLabel: value['statusLabel'],
    statusFarbe: value['statusFarbe'],
    staerke: value['staerke'],
    fahrzeugtypCode: value['fahrzeugtypCode'],
    positionTimestamp: value['positionTimestamp'],
  };
}
