/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.104-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListVorfaelleQueryDto
 */
export interface ListVorfaelleQueryDto {
    /**
     * Komma-separierte CUID2-Liste (max 50 Einträge), z. B. "id1,id2".
     * @type {Array<string>}
     * @memberof ListVorfaelleQueryDto
     */
    einheitIds?: Array<string>;
    /**
     * Untergrenze des Zeitraums (ISO 8601 mit Offset).
     * @type {string}
     * @memberof ListVorfaelleQueryDto
     */
    vorfallZeitVon?: string;
    /**
     * Obergrenze (exklusiv) des Zeitraums (ISO 8601 mit Offset).
     * @type {string}
     * @memberof ListVorfaelleQueryDto
     */
    vorfallZeitBis?: string;
    /**
     * Filter „nur Unfallkasse-relevant" — `true`/`false`/weglassen für „beide".
     * @type {boolean}
     * @memberof ListVorfaelleQueryDto
     */
    unfallkasseRelevant?: boolean;
}

/**
 * Check if a given object implements the ListVorfaelleQueryDto interface.
 */
export function instanceOfListVorfaelleQueryDto(value: object): value is ListVorfaelleQueryDto {
    return true;
}

export function ListVorfaelleQueryDtoFromJSON(json: any): ListVorfaelleQueryDto {
    return ListVorfaelleQueryDtoFromJSONTyped(json, false);
}

export function ListVorfaelleQueryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVorfaelleQueryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'einheitIds': json['einheitIds'] == null ? undefined : json['einheitIds'],
        'vorfallZeitVon': json['vorfallZeitVon'] == null ? undefined : json['vorfallZeitVon'],
        'vorfallZeitBis': json['vorfallZeitBis'] == null ? undefined : json['vorfallZeitBis'],
        'unfallkasseRelevant': json['unfallkasseRelevant'] == null ? undefined : json['unfallkasseRelevant'],
    };
}

export function ListVorfaelleQueryDtoToJSON(json: any): ListVorfaelleQueryDto {
    return ListVorfaelleQueryDtoToJSONTyped(json, false);
}

export function ListVorfaelleQueryDtoToJSONTyped(value?: ListVorfaelleQueryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'einheitIds': value['einheitIds'],
        'vorfallZeitVon': value['vorfallZeitVon'],
        'vorfallZeitBis': value['vorfallZeitBis'],
        'unfallkasseRelevant': value['unfallkasseRelevant'],
    };
}

