/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.34
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
  /**
   * JWT Access Token (24h gültig)
   * @type {string}
   * @memberof LoginResponseDto
   */
  token: string;
}

/**
 * Check if a given object implements the LoginResponseDto interface.
 */
export function instanceOfLoginResponseDto(value: object): value is LoginResponseDto {
  if (!('token' in value) || value['token'] === undefined) return false;
  return true;
}

export function LoginResponseDtoFromJSON(json: any): LoginResponseDto {
  return LoginResponseDtoFromJSONTyped(json, false);
}

export function LoginResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseDto {
  if (json == null) {
    return json;
  }
  return {
    token: json['token'],
  };
}

export function LoginResponseDtoToJSON(json: any): LoginResponseDto {
  return LoginResponseDtoToJSONTyped(json, false);
}

export function LoginResponseDtoToJSONTyped(value?: LoginResponseDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    token: value['token'],
  };
}
