/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.37
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PersonRegisteredResponseDto
 */
export interface PersonRegisteredResponseDto {
  /**
   * ID der neu erstellten EinsatzPerson
   * @type {string}
   * @memberof PersonRegisteredResponseDto
   */
  id: string;
}

/**
 * Check if a given object implements the PersonRegisteredResponseDto interface.
 */
export function instanceOfPersonRegisteredResponseDto(value: object): value is PersonRegisteredResponseDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function PersonRegisteredResponseDtoFromJSON(json: any): PersonRegisteredResponseDto {
  return PersonRegisteredResponseDtoFromJSONTyped(json, false);
}

export function PersonRegisteredResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonRegisteredResponseDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function PersonRegisteredResponseDtoToJSON(json: any): PersonRegisteredResponseDto {
  return PersonRegisteredResponseDtoToJSONTyped(json, false);
}

export function PersonRegisteredResponseDtoToJSONTyped(value?: PersonRegisteredResponseDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
