/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.99-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlzOrtDto
 */
export interface PlzOrtDto {
    /**
     * Name des Ortes
     * @type {string}
     * @memberof PlzOrtDto
     */
    ortsname: string;
    /**
     * Bundesland oder Region
     * @type {string}
     * @memberof PlzOrtDto
     */
    bundesland: string;
    /**
     * Kürzel des Bundeslandes
     * @type {string}
     * @memberof PlzOrtDto
     */
    bundeslandKuerzel: string;
    /**
     * Längengrad
     * @type {string}
     * @memberof PlzOrtDto
     */
    laengengrad: string;
    /**
     * Breitengrad
     * @type {string}
     * @memberof PlzOrtDto
     */
    breitengrad: string;
}

/**
 * Check if a given object implements the PlzOrtDto interface.
 */
export function instanceOfPlzOrtDto(value: object): value is PlzOrtDto {
    if (!('ortsname' in value) || value['ortsname'] === undefined) return false;
    if (!('bundesland' in value) || value['bundesland'] === undefined) return false;
    if (!('bundeslandKuerzel' in value) || value['bundeslandKuerzel'] === undefined) return false;
    if (!('laengengrad' in value) || value['laengengrad'] === undefined) return false;
    if (!('breitengrad' in value) || value['breitengrad'] === undefined) return false;
    return true;
}

export function PlzOrtDtoFromJSON(json: any): PlzOrtDto {
    return PlzOrtDtoFromJSONTyped(json, false);
}

export function PlzOrtDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlzOrtDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ortsname': json['ortsname'],
        'bundesland': json['bundesland'],
        'bundeslandKuerzel': json['bundeslandKuerzel'],
        'laengengrad': json['laengengrad'],
        'breitengrad': json['breitengrad'],
    };
}

export function PlzOrtDtoToJSON(json: any): PlzOrtDto {
    return PlzOrtDtoToJSONTyped(json, false);
}

export function PlzOrtDtoToJSONTyped(value?: PlzOrtDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ortsname': value['ortsname'],
        'bundesland': value['bundesland'],
        'bundeslandKuerzel': value['bundeslandKuerzel'],
        'laengengrad': value['laengengrad'],
        'breitengrad': value['breitengrad'],
    };
}

