/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.91-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QualifikationMappingItemDto } from './QualifikationMappingItemDto';
import {
    QualifikationMappingItemDtoFromJSON,
    QualifikationMappingItemDtoFromJSONTyped,
    QualifikationMappingItemDtoToJSON,
    QualifikationMappingItemDtoToJSONTyped,
} from './QualifikationMappingItemDto';

/**
 * 
 * @export
 * @interface QualifikationMappingsResponseDto
 */
export interface QualifikationMappingsResponseDto {
    /**
     * Liste der Mappings
     * @type {Array<QualifikationMappingItemDto>}
     * @memberof QualifikationMappingsResponseDto
     */
    mappings: Array<QualifikationMappingItemDto>;
    /**
     * Gesamtanzahl Mappings
     * @type {number}
     * @memberof QualifikationMappingsResponseDto
     */
    total: number;
    /**
     * Anzahl gemappter Einträge
     * @type {number}
     * @memberof QualifikationMappingsResponseDto
     */
    mapped: number;
    /**
     * Anzahl ungemappter Einträge
     * @type {number}
     * @memberof QualifikationMappingsResponseDto
     */
    unmapped: number;
}

/**
 * Check if a given object implements the QualifikationMappingsResponseDto interface.
 */
export function instanceOfQualifikationMappingsResponseDto(value: object): value is QualifikationMappingsResponseDto {
    if (!('mappings' in value) || value['mappings'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('mapped' in value) || value['mapped'] === undefined) return false;
    if (!('unmapped' in value) || value['unmapped'] === undefined) return false;
    return true;
}

export function QualifikationMappingsResponseDtoFromJSON(json: any): QualifikationMappingsResponseDto {
    return QualifikationMappingsResponseDtoFromJSONTyped(json, false);
}

export function QualifikationMappingsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualifikationMappingsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mappings': ((json['mappings'] as Array<any>).map(QualifikationMappingItemDtoFromJSON)),
        'total': json['total'],
        'mapped': json['mapped'],
        'unmapped': json['unmapped'],
    };
}

export function QualifikationMappingsResponseDtoToJSON(json: any): QualifikationMappingsResponseDto {
    return QualifikationMappingsResponseDtoToJSONTyped(json, false);
}

export function QualifikationMappingsResponseDtoToJSONTyped(value?: QualifikationMappingsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mappings': ((value['mappings'] as Array<any>).map(QualifikationMappingItemDtoToJSON)),
        'total': value['total'],
        'mapped': value['mapped'],
        'unmapped': value['unmapped'],
    };
}

