/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RefreshResponseDto
 */
export interface RefreshResponseDto {
  /**
   * Erfolgreich aktualisiert
   * @type {boolean}
   * @memberof RefreshResponseDto
   */
  success: boolean;
}

/**
 * Check if a given object implements the RefreshResponseDto interface.
 */
export function instanceOfRefreshResponseDto(value: object): value is RefreshResponseDto {
  if (!('success' in value) || value['success'] === undefined) return false;
  return true;
}

export function RefreshResponseDtoFromJSON(json: any): RefreshResponseDto {
  return RefreshResponseDtoFromJSONTyped(json, false);
}

export function RefreshResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RefreshResponseDto {
  if (json == null) {
    return json;
  }
  return {
    success: json['success'],
  };
}

export function RefreshResponseDtoToJSON(json: any): RefreshResponseDto {
  return RefreshResponseDtoToJSONTyped(json, false);
}

export function RefreshResponseDtoToJSONTyped(
  value?: RefreshResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value['success'],
  };
}
