/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.94-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrierePersonViaQrCodeDto
 */
export interface RegistrierePersonViaQrCodeDto {
    /**
     * Personalnummer aus QR-Code (DRK-Parameter "mnr")
     * @type {string}
     * @memberof RegistrierePersonViaQrCodeDto
     */
    personalnummer: string;
    /**
     * Vorname aus QR-Code (DRK-Parameter "vn")
     * @type {string}
     * @memberof RegistrierePersonViaQrCodeDto
     */
    vorname: string;
    /**
     * Nachname aus QR-Code (DRK-Parameter "nn")
     * @type {string}
     * @memberof RegistrierePersonViaQrCodeDto
     */
    nachname: string;
    /**
     * BOS-Funkkennung aus QR-Code (DRK-Parameter "fk", optional)
     * @type {string}
     * @memberof RegistrierePersonViaQrCodeDto
     */
    funkkennung?: string;
}

/**
 * Check if a given object implements the RegistrierePersonViaQrCodeDto interface.
 */
export function instanceOfRegistrierePersonViaQrCodeDto(value: object): value is RegistrierePersonViaQrCodeDto {
    if (!('personalnummer' in value) || value['personalnummer'] === undefined) return false;
    if (!('vorname' in value) || value['vorname'] === undefined) return false;
    if (!('nachname' in value) || value['nachname'] === undefined) return false;
    return true;
}

export function RegistrierePersonViaQrCodeDtoFromJSON(json: any): RegistrierePersonViaQrCodeDto {
    return RegistrierePersonViaQrCodeDtoFromJSONTyped(json, false);
}

export function RegistrierePersonViaQrCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrierePersonViaQrCodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'personalnummer': json['personalnummer'],
        'vorname': json['vorname'],
        'nachname': json['nachname'],
        'funkkennung': json['funkkennung'] == null ? undefined : json['funkkennung'],
    };
}

export function RegistrierePersonViaQrCodeDtoToJSON(json: any): RegistrierePersonViaQrCodeDto {
    return RegistrierePersonViaQrCodeDtoToJSONTyped(json, false);
}

export function RegistrierePersonViaQrCodeDtoToJSONTyped(value?: RegistrierePersonViaQrCodeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personalnummer': value['personalnummer'],
        'vorname': value['vorname'],
        'nachname': value['nachname'],
        'funkkennung': value['funkkennung'],
    };
}

