/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RuleStatisticsDto
 */
export interface RuleStatisticsDto {
  /**
   * Gesamtanzahl aller Regeln im System
   * @type {number}
   * @memberof RuleStatisticsDto
   */
  totalRules: number;
  /**
   * Verteilung der Regeln nach Status
   * @type {object}
   * @memberof RuleStatisticsDto
   */
  rulesByStatus: object;
  /**
   * Verteilung der Regeln nach Schweregrad
   * @type {object}
   * @memberof RuleStatisticsDto
   */
  rulesBySeverity: object;
  /**
   * Performance-Metriken der Rule Engine
   * @type {object}
   * @memberof RuleStatisticsDto
   */
  engineMetrics: object;
}

/**
 * Check if a given object implements the RuleStatisticsDto interface.
 */
export function instanceOfRuleStatisticsDto(value: object): value is RuleStatisticsDto {
  if (!('totalRules' in value) || value['totalRules'] === undefined) return false;
  if (!('rulesByStatus' in value) || value['rulesByStatus'] === undefined) return false;
  if (!('rulesBySeverity' in value) || value['rulesBySeverity'] === undefined) return false;
  if (!('engineMetrics' in value) || value['engineMetrics'] === undefined) return false;
  return true;
}

export function RuleStatisticsDtoFromJSON(json: any): RuleStatisticsDto {
  return RuleStatisticsDtoFromJSONTyped(json, false);
}

export function RuleStatisticsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RuleStatisticsDto {
  if (json == null) {
    return json;
  }
  return {
    totalRules: json['totalRules'],
    rulesByStatus: json['rulesByStatus'],
    rulesBySeverity: json['rulesBySeverity'],
    engineMetrics: json['engineMetrics'],
  };
}

export function RuleStatisticsDtoToJSON(json: any): RuleStatisticsDto {
  return RuleStatisticsDtoToJSONTyped(json, false);
}

export function RuleStatisticsDtoToJSONTyped(
  value?: RuleStatisticsDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    totalRules: value['totalRules'],
    rulesByStatus: value['rulesByStatus'],
    rulesBySeverity: value['rulesBySeverity'],
    engineMetrics: value['engineMetrics'],
  };
}
