/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.72-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveQualifikationMappingRequestDto
 */
export interface SaveQualifikationMappingRequestDto {
    /**
     * Mapping ID
     * @type {string}
     * @memberof SaveQualifikationMappingRequestDto
     */
    id: string;
    /**
     * Qualifikation-ID zum Mappen (null = Mapping entfernen)
     * @type {object}
     * @memberof SaveQualifikationMappingRequestDto
     */
    qualifikationId?: object;
}

/**
 * Check if a given object implements the SaveQualifikationMappingRequestDto interface.
 */
export function instanceOfSaveQualifikationMappingRequestDto(value: object): value is SaveQualifikationMappingRequestDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SaveQualifikationMappingRequestDtoFromJSON(json: any): SaveQualifikationMappingRequestDto {
    return SaveQualifikationMappingRequestDtoFromJSONTyped(json, false);
}

export function SaveQualifikationMappingRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveQualifikationMappingRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'qualifikationId': json['qualifikationId'] == null ? undefined : json['qualifikationId'],
    };
}

export function SaveQualifikationMappingRequestDtoToJSON(json: any): SaveQualifikationMappingRequestDto {
    return SaveQualifikationMappingRequestDtoToJSONTyped(json, false);
}

export function SaveQualifikationMappingRequestDtoToJSONTyped(value?: SaveQualifikationMappingRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'qualifikationId': value['qualifikationId'],
    };
}

