/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins
 */
export interface SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins {
  /**
   *
   * @type {number}
   * @memberof SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins
   */
  last24Hours?: number;
  /**
   *
   * @type {number}
   * @memberof SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins
   */
  last7Days?: number;
  /**
   *
   * @type {number}
   * @memberof SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins
   */
  trend?: number;
}

/**
 * Check if a given object implements the SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins interface.
 */
export function instanceOfSecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins(
  value: object,
): value is SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins {
  return true;
}

export function SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLoginsFromJSON(
  json: any,
): SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins {
  return SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLoginsFromJSONTyped(
    json,
    false,
  );
}

export function SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLoginsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins {
  if (json == null) {
    return json;
  }
  return {
    last24Hours: json['last24Hours'] == null ? undefined : json['last24Hours'],
    last7Days: json['last7Days'] == null ? undefined : json['last7Days'],
    trend: json['trend'] == null ? undefined : json['trend'],
  };
}

export function SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLoginsToJSON(
  json: any,
): SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins {
  return SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLoginsToJSONTyped(
    json,
    false,
  );
}

export function SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLoginsToJSONTyped(
  value?: SecurityControllerGetDashboardMetricsV1200ResponseSummaryFailedLogins | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    last24Hours: value['last24Hours'],
    last7Days: value['last7Days'],
    trend: value['trend'],
  };
}
