/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.104-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SicherheitsregelQuittungDto
 */
export interface SicherheitsregelQuittungDto {
    /**
     * cuid2 der Einheit, die quittiert hat.
     * @type {string}
     * @memberof SicherheitsregelQuittungDto
     */
    einheitId: string;
    /**
     * Anzeigename der Einheit zum Quittungs-Zeitpunkt.
     * @type {string}
     * @memberof SicherheitsregelQuittungDto
     */
    einheitName: string;
    /**
     * ISO-DateTime, wann die Einheit quittiert hat.
     * @type {string}
     * @memberof SicherheitsregelQuittungDto
     */
    quittiertAm: string;
    /**
     * cuid2 des Users, der für die Einheit quittiert hat.
     * @type {string}
     * @memberof SicherheitsregelQuittungDto
     */
    quittiertVonUserId: string;
    /**
     * Anzeigename des quittierenden Users (optional).
     * @type {string}
     * @memberof SicherheitsregelQuittungDto
     */
    quittiertVonUserName?: string;
}

/**
 * Check if a given object implements the SicherheitsregelQuittungDto interface.
 */
export function instanceOfSicherheitsregelQuittungDto(value: object): value is SicherheitsregelQuittungDto {
    if (!('einheitId' in value) || value['einheitId'] === undefined) return false;
    if (!('einheitName' in value) || value['einheitName'] === undefined) return false;
    if (!('quittiertAm' in value) || value['quittiertAm'] === undefined) return false;
    if (!('quittiertVonUserId' in value) || value['quittiertVonUserId'] === undefined) return false;
    return true;
}

export function SicherheitsregelQuittungDtoFromJSON(json: any): SicherheitsregelQuittungDto {
    return SicherheitsregelQuittungDtoFromJSONTyped(json, false);
}

export function SicherheitsregelQuittungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SicherheitsregelQuittungDto {
    if (json == null) {
        return json;
    }
    return {
        
        'einheitId': json['einheitId'],
        'einheitName': json['einheitName'],
        'quittiertAm': json['quittiertAm'],
        'quittiertVonUserId': json['quittiertVonUserId'],
        'quittiertVonUserName': json['quittiertVonUserName'] == null ? undefined : json['quittiertVonUserName'],
    };
}

export function SicherheitsregelQuittungDtoToJSON(json: any): SicherheitsregelQuittungDto {
    return SicherheitsregelQuittungDtoToJSONTyped(json, false);
}

export function SicherheitsregelQuittungDtoToJSONTyped(value?: SicherheitsregelQuittungDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'einheitId': value['einheitId'],
        'einheitName': value['einheitName'],
        'quittiertAm': value['quittiertAm'],
        'quittiertVonUserId': value['quittiertVonUserId'],
        'quittiertVonUserName': value['quittiertVonUserName'],
    };
}

