/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PersonalFreitextEntryDto } from './PersonalFreitextEntryDto';
import {
    instanceOfPersonalFreitextEntryDto,
    PersonalFreitextEntryDtoFromJSON,
    PersonalFreitextEntryDtoFromJSONTyped,
    PersonalFreitextEntryDtoToJSON,
} from './PersonalFreitextEntryDto';
import type { PersonalUserEntryDto } from './PersonalUserEntryDto';
import {
    instanceOfPersonalUserEntryDto,
    PersonalUserEntryDtoFromJSON,
    PersonalUserEntryDtoFromJSONTyped,
    PersonalUserEntryDtoToJSON,
} from './PersonalUserEntryDto';

/**
 * @type SicherungspostenDtoPersonalInner
 * 
 * @export
 */
export type SicherungspostenDtoPersonalInner = PersonalFreitextEntryDto | PersonalUserEntryDto;

export function SicherungspostenDtoPersonalInnerFromJSON(json: any): SicherungspostenDtoPersonalInner {
    return SicherungspostenDtoPersonalInnerFromJSONTyped(json, false);
}

export function SicherungspostenDtoPersonalInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SicherungspostenDtoPersonalInner {
    if (json == null) {
        return json;
    }
    if (instanceOfPersonalFreitextEntryDto(json)) {
        return PersonalFreitextEntryDtoFromJSONTyped(json, true);
    }
    if (instanceOfPersonalUserEntryDto(json)) {
        return PersonalUserEntryDtoFromJSONTyped(json, true);
    }

    return {} as any;
}

export function SicherungspostenDtoPersonalInnerToJSON(json: any): any {
    return SicherungspostenDtoPersonalInnerToJSONTyped(json, false);
}

export function SicherungspostenDtoPersonalInnerToJSONTyped(value?: SicherungspostenDtoPersonalInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfPersonalFreitextEntryDto(value)) {
        return PersonalFreitextEntryDtoToJSON(value as PersonalFreitextEntryDto);
    }
    if (instanceOfPersonalUserEntryDto(value)) {
        return PersonalUserEntryDtoToJSON(value as PersonalUserEntryDto);
    }

    return {};
}

