/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.36
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StammPersonDto } from './StammPersonDto';
import { StammPersonDtoFromJSON, StammPersonDtoFromJSONTyped, StammPersonDtoToJSON, StammPersonDtoToJSONTyped } from './StammPersonDto';
import type { EinsatzControllerFindAllVAlpha200ResponsePagination } from './EinsatzControllerFindAllVAlpha200ResponsePagination';
import {
  EinsatzControllerFindAllVAlpha200ResponsePaginationFromJSON,
  EinsatzControllerFindAllVAlpha200ResponsePaginationFromJSONTyped,
  EinsatzControllerFindAllVAlpha200ResponsePaginationToJSON,
  EinsatzControllerFindAllVAlpha200ResponsePaginationToJSONTyped,
} from './EinsatzControllerFindAllVAlpha200ResponsePagination';
import type { UserControllerFindOneVAlpha200ResponseMeta } from './UserControllerFindOneVAlpha200ResponseMeta';
import {
  UserControllerFindOneVAlpha200ResponseMetaFromJSON,
  UserControllerFindOneVAlpha200ResponseMetaFromJSONTyped,
  UserControllerFindOneVAlpha200ResponseMetaToJSON,
  UserControllerFindOneVAlpha200ResponseMetaToJSONTyped,
} from './UserControllerFindOneVAlpha200ResponseMeta';

/**
 *
 * @export
 * @interface StammPersonenControllerFindAllVAlpha200Response
 */
export interface StammPersonenControllerFindAllVAlpha200Response {
  /**
   *
   * @type {Array<StammPersonDto>}
   * @memberof StammPersonenControllerFindAllVAlpha200Response
   */
  data: Array<StammPersonDto>;
  /**
   *
   * @type {UserControllerFindOneVAlpha200ResponseMeta}
   * @memberof StammPersonenControllerFindAllVAlpha200Response
   */
  meta: UserControllerFindOneVAlpha200ResponseMeta;
  /**
   *
   * @type {EinsatzControllerFindAllVAlpha200ResponsePagination}
   * @memberof StammPersonenControllerFindAllVAlpha200Response
   */
  pagination?: EinsatzControllerFindAllVAlpha200ResponsePagination;
}

/**
 * Check if a given object implements the StammPersonenControllerFindAllVAlpha200Response interface.
 */
export function instanceOfStammPersonenControllerFindAllVAlpha200Response(value: object): value is StammPersonenControllerFindAllVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function StammPersonenControllerFindAllVAlpha200ResponseFromJSON(json: any): StammPersonenControllerFindAllVAlpha200Response {
  return StammPersonenControllerFindAllVAlpha200ResponseFromJSONTyped(json, false);
}

export function StammPersonenControllerFindAllVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StammPersonenControllerFindAllVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(StammPersonDtoFromJSON),
    meta: UserControllerFindOneVAlpha200ResponseMetaFromJSON(json['meta']),
    pagination: json['pagination'] == null ? undefined : EinsatzControllerFindAllVAlpha200ResponsePaginationFromJSON(json['pagination']),
  };
}

export function StammPersonenControllerFindAllVAlpha200ResponseToJSON(json: any): StammPersonenControllerFindAllVAlpha200Response {
  return StammPersonenControllerFindAllVAlpha200ResponseToJSONTyped(json, false);
}

export function StammPersonenControllerFindAllVAlpha200ResponseToJSONTyped(value?: StammPersonenControllerFindAllVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(StammPersonDtoToJSON),
    meta: UserControllerFindOneVAlpha200ResponseMetaToJSON(value['meta']),
    pagination: EinsatzControllerFindAllVAlpha200ResponsePaginationToJSON(value['pagination']),
  };
}
