/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TaktischeStaerkeDto
 */
export interface TaktischeStaerkeDto {
  /**
   * Anzahl Führungskräfte (Leiter, LNA, OrgL, Zugführer, Ärzte)
   * @type {number}
   * @memberof TaktischeStaerkeDto
   */
  fuehrung: number;
  /**
   * Anzahl Unterführer (Gruppenführer, Truppführer)
   * @type {number}
   * @memberof TaktischeStaerkeDto
   */
  unterfuehrung: number;
  /**
   * Anzahl Mannschaftsmitglieder (alle anderen Helfer)
   * @type {number}
   * @memberof TaktischeStaerkeDto
   */
  mannschaft: number;
  /**
   * Gesamtanzahl aller eingesetzten Kräfte
   * @type {number}
   * @memberof TaktischeStaerkeDto
   */
  gesamt: number;
}

/**
 * Check if a given object implements the TaktischeStaerkeDto interface.
 */
export function instanceOfTaktischeStaerkeDto(value: object): value is TaktischeStaerkeDto {
  if (!('fuehrung' in value) || value['fuehrung'] === undefined) return false;
  if (!('unterfuehrung' in value) || value['unterfuehrung'] === undefined) return false;
  if (!('mannschaft' in value) || value['mannschaft'] === undefined) return false;
  if (!('gesamt' in value) || value['gesamt'] === undefined) return false;
  return true;
}

export function TaktischeStaerkeDtoFromJSON(json: any): TaktischeStaerkeDto {
  return TaktischeStaerkeDtoFromJSONTyped(json, false);
}

export function TaktischeStaerkeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaktischeStaerkeDto {
  if (json == null) {
    return json;
  }
  return {
    fuehrung: json['fuehrung'],
    unterfuehrung: json['unterfuehrung'],
    mannschaft: json['mannschaft'],
    gesamt: json['gesamt'],
  };
}

export function TaktischeStaerkeDtoToJSON(json: any): TaktischeStaerkeDto {
  return TaktischeStaerkeDtoToJSONTyped(json, false);
}

export function TaktischeStaerkeDtoToJSONTyped(value?: TaktischeStaerkeDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    fuehrung: value['fuehrung'],
    unterfuehrung: value['unterfuehrung'],
    mannschaft: value['mannschaft'],
    gesamt: value['gesamt'],
  };
}
