/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.76-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextbausteinDto
 */
export interface TextbausteinDto {
    /**
     * Eindeutige ID des Textbausteins
     * @type {string}
     * @memberof TextbausteinDto
     */
    id: string;
    /**
     * Kategorie des Textbausteins
     * @type {string}
     * @memberof TextbausteinDto
     */
    kategorie: TextbausteinDtoKategorieEnum;
    /**
     * Kurzbeschreibung des Textbausteins
     * @type {string}
     * @memberof TextbausteinDto
     */
    kurztext: string;
    /**
     * Vollstaendiger Text des Bausteins
     * @type {string}
     * @memberof TextbausteinDto
     */
    volltext: string;
    /**
     * Aktiv-Status des Textbausteins
     * @type {boolean}
     * @memberof TextbausteinDto
     */
    isActive: boolean;
    /**
     * Sortierreihenfolge
     * @type {number}
     * @memberof TextbausteinDto
     */
    sortOrder: number;
    /**
     * Anzahl der Verwendungen
     * @type {number}
     * @memberof TextbausteinDto
     */
    verwendungen: number;
    /**
     * Datum der letzten Nutzung
     * @type {Date}
     * @memberof TextbausteinDto
     */
    letztGenutzt?: Date | null;
}


/**
 * @export
 */
export const TextbausteinDtoKategorieEnum = {
    Alarmierung: 'ALARMIERUNG',
    Ankunft: 'ANKUNFT',
    Befehl: 'BEFEHL',
    Erkundung: 'ERKUNDUNG',
    Lage: 'LAGE',
    Massnahme: 'MASSNAHME',
    Personal: 'PERSONAL',
    Fahrzeug: 'FAHRZEUG',
    Material: 'MATERIAL',
    Kommunikation: 'KOMMUNIKATION',
    Wetter: 'WETTER',
    Dokumentation: 'DOKUMENTATION',
    Sonstiges: 'SONSTIGES',
    System: 'SYSTEM'
} as const;
export type TextbausteinDtoKategorieEnum = typeof TextbausteinDtoKategorieEnum[keyof typeof TextbausteinDtoKategorieEnum];


/**
 * Check if a given object implements the TextbausteinDto interface.
 */
export function instanceOfTextbausteinDto(value: object): value is TextbausteinDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kategorie' in value) || value['kategorie'] === undefined) return false;
    if (!('kurztext' in value) || value['kurztext'] === undefined) return false;
    if (!('volltext' in value) || value['volltext'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('verwendungen' in value) || value['verwendungen'] === undefined) return false;
    return true;
}

export function TextbausteinDtoFromJSON(json: any): TextbausteinDto {
    return TextbausteinDtoFromJSONTyped(json, false);
}

export function TextbausteinDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextbausteinDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kategorie': json['kategorie'],
        'kurztext': json['kurztext'],
        'volltext': json['volltext'],
        'isActive': json['isActive'],
        'sortOrder': json['sortOrder'],
        'verwendungen': json['verwendungen'],
        'letztGenutzt': json['letztGenutzt'] == null ? undefined : (new Date(json['letztGenutzt'])),
    };
}

export function TextbausteinDtoToJSON(json: any): TextbausteinDto {
    return TextbausteinDtoToJSONTyped(json, false);
}

export function TextbausteinDtoToJSONTyped(value?: TextbausteinDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kategorie': value['kategorie'],
        'kurztext': value['kurztext'],
        'volltext': value['volltext'],
        'isActive': value['isActive'],
        'sortOrder': value['sortOrder'],
        'verwendungen': value['verwendungen'],
        'letztGenutzt': value['letztGenutzt'] == null ? undefined : ((value['letztGenutzt'] as any).toISOString()),
    };
}

