/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.99-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBefehlsgeberVorschlagDto
 */
export interface UpdateBefehlsgeberVorschlagDto {
    /**
     * Kuerzel (z.B. EL, ZF)
     * @type {string}
     * @memberof UpdateBefehlsgeberVorschlagDto
     */
    kuerzel?: string;
    /**
     * Anzeige-Label
     * @type {string}
     * @memberof UpdateBefehlsgeberVorschlagDto
     */
    label?: string;
    /**
     * Sortierreihenfolge
     * @type {number}
     * @memberof UpdateBefehlsgeberVorschlagDto
     */
    sortOrder?: number;
    /**
     * Ob der Vorschlag aktiv ist
     * @type {boolean}
     * @memberof UpdateBefehlsgeberVorschlagDto
     */
    istAktiv?: boolean;
}

/**
 * Check if a given object implements the UpdateBefehlsgeberVorschlagDto interface.
 */
export function instanceOfUpdateBefehlsgeberVorschlagDto(value: object): value is UpdateBefehlsgeberVorschlagDto {
    return true;
}

export function UpdateBefehlsgeberVorschlagDtoFromJSON(json: any): UpdateBefehlsgeberVorschlagDto {
    return UpdateBefehlsgeberVorschlagDtoFromJSONTyped(json, false);
}

export function UpdateBefehlsgeberVorschlagDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBefehlsgeberVorschlagDto {
    if (json == null) {
        return json;
    }
    return {
        
        'kuerzel': json['kuerzel'] == null ? undefined : json['kuerzel'],
        'label': json['label'] == null ? undefined : json['label'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'istAktiv': json['istAktiv'] == null ? undefined : json['istAktiv'],
    };
}

export function UpdateBefehlsgeberVorschlagDtoToJSON(json: any): UpdateBefehlsgeberVorschlagDto {
    return UpdateBefehlsgeberVorschlagDtoToJSONTyped(json, false);
}

export function UpdateBefehlsgeberVorschlagDtoToJSONTyped(value?: UpdateBefehlsgeberVorschlagDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kuerzel': value['kuerzel'],
        'label': value['label'],
        'sortOrder': value['sortOrder'],
        'istAktiv': value['istAktiv'],
    };
}

