/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.94-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZeichenDefinitionRequestDto } from './ZeichenDefinitionRequestDto';
import {
    ZeichenDefinitionRequestDtoFromJSON,
    ZeichenDefinitionRequestDtoFromJSONTyped,
    ZeichenDefinitionRequestDtoToJSON,
    ZeichenDefinitionRequestDtoToJSONTyped,
} from './ZeichenDefinitionRequestDto';

/**
 * 
 * @export
 * @interface UpdateTaktischesZeichenDto
 */
export interface UpdateTaktischesZeichenDto {
    /**
     * Neue Zeichendefinition
     * @type {ZeichenDefinitionRequestDto}
     * @memberof UpdateTaktischesZeichenDto
     */
    zeichenDefinition?: ZeichenDefinitionRequestDto;
    /**
     * Neue Beschriftung (null zum Löschen)
     * @type {string}
     * @memberof UpdateTaktischesZeichenDto
     */
    label?: string;
    /**
     * Neue Notiz (null zum Löschen)
     * @type {string}
     * @memberof UpdateTaktischesZeichenDto
     */
    notiz?: string;
}

/**
 * Check if a given object implements the UpdateTaktischesZeichenDto interface.
 */
export function instanceOfUpdateTaktischesZeichenDto(value: object): value is UpdateTaktischesZeichenDto {
    return true;
}

export function UpdateTaktischesZeichenDtoFromJSON(json: any): UpdateTaktischesZeichenDto {
    return UpdateTaktischesZeichenDtoFromJSONTyped(json, false);
}

export function UpdateTaktischesZeichenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaktischesZeichenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'zeichenDefinition': json['zeichenDefinition'] == null ? undefined : ZeichenDefinitionRequestDtoFromJSON(json['zeichenDefinition']),
        'label': json['label'] == null ? undefined : json['label'],
        'notiz': json['notiz'] == null ? undefined : json['notiz'],
    };
}

export function UpdateTaktischesZeichenDtoToJSON(json: any): UpdateTaktischesZeichenDto {
    return UpdateTaktischesZeichenDtoToJSONTyped(json, false);
}

export function UpdateTaktischesZeichenDtoToJSONTyped(value?: UpdateTaktischesZeichenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'zeichenDefinition': ZeichenDefinitionRequestDtoToJSON(value['zeichenDefinition']),
        'label': value['label'],
        'notiz': value['notiz'],
    };
}

