/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.74-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateQualifikationDto
 */
export interface UpdateQualifikationDto {
    /**
     * Name der Qualifikation
     * @type {string}
     * @memberof UpdateQualifikationDto
     */
    name?: string;
    /**
     * Eindeutige Abkürzung
     * @type {string}
     * @memberof UpdateQualifikationDto
     */
    abkuerzung?: string;
    /**
     * Kategorie der Qualifikation
     * @type {string}
     * @memberof UpdateQualifikationDto
     */
    kategorie?: UpdateQualifikationDtoKategorieEnum;
    /**
     * Optionale Beschreibung
     * @type {string}
     * @memberof UpdateQualifikationDto
     */
    beschreibung?: string;
    /**
     * Aktivierungsstatus
     * @type {boolean}
     * @memberof UpdateQualifikationDto
     */
    istAktiv?: boolean;
}


/**
 * @export
 */
export const UpdateQualifikationDtoKategorieEnum = {
    Fuehrung: 'FUEHRUNG',
    Sanitaet: 'SANITAET',
    Betreuung: 'BETREUUNG',
    Technik: 'TECHNIK',
    Sonstiges: 'SONSTIGES'
} as const;
export type UpdateQualifikationDtoKategorieEnum = typeof UpdateQualifikationDtoKategorieEnum[keyof typeof UpdateQualifikationDtoKategorieEnum];


/**
 * Check if a given object implements the UpdateQualifikationDto interface.
 */
export function instanceOfUpdateQualifikationDto(value: object): value is UpdateQualifikationDto {
    return true;
}

export function UpdateQualifikationDtoFromJSON(json: any): UpdateQualifikationDto {
    return UpdateQualifikationDtoFromJSONTyped(json, false);
}

export function UpdateQualifikationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateQualifikationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'abkuerzung': json['abkuerzung'] == null ? undefined : json['abkuerzung'],
        'kategorie': json['kategorie'] == null ? undefined : json['kategorie'],
        'beschreibung': json['beschreibung'] == null ? undefined : json['beschreibung'],
        'istAktiv': json['istAktiv'] == null ? undefined : json['istAktiv'],
    };
}

export function UpdateQualifikationDtoToJSON(json: any): UpdateQualifikationDto {
    return UpdateQualifikationDtoToJSONTyped(json, false);
}

export function UpdateQualifikationDtoToJSONTyped(value?: UpdateQualifikationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'abkuerzung': value['abkuerzung'],
        'kategorie': value['kategorie'],
        'beschreibung': value['beschreibung'],
        'istAktiv': value['istAktiv'],
    };
}

