/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.31
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import { UserResponseFromJSON, UserResponseFromJSONTyped, UserResponseToJSON, UserResponseToJSONTyped } from './UserResponse';
import type { UserControllerFindOneVAlpha200ResponseMeta } from './UserControllerFindOneVAlpha200ResponseMeta';
import {
  UserControllerFindOneVAlpha200ResponseMetaFromJSON,
  UserControllerFindOneVAlpha200ResponseMetaFromJSONTyped,
  UserControllerFindOneVAlpha200ResponseMetaToJSON,
  UserControllerFindOneVAlpha200ResponseMetaToJSONTyped,
} from './UserControllerFindOneVAlpha200ResponseMeta';
import type { UserControllerFindOneVAlpha200ResponsePagination } from './UserControllerFindOneVAlpha200ResponsePagination';
import {
  UserControllerFindOneVAlpha200ResponsePaginationFromJSON,
  UserControllerFindOneVAlpha200ResponsePaginationFromJSONTyped,
  UserControllerFindOneVAlpha200ResponsePaginationToJSON,
  UserControllerFindOneVAlpha200ResponsePaginationToJSONTyped,
} from './UserControllerFindOneVAlpha200ResponsePagination';

/**
 *
 * @export
 * @interface UserControllerFindOneVAlpha200Response
 */
export interface UserControllerFindOneVAlpha200Response {
  /**
   *
   * @type {Array<UserResponse>}
   * @memberof UserControllerFindOneVAlpha200Response
   */
  data: Array<UserResponse>;
  /**
   *
   * @type {UserControllerFindOneVAlpha200ResponseMeta}
   * @memberof UserControllerFindOneVAlpha200Response
   */
  meta: UserControllerFindOneVAlpha200ResponseMeta;
  /**
   *
   * @type {UserControllerFindOneVAlpha200ResponsePagination}
   * @memberof UserControllerFindOneVAlpha200Response
   */
  pagination?: UserControllerFindOneVAlpha200ResponsePagination;
}

/**
 * Check if a given object implements the UserControllerFindOneVAlpha200Response interface.
 */
export function instanceOfUserControllerFindOneVAlpha200Response(value: object): value is UserControllerFindOneVAlpha200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function UserControllerFindOneVAlpha200ResponseFromJSON(json: any): UserControllerFindOneVAlpha200Response {
  return UserControllerFindOneVAlpha200ResponseFromJSONTyped(json, false);
}

export function UserControllerFindOneVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserControllerFindOneVAlpha200Response {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(UserResponseFromJSON),
    meta: UserControllerFindOneVAlpha200ResponseMetaFromJSON(json['meta']),
    pagination: json['pagination'] == null ? undefined : UserControllerFindOneVAlpha200ResponsePaginationFromJSON(json['pagination']),
  };
}

export function UserControllerFindOneVAlpha200ResponseToJSON(json: any): UserControllerFindOneVAlpha200Response {
  return UserControllerFindOneVAlpha200ResponseToJSONTyped(json, false);
}

export function UserControllerFindOneVAlpha200ResponseToJSONTyped(value?: UserControllerFindOneVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(UserResponseToJSON),
    meta: UserControllerFindOneVAlpha200ResponseMetaToJSON(value['meta']),
    pagination: UserControllerFindOneVAlpha200ResponsePaginationToJSON(value['pagination']),
  };
}
