/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserBasicDto } from './UserBasicDto';
import {
    UserBasicDtoFromJSON,
    UserBasicDtoFromJSONTyped,
    UserBasicDtoToJSON,
    UserBasicDtoToJSONTyped,
} from './UserBasicDto';
import type { HealthControllerGetIntegrationHealth200ResponseMeta } from './HealthControllerGetIntegrationHealth200ResponseMeta';
import {
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaFromJSONTyped,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSON,
    HealthControllerGetIntegrationHealth200ResponseMetaToJSONTyped,
} from './HealthControllerGetIntegrationHealth200ResponseMeta';
import type { UserControllerFindAllBasicVAlpha200ResponsePagination } from './UserControllerFindAllBasicVAlpha200ResponsePagination';
import {
    UserControllerFindAllBasicVAlpha200ResponsePaginationFromJSON,
    UserControllerFindAllBasicVAlpha200ResponsePaginationFromJSONTyped,
    UserControllerFindAllBasicVAlpha200ResponsePaginationToJSON,
    UserControllerFindAllBasicVAlpha200ResponsePaginationToJSONTyped,
} from './UserControllerFindAllBasicVAlpha200ResponsePagination';

/**
 * 
 * @export
 * @interface UserControllerFindAllBasicVAlpha200Response
 */
export interface UserControllerFindAllBasicVAlpha200Response {
    /**
     * 
     * @type {Array<UserBasicDto>}
     * @memberof UserControllerFindAllBasicVAlpha200Response
     */
    data: Array<UserBasicDto>;
    /**
     * 
     * @type {HealthControllerGetIntegrationHealth200ResponseMeta}
     * @memberof UserControllerFindAllBasicVAlpha200Response
     */
    meta: HealthControllerGetIntegrationHealth200ResponseMeta;
    /**
     * 
     * @type {UserControllerFindAllBasicVAlpha200ResponsePagination}
     * @memberof UserControllerFindAllBasicVAlpha200Response
     */
    pagination?: UserControllerFindAllBasicVAlpha200ResponsePagination;
}

/**
 * Check if a given object implements the UserControllerFindAllBasicVAlpha200Response interface.
 */
export function instanceOfUserControllerFindAllBasicVAlpha200Response(value: object): value is UserControllerFindAllBasicVAlpha200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function UserControllerFindAllBasicVAlpha200ResponseFromJSON(json: any): UserControllerFindAllBasicVAlpha200Response {
    return UserControllerFindAllBasicVAlpha200ResponseFromJSONTyped(json, false);
}

export function UserControllerFindAllBasicVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserControllerFindAllBasicVAlpha200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserBasicDtoFromJSON)),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaFromJSON(json['meta']),
        'pagination': json['pagination'] == null ? undefined : UserControllerFindAllBasicVAlpha200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function UserControllerFindAllBasicVAlpha200ResponseToJSON(json: any): UserControllerFindAllBasicVAlpha200Response {
    return UserControllerFindAllBasicVAlpha200ResponseToJSONTyped(json, false);
}

export function UserControllerFindAllBasicVAlpha200ResponseToJSONTyped(value?: UserControllerFindAllBasicVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserBasicDtoToJSON)),
        'meta': HealthControllerGetIntegrationHealth200ResponseMetaToJSON(value['meta']),
        'pagination': UserControllerFindAllBasicVAlpha200ResponsePaginationToJSON(value['pagination']),
    };
}

