/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthControllerUnifiedAuth200ResponseMeta } from './AuthControllerUnifiedAuth200ResponseMeta';
import {
    AuthControllerUnifiedAuth200ResponseMetaFromJSON,
    AuthControllerUnifiedAuth200ResponseMetaFromJSONTyped,
    AuthControllerUnifiedAuth200ResponseMetaToJSON,
    AuthControllerUnifiedAuth200ResponseMetaToJSONTyped,
} from './AuthControllerUnifiedAuth200ResponseMeta';
import type { DeleteManagedUserResponse } from './DeleteManagedUserResponse';
import {
    DeleteManagedUserResponseFromJSON,
    DeleteManagedUserResponseFromJSONTyped,
    DeleteManagedUserResponseToJSON,
    DeleteManagedUserResponseToJSONTyped,
} from './DeleteManagedUserResponse';

/**
 * 
 * @export
 * @interface UserManagementControllerRemoveVAlpha200Response
 */
export interface UserManagementControllerRemoveVAlpha200Response {
    /**
     * 
     * @type {DeleteManagedUserResponse}
     * @memberof UserManagementControllerRemoveVAlpha200Response
     */
    data: DeleteManagedUserResponse;
    /**
     * 
     * @type {AuthControllerUnifiedAuth200ResponseMeta}
     * @memberof UserManagementControllerRemoveVAlpha200Response
     */
    meta: AuthControllerUnifiedAuth200ResponseMeta;
}

/**
 * Check if a given object implements the UserManagementControllerRemoveVAlpha200Response interface.
 */
export function instanceOfUserManagementControllerRemoveVAlpha200Response(value: object): value is UserManagementControllerRemoveVAlpha200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function UserManagementControllerRemoveVAlpha200ResponseFromJSON(json: any): UserManagementControllerRemoveVAlpha200Response {
    return UserManagementControllerRemoveVAlpha200ResponseFromJSONTyped(json, false);
}

export function UserManagementControllerRemoveVAlpha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserManagementControllerRemoveVAlpha200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': DeleteManagedUserResponseFromJSON(json['data']),
        'meta': AuthControllerUnifiedAuth200ResponseMetaFromJSON(json['meta']),
    };
}

export function UserManagementControllerRemoveVAlpha200ResponseToJSON(json: any): UserManagementControllerRemoveVAlpha200Response {
    return UserManagementControllerRemoveVAlpha200ResponseToJSONTyped(json, false);
}

export function UserManagementControllerRemoveVAlpha200ResponseToJSONTyped(value?: UserManagementControllerRemoveVAlpha200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DeleteManagedUserResponseToJSON(value['data']),
        'meta': AuthControllerUnifiedAuth200ResponseMetaToJSON(value['meta']),
    };
}

