/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VorfallAuditTimelineEintragDto } from './VorfallAuditTimelineEintragDto';
import {
    VorfallAuditTimelineEintragDtoFromJSON,
    VorfallAuditTimelineEintragDtoFromJSONTyped,
    VorfallAuditTimelineEintragDtoToJSON,
    VorfallAuditTimelineEintragDtoToJSONTyped,
} from './VorfallAuditTimelineEintragDto';

/**
 * 
 * @export
 * @interface VorfallAuditTimelineDto
 */
export interface VorfallAuditTimelineDto {
    /**
     * 
     * @type {Array<VorfallAuditTimelineEintragDto>}
     * @memberof VorfallAuditTimelineDto
     */
    eintraege: Array<VorfallAuditTimelineEintragDto>;
}

/**
 * Check if a given object implements the VorfallAuditTimelineDto interface.
 */
export function instanceOfVorfallAuditTimelineDto(value: object): value is VorfallAuditTimelineDto {
    if (!('eintraege' in value) || value['eintraege'] === undefined) return false;
    return true;
}

export function VorfallAuditTimelineDtoFromJSON(json: any): VorfallAuditTimelineDto {
    return VorfallAuditTimelineDtoFromJSONTyped(json, false);
}

export function VorfallAuditTimelineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VorfallAuditTimelineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'eintraege': ((json['eintraege'] as Array<any>).map(VorfallAuditTimelineEintragDtoFromJSON)),
    };
}

export function VorfallAuditTimelineDtoToJSON(json: any): VorfallAuditTimelineDto {
    return VorfallAuditTimelineDtoToJSONTyped(json, false);
}

export function VorfallAuditTimelineDtoToJSONTyped(value?: VorfallAuditTimelineDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eintraege': ((value['eintraege'] as Array<any>).map(VorfallAuditTimelineEintragDtoToJSON)),
    };
}

