/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.104-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZuordnungResponseDto
 */
export interface ZuordnungResponseDto {
    /**
     * ID der Zuordnung
     * @type {string}
     * @memberof ZuordnungResponseDto
     */
    id: string;
    /**
     * ID des Funkkanals
     * @type {string}
     * @memberof ZuordnungResponseDto
     */
    kanalId: string;
    /**
     * Typ der zugeordneten Kraft
     * @type {string}
     * @memberof ZuordnungResponseDto
     */
    kraftKind: ZuordnungResponseDtoKraftKindEnum;
    /**
     * ID des Fahrzeugs (nur bei kind=fahrzeug)
     * @type {object}
     * @memberof ZuordnungResponseDto
     */
    fahrzeugId?: object | null;
    /**
     * ID der Person (nur bei kind=person)
     * @type {object}
     * @memberof ZuordnungResponseDto
     */
    personId?: object | null;
    /**
     * ID der Einheit (nur bei kind=einheit)
     * @type {object}
     * @memberof ZuordnungResponseDto
     */
    einheitId?: object | null;
    /**
     * Rufname zum Zeitpunkt der Zuordnung (Snapshot)
     * @type {string}
     * @memberof ZuordnungResponseDto
     */
    rufnameSnapshot: string;
    /**
     * 
     * @type {string}
     * @memberof ZuordnungResponseDto
     */
    rolle: ZuordnungResponseDtoRolleEnum;
    /**
     * 
     * @type {Date}
     * @memberof ZuordnungResponseDto
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ZuordnungResponseDtoKraftKindEnum = {
    Fahrzeug: 'fahrzeug',
    Person: 'person',
    Einheit: 'einheit'
} as const;
export type ZuordnungResponseDtoKraftKindEnum = typeof ZuordnungResponseDtoKraftKindEnum[keyof typeof ZuordnungResponseDtoKraftKindEnum];

/**
 * @export
 */
export const ZuordnungResponseDtoRolleEnum = {
    Primaer: 'primaer',
    Sekundaer: 'sekundaer',
    Zuhoeren: 'zuhoeren'
} as const;
export type ZuordnungResponseDtoRolleEnum = typeof ZuordnungResponseDtoRolleEnum[keyof typeof ZuordnungResponseDtoRolleEnum];


/**
 * Check if a given object implements the ZuordnungResponseDto interface.
 */
export function instanceOfZuordnungResponseDto(value: object): value is ZuordnungResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kanalId' in value) || value['kanalId'] === undefined) return false;
    if (!('kraftKind' in value) || value['kraftKind'] === undefined) return false;
    if (!('rufnameSnapshot' in value) || value['rufnameSnapshot'] === undefined) return false;
    if (!('rolle' in value) || value['rolle'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ZuordnungResponseDtoFromJSON(json: any): ZuordnungResponseDto {
    return ZuordnungResponseDtoFromJSONTyped(json, false);
}

export function ZuordnungResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZuordnungResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kanalId': json['kanalId'],
        'kraftKind': json['kraftKind'],
        'fahrzeugId': json['fahrzeugId'] == null ? undefined : json['fahrzeugId'],
        'personId': json['personId'] == null ? undefined : json['personId'],
        'einheitId': json['einheitId'] == null ? undefined : json['einheitId'],
        'rufnameSnapshot': json['rufnameSnapshot'],
        'rolle': json['rolle'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ZuordnungResponseDtoToJSON(json: any): ZuordnungResponseDto {
    return ZuordnungResponseDtoToJSONTyped(json, false);
}

export function ZuordnungResponseDtoToJSONTyped(value?: ZuordnungResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kanalId': value['kanalId'],
        'kraftKind': value['kraftKind'],
        'fahrzeugId': value['fahrzeugId'],
        'personId': value['personId'],
        'einheitId': value['einheitId'],
        'rufnameSnapshot': value['rufnameSnapshot'],
        'rolle': value['rolle'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

