/**
 * Error Codes für Erinnerungsvorlage-Operationen.
 */
export const ERINNERUNGSVORLAGE_ERROR_CODES = {
  TITEL_REQUIRED: 'VORLAGE_TITEL_REQUIRED',
  TITEL_TOO_LONG: 'VORLAGE_TITEL_TOO_LONG',
  MINUTEN_INVALID: 'VORLAGE_MINUTEN_INVALID',
  BESCHREIBUNG_TOO_LONG: 'VORLAGE_BESCHREIBUNG_TOO_LONG',
  CREATED_BY_REQUIRED: 'VORLAGE_CREATED_BY_REQUIRED',
  CREATION_FAILED: 'VORLAGE_CREATION_FAILED',
  SAVE_FAILED: 'VORLAGE_SAVE_FAILED',
  NOT_FOUND: 'VORLAGE_NOT_FOUND',
  ALREADY_DELETED: 'VORLAGE_ALREADY_DELETED',
  NO_CHANGES: 'VORLAGE_NO_CHANGES',
  UPDATE_FAILED: 'VORLAGE_UPDATE_FAILED',
  DELETE_FAILED: 'VORLAGE_DELETE_FAILED',
} as const;
