/**
 * Error Codes für Erinnerungsvorlage-Operationen.
 */
export const ERINNERUNGSVORLAGE_ERROR_CODES = {
  TITEL_REQUIRED: 'VORLAGE_TITEL_REQUIRED',
  TITEL_TOO_LONG: 'VORLAGE_TITEL_TOO_LONG',
  MINUTEN_INVALID: 'VORLAGE_MINUTEN_INVALID',
  BESCHREIBUNG_TOO_LONG: 'VORLAGE_BESCHREIBUNG_TOO_LONG',
  CREATED_BY_REQUIRED: 'VORLAGE_CREATED_BY_REQUIRED',
  CREATION_FAILED: 'VORLAGE_CREATION_FAILED',
  SAVE_FAILED: 'VORLAGE_SAVE_FAILED',
  NOT_FOUND: 'VORLAGE_NOT_FOUND',
} as const;
