export const GEFAHR_ERROR_CODES = {
  EINSATZ_ID_REQUIRED: 'GEFAHR_EINSATZ_ID_REQUIRED',
  GEFAHRENTYP_INVALID: 'GEFAHR_GEFAHRENTYP_INVALID',
  SCHUTZOBJEKT_INVALID: 'GEFAHR_SCHUTZOBJEKT_INVALID',
  WARNSTUFE_INVALID: 'GEFAHR_WARNSTUFE_INVALID',
  AKTUALISIERT_VON_REQUIRED: 'GEFAHR_AKTUALISIERT_VON_REQUIRED',
} as const;
