export const GEFAHRENZONE_APPLICATION_ERROR_CODES = {
  EINSATZ_ID_REQUIRED: 'GEFAHRENZONE_EINSATZ_ID_REQUIRED',
  ZONE_ID_REQUIRED: 'GEFAHRENZONE_ZONE_ID_REQUIRED',
  GEFAHRENTYP_INVALID: 'GEFAHRENZONE_GEFAHRENTYP_INVALID',
  SCHUTZOBJEKT_INVALID: 'GEFAHRENZONE_SCHUTZOBJEKT_INVALID',
  GEOMETRY_TYPE_INVALID: 'GEFAHRENZONE_GEOMETRY_TYPE_INVALID',
  GEOMETRY_INVALID: 'GEFAHRENZONE_GEOMETRY_INVALID',
  BEZEICHNUNG_TOO_LONG: 'GEFAHRENZONE_BEZEICHNUNG_TOO_LONG',
  NOT_FOUND: 'GEFAHRENZONE_NOT_FOUND',
  AKTUALISIERT_VON_REQUIRED: 'GEFAHRENZONE_AKTUALISIERT_VON_REQUIRED',
  ERSTELLT_VON_REQUIRED: 'GEFAHRENZONE_ERSTELLT_VON_REQUIRED',
} as const;
