name: Frontend E2E Tests

on:
  push:
    branches: [main, develop, feature/*, alpha, beta, release/*]
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/frontend-e2e.yml'
  pull_request:
    branches: [main, develop, feature/*, alpha, beta, release/*]
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/frontend-e2e.yml'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bluelight_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @bluelight-hub/shared build:ci

      - name: Setup backend for E2E tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bluelight_test
          JWT_SECRET: test-secret
          JWT_REFRESH_SECRET: test-refresh-secret
          REDIS_URL: redis://localhost:6379
        run: |
          pnpm --filter @bluelight-hub/backend prisma generate
          pnpm --filter @bluelight-hub/backend prisma migrate deploy
          pnpm --filter @bluelight-hub/backend build

      - name: Start backend server
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bluelight_test
          JWT_SECRET: test-secret
          JWT_REFRESH_SECRET: test-refresh-secret
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test
        run: |
          pnpm --filter @bluelight-hub/backend start:prod &
          # Wait for backend to become healthy instead of a fixed sleep
          echo "Waiting for backend to be ready..."
          ATTEMPTS=60
          SLEEP_SECONDS=2
          for i in $(seq 1 $ATTEMPTS); do
            if curl -fsS http://localhost:3000/api/health/liveness > /dev/null; then
              echo "Backend is ready (attempt $i)."
              break
            fi
            echo "Attempt $i/$ATTEMPTS: Backend not ready yet. Retrying in ${SLEEP_SECONDS}s..."
            sleep $SLEEP_SECONDS
          done
          # Final check to fail fast if backend is still not ready
          if ! curl -fsS http://localhost:3000/api/health/liveness > /dev/null; then
            echo "Backend failed to become ready within $((ATTEMPTS * SLEEP_SECONDS)) seconds."
            exit 1
          fi

      - name: Install Playwright Browsers
        run: pnpm --filter @bluelight-hub/frontend exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm --filter @bluelight-hub/frontend test:e2e
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/frontend/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: packages/frontend/test-results/
          retention-days: 7
