---
#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana
on:
  workflow_dispatch:
  push:
    branches: [main, develop, feature/*, alpha, beta, release/*]
  pull_request:
    branches: [main, develop, feature/*, alpha, beta, release/*]

jobs:
  qodana:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: qodana-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
        with:
          pr-mode: ${{ github.event_name == 'pull_request' }}
          use-caches: true
          post-pr-comment: ${{ github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork }}
          use-annotations: true
          upload-result: true
