name: Release
run-name: Release ${{ github.ref_name }}#${{ github.run_number }}
on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main, alpha, beta, next]
    types: 
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  check-test-success:
    name: Check Test Success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Test success confirmed
        run: echo "Tests were successful, proceeding with release"

  build-backend:
    name: Build Backend
    needs: [check-test-success]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "TAGS=latest,main,main:${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Set tags for other branches
        if: github.ref != 'refs/heads/main'
        run: echo "TAGS=${GITHUB_REF#refs/heads/},${GITHUB_REF#refs/heads/}:${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image tags
        run: echo "${{ steps.meta.outputs.tags }}" > backend-image-tags.txt

      - name: Upload Backend Image Tags
        uses: actions/upload-artifact@v4
        with:
          name: backend-image-tags
          path: backend-image-tags.txt

  build-frontend:
    name: Build Frontend on ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            artifact_suffix: 'macos-arm64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            artifact_suffix: 'macos-x64'
          - platform: 'ubuntu-22.04'
            args: ''
            artifact_suffix: 'ubuntu'
          - platform: 'windows-latest'
            args: ''
            artifact_suffix: 'windows'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.3.0'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: cd packages/frontend && pnpm install

      - name: Prepare Windows Version (Windows only)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          # Function to get only major.minor.patch
          function Get-BaseVersion {
              param($version)
              if ($version -match '(\d+\.\d+\.\d+)') {
                  return $matches[1]
              }
              return $version
          }

          # Update package.json
          $packageContent = Get-Content packages/frontend/package.json -Raw
          $packageJson = $packageContent | ConvertFrom-Json
          $packageJson.version = Get-BaseVersion $packageJson.version
          $packageJson | ConvertTo-Json -Depth 32 | Set-Content packages/frontend/package.json

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: packages/frontend
          args: ${{ matrix.args }}

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact-${{ matrix.artifact_suffix }}
          path: packages/frontend/src-tauri/target/release/bundle

  release:
    name: Create Release
    needs: [ build-backend, build-frontend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.3.0'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Download Backend Image Tags
        uses: actions/download-artifact@v4
        with:
          name: backend-image-tags

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          path: frontend-artifacts
          pattern: frontend-artifact-*

      - name: Prepare Release Notes
        run: |
          echo "## Docker Image Tags" >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md
          cat backend-image-tags.txt >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## Frontend Artifacts" >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md
          ls -R frontend-artifacts/frontend-artifact-* >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ github.workspace }}/RELEASE_NOTES.md
        run: npx semantic-release 