/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.103-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AckPsaQuittungDto,
  AckSicherheitsregelDto,
  AufloeseSicherungspostenDto,
  BulkChangePsaProfilDto,
  ChangePsaProfilDto,
  CreateGefaehrdungsbeurteilungDto,
  CreateSicherheitsregelDto,
  CreateSicherungspostenDto,
  EigenschutzAmpelControllerGetAmpelVAlpha200Response,
  EigenschutzAmpelControllerListWarnBadgesVAlpha200Response,
  EigenschutzHealthControllerGetHealthVAlpha200Response,
  EigenschutzTelemetryControllerIngestVAlpha200Response,
  EigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha200Response,
  EigenschutzVorfallControllerListVorfaelleVAlpha200Response,
  EigenschutzVorfallControllerReportVorfallVAlpha201Response,
  GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response,
  GefaehrdungsbeurteilungControllerGetHistorieVAlpha200Response,
  GefaehrdungsbeurteilungControllerListBeurteilungenVAlpha200Response,
  GefaehrdungsbeurteilungControllerListVorlagenVAlpha200Response,
  MeldeLueckeDto,
  PsaProfilControllerChangePsaProfilVAlpha201Response,
  PsaProfilControllerGetPsaProfileVAlpha200Response,
  PsaProfilControllerListOffeneBekanntgabenVAlpha200Response,
  PsaProfilControllerListOffeneRueckmeldungenVAlpha200Response,
  PsaProfilControllerListQuittungenVAlpha200Response,
  ReportSyncConflictDto,
  ReportVorfallDto,
  ResolveSyncConflictDto,
  SicherheitsregelControllerGetRegelVAlpha200Response,
  SicherheitsregelControllerListQuittungenVAlpha200Response,
  SicherheitsregelControllerListRegelnVAlpha200Response,
  SicherungspostenControllerCreateSicherungspostenVAlpha201Response,
  SicherungspostenControllerListSicherungspostenVAlpha200Response,
  SyncConflictControllerListSyncConflictsVAlpha200Response,
  SyncConflictControllerReportSyncConflictVAlpha200Response,
  SyncConflictControllerResolveSyncConflictVAlpha200Response,
  TelemetryEventBatchDto,
  UpdateGefaehrdungsbeurteilungItemsDto,
  UpdateSicherheitsregelDto,
  UpdateSicherungspostenDto,
} from '../models/index';
import {
    AckPsaQuittungDtoFromJSON,
    AckPsaQuittungDtoToJSON,
    AckSicherheitsregelDtoFromJSON,
    AckSicherheitsregelDtoToJSON,
    AufloeseSicherungspostenDtoFromJSON,
    AufloeseSicherungspostenDtoToJSON,
    BulkChangePsaProfilDtoFromJSON,
    BulkChangePsaProfilDtoToJSON,
    ChangePsaProfilDtoFromJSON,
    ChangePsaProfilDtoToJSON,
    CreateGefaehrdungsbeurteilungDtoFromJSON,
    CreateGefaehrdungsbeurteilungDtoToJSON,
    CreateSicherheitsregelDtoFromJSON,
    CreateSicherheitsregelDtoToJSON,
    CreateSicherungspostenDtoFromJSON,
    CreateSicherungspostenDtoToJSON,
    EigenschutzAmpelControllerGetAmpelVAlpha200ResponseFromJSON,
    EigenschutzAmpelControllerGetAmpelVAlpha200ResponseToJSON,
    EigenschutzAmpelControllerListWarnBadgesVAlpha200ResponseFromJSON,
    EigenschutzAmpelControllerListWarnBadgesVAlpha200ResponseToJSON,
    EigenschutzHealthControllerGetHealthVAlpha200ResponseFromJSON,
    EigenschutzHealthControllerGetHealthVAlpha200ResponseToJSON,
    EigenschutzTelemetryControllerIngestVAlpha200ResponseFromJSON,
    EigenschutzTelemetryControllerIngestVAlpha200ResponseToJSON,
    EigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha200ResponseFromJSON,
    EigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha200ResponseToJSON,
    EigenschutzVorfallControllerListVorfaelleVAlpha200ResponseFromJSON,
    EigenschutzVorfallControllerListVorfaelleVAlpha200ResponseToJSON,
    EigenschutzVorfallControllerReportVorfallVAlpha201ResponseFromJSON,
    EigenschutzVorfallControllerReportVorfallVAlpha201ResponseToJSON,
    GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201ResponseFromJSON,
    GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201ResponseToJSON,
    GefaehrdungsbeurteilungControllerGetHistorieVAlpha200ResponseFromJSON,
    GefaehrdungsbeurteilungControllerGetHistorieVAlpha200ResponseToJSON,
    GefaehrdungsbeurteilungControllerListBeurteilungenVAlpha200ResponseFromJSON,
    GefaehrdungsbeurteilungControllerListBeurteilungenVAlpha200ResponseToJSON,
    GefaehrdungsbeurteilungControllerListVorlagenVAlpha200ResponseFromJSON,
    GefaehrdungsbeurteilungControllerListVorlagenVAlpha200ResponseToJSON,
    MeldeLueckeDtoFromJSON,
    MeldeLueckeDtoToJSON,
    PsaProfilControllerChangePsaProfilVAlpha201ResponseFromJSON,
    PsaProfilControllerChangePsaProfilVAlpha201ResponseToJSON,
    PsaProfilControllerGetPsaProfileVAlpha200ResponseFromJSON,
    PsaProfilControllerGetPsaProfileVAlpha200ResponseToJSON,
    PsaProfilControllerListOffeneBekanntgabenVAlpha200ResponseFromJSON,
    PsaProfilControllerListOffeneBekanntgabenVAlpha200ResponseToJSON,
    PsaProfilControllerListOffeneRueckmeldungenVAlpha200ResponseFromJSON,
    PsaProfilControllerListOffeneRueckmeldungenVAlpha200ResponseToJSON,
    PsaProfilControllerListQuittungenVAlpha200ResponseFromJSON,
    PsaProfilControllerListQuittungenVAlpha200ResponseToJSON,
    ReportSyncConflictDtoFromJSON,
    ReportSyncConflictDtoToJSON,
    ReportVorfallDtoFromJSON,
    ReportVorfallDtoToJSON,
    ResolveSyncConflictDtoFromJSON,
    ResolveSyncConflictDtoToJSON,
    SicherheitsregelControllerGetRegelVAlpha200ResponseFromJSON,
    SicherheitsregelControllerGetRegelVAlpha200ResponseToJSON,
    SicherheitsregelControllerListQuittungenVAlpha200ResponseFromJSON,
    SicherheitsregelControllerListQuittungenVAlpha200ResponseToJSON,
    SicherheitsregelControllerListRegelnVAlpha200ResponseFromJSON,
    SicherheitsregelControllerListRegelnVAlpha200ResponseToJSON,
    SicherungspostenControllerCreateSicherungspostenVAlpha201ResponseFromJSON,
    SicherungspostenControllerCreateSicherungspostenVAlpha201ResponseToJSON,
    SicherungspostenControllerListSicherungspostenVAlpha200ResponseFromJSON,
    SicherungspostenControllerListSicherungspostenVAlpha200ResponseToJSON,
    SyncConflictControllerListSyncConflictsVAlpha200ResponseFromJSON,
    SyncConflictControllerListSyncConflictsVAlpha200ResponseToJSON,
    SyncConflictControllerReportSyncConflictVAlpha200ResponseFromJSON,
    SyncConflictControllerReportSyncConflictVAlpha200ResponseToJSON,
    SyncConflictControllerResolveSyncConflictVAlpha200ResponseFromJSON,
    SyncConflictControllerResolveSyncConflictVAlpha200ResponseToJSON,
    TelemetryEventBatchDtoFromJSON,
    TelemetryEventBatchDtoToJSON,
    UpdateGefaehrdungsbeurteilungItemsDtoFromJSON,
    UpdateGefaehrdungsbeurteilungItemsDtoToJSON,
    UpdateSicherheitsregelDtoFromJSON,
    UpdateSicherheitsregelDtoToJSON,
    UpdateSicherungspostenDtoFromJSON,
    UpdateSicherungspostenDtoToJSON,
} from '../models/index';

export interface EigenschutzAmpelControllerGetAmpelVAlphaRequest {
    einsatzId: string;
}

export interface EigenschutzAmpelControllerListWarnBadgesVAlphaRequest {
    einsatzId: string;
}

export interface EigenschutzHealthControllerGetHealthVAlphaRequest {
    einsatzId: string;
}

export interface EigenschutzTelemetryControllerIngestVAlphaRequest {
    einsatzId: string;
    telemetryEventBatchDto: TelemetryEventBatchDto;
}

export interface EigenschutzVorfallControllerExportVorfallVAlphaRequest {
    einsatzId: string;
    vorfallId: string;
    format?: EigenschutzVorfallControllerExportVorfallVAlphaFormatEnum;
}

export interface EigenschutzVorfallControllerGetVorfallAuditTimelineVAlphaRequest {
    einsatzId: string;
    vorfallId: string;
}

export interface EigenschutzVorfallControllerGetVorfallVAlphaRequest {
    einsatzId: string;
    vorfallId: string;
}

export interface EigenschutzVorfallControllerListVorfaelleVAlphaRequest {
    einsatzId: string;
    einheitIds?: string;
    vorfallZeitVon?: string;
    vorfallZeitBis?: string;
    unfallkasseRelevant?: boolean;
}

export interface EigenschutzVorfallControllerReportVorfallVAlphaRequest {
    einsatzId: string;
    reportVorfallDto: ReportVorfallDto;
}

export interface GefaehrdungsbeurteilungControllerCreateBeurteilungVAlphaRequest {
    einsatzId: string;
    createGefaehrdungsbeurteilungDto: CreateGefaehrdungsbeurteilungDto;
}

export interface GefaehrdungsbeurteilungControllerGetBeurteilungVAlphaRequest {
    einsatzId: string;
    id: string;
}

export interface GefaehrdungsbeurteilungControllerGetHistorieVAlphaRequest {
    einsatzId: string;
    id: string;
}

export interface GefaehrdungsbeurteilungControllerListBeurteilungenVAlphaRequest {
    einsatzId: string;
}

export interface GefaehrdungsbeurteilungControllerListVorlagenVAlphaRequest {
    einsatzId: string;
}

export interface GefaehrdungsbeurteilungControllerUpdateItemsVAlphaRequest {
    einsatzId: string;
    id: string;
    updateGefaehrdungsbeurteilungItemsDto: UpdateGefaehrdungsbeurteilungItemsDto;
}

export interface PsaProfilControllerBulkChangePsaProfilVAlphaRequest {
    einsatzId: string;
    bulkChangePsaProfilDto: BulkChangePsaProfilDto;
}

export interface PsaProfilControllerChangePsaProfilVAlphaRequest {
    einsatzId: string;
    einheitId: string;
    changePsaProfilDto: ChangePsaProfilDto;
}

export interface PsaProfilControllerGetPsaProfileVAlphaRequest {
    einsatzId: string;
    einheitId: string;
}

export interface PsaProfilControllerListOffeneBekanntgabenVAlphaRequest {
    einsatzId: string;
    seit?: string;
}

export interface PsaProfilControllerListOffeneRueckmeldungenVAlphaRequest {
    einsatzId: string;
}

export interface PsaProfilControllerListQuittungenVAlphaRequest {
    einsatzId: string;
    propagationGroupId: string;
}

export interface PsaProfilControllerMeldeLueckeVAlphaRequest {
    einsatzId: string;
    propagationGroupId: string;
    meldeLueckeDto: MeldeLueckeDto;
}

export interface PsaProfilControllerQuittierenVAlphaRequest {
    einsatzId: string;
    propagationGroupId: string;
    ackPsaQuittungDto: AckPsaQuittungDto;
}

export interface SicherheitsregelControllerCreateRegelnVAlphaRequest {
    einsatzId: string;
    createSicherheitsregelDto: CreateSicherheitsregelDto;
}

export interface SicherheitsregelControllerGetRegelVAlphaRequest {
    einsatzId: string;
    id: string;
}

export interface SicherheitsregelControllerListQuittungenVAlphaRequest {
    einsatzId: string;
    id: string;
}

export interface SicherheitsregelControllerListRegelnVAlphaRequest {
    einsatzId: string;
    einheitId?: string;
}

export interface SicherheitsregelControllerQuittierenVAlphaRequest {
    einsatzId: string;
    id: string;
    ackSicherheitsregelDto: AckSicherheitsregelDto;
}

export interface SicherheitsregelControllerUpdateRegelVAlphaRequest {
    einsatzId: string;
    id: string;
    updateSicherheitsregelDto: UpdateSicherheitsregelDto;
}

export interface SicherungspostenControllerAufloeseSicherungspostenVAlphaRequest {
    einsatzId: string;
    postenId: string;
    aufloeseSicherungspostenDto: AufloeseSicherungspostenDto;
}

export interface SicherungspostenControllerCreateSicherungspostenVAlphaRequest {
    einsatzId: string;
    createSicherungspostenDto: CreateSicherungspostenDto;
}

export interface SicherungspostenControllerGetSicherungspostenVAlphaRequest {
    einsatzId: string;
    postenId: string;
}

export interface SicherungspostenControllerListSicherungspostenVAlphaRequest {
    einsatzId: string;
    status: SicherungspostenControllerListSicherungspostenVAlphaStatusEnum;
}

export interface SicherungspostenControllerUpdateSicherungspostenVAlphaRequest {
    einsatzId: string;
    postenId: string;
    updateSicherungspostenDto: UpdateSicherungspostenDto;
}

export interface SyncConflictControllerListSyncConflictsVAlphaRequest {
    einsatzId: string;
    entityType?: SyncConflictControllerListSyncConflictsVAlphaEntityTypeEnum;
    einheitId?: string;
}

export interface SyncConflictControllerReportSyncConflictVAlphaRequest {
    einsatzId: string;
    reportSyncConflictDto: ReportSyncConflictDto;
}

export interface SyncConflictControllerResolveSyncConflictVAlphaRequest {
    einsatzId: string;
    syncConflictId: string;
    resolveSyncConflictDto: ResolveSyncConflictDto;
}

/**
 * 
 */
export class EigenschutzApi extends runtime.BaseAPI {

    /**
     * Eigenschutz-Ampelstatus für alle Einheiten des Einsatzes laden
     */
    async eigenschutzAmpelControllerGetAmpelVAlphaRaw(requestParameters: EigenschutzAmpelControllerGetAmpelVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzAmpelControllerGetAmpelVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzAmpelControllerGetAmpelVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/ampel`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzAmpelControllerGetAmpelVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Eigenschutz-Ampelstatus für alle Einheiten des Einsatzes laden
     */
    async eigenschutzAmpelControllerGetAmpelVAlpha(requestParameters: EigenschutzAmpelControllerGetAmpelVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzAmpelControllerGetAmpelVAlpha200Response> {
        const response = await this.eigenschutzAmpelControllerGetAmpelVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Eigenschutz-Warn-Markierungen für alle Einheiten des Einsatzes laden
     */
    async eigenschutzAmpelControllerListWarnBadgesVAlphaRaw(requestParameters: EigenschutzAmpelControllerListWarnBadgesVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzAmpelControllerListWarnBadgesVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzAmpelControllerListWarnBadgesVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/ampel/warn-badges`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzAmpelControllerListWarnBadgesVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Eigenschutz-Warn-Markierungen für alle Einheiten des Einsatzes laden
     */
    async eigenschutzAmpelControllerListWarnBadgesVAlpha(requestParameters: EigenschutzAmpelControllerListWarnBadgesVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzAmpelControllerListWarnBadgesVAlpha200Response> {
        const response = await this.eigenschutzAmpelControllerListWarnBadgesVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Eigenschutz-Modul-Health — signalisiert, dass das Modul für den Einsatz verdrahtet ist
     */
    async eigenschutzHealthControllerGetHealthVAlphaRaw(requestParameters: EigenschutzHealthControllerGetHealthVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzHealthControllerGetHealthVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzHealthControllerGetHealthVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/health`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzHealthControllerGetHealthVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Eigenschutz-Modul-Health — signalisiert, dass das Modul für den Einsatz verdrahtet ist
     */
    async eigenschutzHealthControllerGetHealthVAlpha(requestParameters: EigenschutzHealthControllerGetHealthVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzHealthControllerGetHealthVAlpha200Response> {
        const response = await this.eigenschutzHealthControllerGetHealthVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Telemetrie-Batch (1–50 Events) für CBRN-Moment-Auswertung — Story 3.11 (FR21, AR8)
     */
    async eigenschutzTelemetryControllerIngestVAlphaRaw(requestParameters: EigenschutzTelemetryControllerIngestVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzTelemetryControllerIngestVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzTelemetryControllerIngestVAlpha().'
            );
        }

        if (requestParameters['telemetryEventBatchDto'] == null) {
            throw new runtime.RequiredError(
                'telemetryEventBatchDto',
                'Required parameter "telemetryEventBatchDto" was null or undefined when calling eigenschutzTelemetryControllerIngestVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/telemetry`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TelemetryEventBatchDtoToJSON(requestParameters['telemetryEventBatchDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzTelemetryControllerIngestVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Telemetrie-Batch (1–50 Events) für CBRN-Moment-Auswertung — Story 3.11 (FR21, AR8)
     */
    async eigenschutzTelemetryControllerIngestVAlpha(requestParameters: EigenschutzTelemetryControllerIngestVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzTelemetryControllerIngestVAlpha200Response> {
        const response = await this.eigenschutzTelemetryControllerIngestVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Vorfall als PDF oder JSON exportieren (Unfallkassen-Format)
     */
    async eigenschutzVorfallControllerExportVorfallVAlphaRaw(requestParameters: EigenschutzVorfallControllerExportVorfallVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzVorfallControllerExportVorfallVAlpha().'
            );
        }

        if (requestParameters['vorfallId'] == null) {
            throw new runtime.RequiredError(
                'vorfallId',
                'Required parameter "vorfallId" was null or undefined when calling eigenschutzVorfallControllerExportVorfallVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/vorfaelle/{vorfallId}/export`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"vorfallId"}}`, encodeURIComponent(String(requestParameters['vorfallId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Vorfall als PDF oder JSON exportieren (Unfallkassen-Format)
     */
    async eigenschutzVorfallControllerExportVorfallVAlpha(requestParameters: EigenschutzVorfallControllerExportVorfallVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.eigenschutzVorfallControllerExportVorfallVAlphaRaw(requestParameters, initOverrides);
    }

    /**
     * Export-Historie eines Vorfalls laden
     */
    async eigenschutzVorfallControllerGetVorfallAuditTimelineVAlphaRaw(requestParameters: EigenschutzVorfallControllerGetVorfallAuditTimelineVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha().'
            );
        }

        if (requestParameters['vorfallId'] == null) {
            throw new runtime.RequiredError(
                'vorfallId',
                'Required parameter "vorfallId" was null or undefined when calling eigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/vorfaelle/{vorfallId}/audit-timeline`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"vorfallId"}}`, encodeURIComponent(String(requestParameters['vorfallId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Export-Historie eines Vorfalls laden
     */
    async eigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha(requestParameters: EigenschutzVorfallControllerGetVorfallAuditTimelineVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzVorfallControllerGetVorfallAuditTimelineVAlpha200Response> {
        const response = await this.eigenschutzVorfallControllerGetVorfallAuditTimelineVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Vorfall-Detail laden (inkl. zeitpunkt-genauem Kontext-Snapshot)
     */
    async eigenschutzVorfallControllerGetVorfallVAlphaRaw(requestParameters: EigenschutzVorfallControllerGetVorfallVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzVorfallControllerReportVorfallVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzVorfallControllerGetVorfallVAlpha().'
            );
        }

        if (requestParameters['vorfallId'] == null) {
            throw new runtime.RequiredError(
                'vorfallId',
                'Required parameter "vorfallId" was null or undefined when calling eigenschutzVorfallControllerGetVorfallVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/vorfaelle/{vorfallId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"vorfallId"}}`, encodeURIComponent(String(requestParameters['vorfallId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzVorfallControllerReportVorfallVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Vorfall-Detail laden (inkl. zeitpunkt-genauem Kontext-Snapshot)
     */
    async eigenschutzVorfallControllerGetVorfallVAlpha(requestParameters: EigenschutzVorfallControllerGetVorfallVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzVorfallControllerReportVorfallVAlpha201Response> {
        const response = await this.eigenschutzVorfallControllerGetVorfallVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Vorfälle eines Einsatzes filtern (Liste, max. 200 Einträge)
     */
    async eigenschutzVorfallControllerListVorfaelleVAlphaRaw(requestParameters: EigenschutzVorfallControllerListVorfaelleVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzVorfallControllerListVorfaelleVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzVorfallControllerListVorfaelleVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['einheitIds'] != null) {
            queryParameters['einheitIds'] = requestParameters['einheitIds'];
        }

        if (requestParameters['vorfallZeitVon'] != null) {
            queryParameters['vorfallZeitVon'] = requestParameters['vorfallZeitVon'];
        }

        if (requestParameters['vorfallZeitBis'] != null) {
            queryParameters['vorfallZeitBis'] = requestParameters['vorfallZeitBis'];
        }

        if (requestParameters['unfallkasseRelevant'] != null) {
            queryParameters['unfallkasseRelevant'] = requestParameters['unfallkasseRelevant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/vorfaelle`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzVorfallControllerListVorfaelleVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Vorfälle eines Einsatzes filtern (Liste, max. 200 Einträge)
     */
    async eigenschutzVorfallControllerListVorfaelleVAlpha(requestParameters: EigenschutzVorfallControllerListVorfaelleVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzVorfallControllerListVorfaelleVAlpha200Response> {
        const response = await this.eigenschutzVorfallControllerListVorfaelleVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Neuen Vorfall melden (Pflichtfelder Was/Wann/Wo/Beteiligte/Maßnahmen)
     */
    async eigenschutzVorfallControllerReportVorfallVAlphaRaw(requestParameters: EigenschutzVorfallControllerReportVorfallVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EigenschutzVorfallControllerReportVorfallVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling eigenschutzVorfallControllerReportVorfallVAlpha().'
            );
        }

        if (requestParameters['reportVorfallDto'] == null) {
            throw new runtime.RequiredError(
                'reportVorfallDto',
                'Required parameter "reportVorfallDto" was null or undefined when calling eigenschutzVorfallControllerReportVorfallVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/vorfaelle`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReportVorfallDtoToJSON(requestParameters['reportVorfallDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EigenschutzVorfallControllerReportVorfallVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Neuen Vorfall melden (Pflichtfelder Was/Wann/Wo/Beteiligte/Maßnahmen)
     */
    async eigenschutzVorfallControllerReportVorfallVAlpha(requestParameters: EigenschutzVorfallControllerReportVorfallVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EigenschutzVorfallControllerReportVorfallVAlpha201Response> {
        const response = await this.eigenschutzVorfallControllerReportVorfallVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Neue Gefährdungsbeurteilung für eine Einheit anlegen
     */
    async gefaehrdungsbeurteilungControllerCreateBeurteilungVAlphaRaw(requestParameters: GefaehrdungsbeurteilungControllerCreateBeurteilungVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling gefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha().'
            );
        }

        if (requestParameters['createGefaehrdungsbeurteilungDto'] == null) {
            throw new runtime.RequiredError(
                'createGefaehrdungsbeurteilungDto',
                'Required parameter "createGefaehrdungsbeurteilungDto" was null or undefined when calling gefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/gefaehrdungsbeurteilungen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGefaehrdungsbeurteilungDtoToJSON(requestParameters['createGefaehrdungsbeurteilungDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Neue Gefährdungsbeurteilung für eine Einheit anlegen
     */
    async gefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha(requestParameters: GefaehrdungsbeurteilungControllerCreateBeurteilungVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response> {
        const response = await this.gefaehrdungsbeurteilungControllerCreateBeurteilungVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Eine Gefährdungsbeurteilung per ID abrufen
     */
    async gefaehrdungsbeurteilungControllerGetBeurteilungVAlphaRaw(requestParameters: GefaehrdungsbeurteilungControllerGetBeurteilungVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling gefaehrdungsbeurteilungControllerGetBeurteilungVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gefaehrdungsbeurteilungControllerGetBeurteilungVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/gefaehrdungsbeurteilungen/{id}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Eine Gefährdungsbeurteilung per ID abrufen
     */
    async gefaehrdungsbeurteilungControllerGetBeurteilungVAlpha(requestParameters: GefaehrdungsbeurteilungControllerGetBeurteilungVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response> {
        const response = await this.gefaehrdungsbeurteilungControllerGetBeurteilungVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Versionshistorie einer Gefährdungsbeurteilung (Story 2.4)
     */
    async gefaehrdungsbeurteilungControllerGetHistorieVAlphaRaw(requestParameters: GefaehrdungsbeurteilungControllerGetHistorieVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GefaehrdungsbeurteilungControllerGetHistorieVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling gefaehrdungsbeurteilungControllerGetHistorieVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gefaehrdungsbeurteilungControllerGetHistorieVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/gefaehrdungsbeurteilungen/{id}/versionen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GefaehrdungsbeurteilungControllerGetHistorieVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Versionshistorie einer Gefährdungsbeurteilung (Story 2.4)
     */
    async gefaehrdungsbeurteilungControllerGetHistorieVAlpha(requestParameters: GefaehrdungsbeurteilungControllerGetHistorieVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GefaehrdungsbeurteilungControllerGetHistorieVAlpha200Response> {
        const response = await this.gefaehrdungsbeurteilungControllerGetHistorieVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gefährdungsbeurteilungen des Einsatzes auflisten
     */
    async gefaehrdungsbeurteilungControllerListBeurteilungenVAlphaRaw(requestParameters: GefaehrdungsbeurteilungControllerListBeurteilungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GefaehrdungsbeurteilungControllerListBeurteilungenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling gefaehrdungsbeurteilungControllerListBeurteilungenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/gefaehrdungsbeurteilungen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GefaehrdungsbeurteilungControllerListBeurteilungenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Gefährdungsbeurteilungen des Einsatzes auflisten
     */
    async gefaehrdungsbeurteilungControllerListBeurteilungenVAlpha(requestParameters: GefaehrdungsbeurteilungControllerListBeurteilungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GefaehrdungsbeurteilungControllerListBeurteilungenVAlpha200Response> {
        const response = await this.gefaehrdungsbeurteilungControllerListBeurteilungenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aktive Gefährdungsbeurteilungs-Vorlagen abrufen
     */
    async gefaehrdungsbeurteilungControllerListVorlagenVAlphaRaw(requestParameters: GefaehrdungsbeurteilungControllerListVorlagenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GefaehrdungsbeurteilungControllerListVorlagenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling gefaehrdungsbeurteilungControllerListVorlagenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/gefaehrdungsbeurteilungs-vorlagen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GefaehrdungsbeurteilungControllerListVorlagenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Aktive Gefährdungsbeurteilungs-Vorlagen abrufen
     */
    async gefaehrdungsbeurteilungControllerListVorlagenVAlpha(requestParameters: GefaehrdungsbeurteilungControllerListVorlagenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GefaehrdungsbeurteilungControllerListVorlagenVAlpha200Response> {
        const response = await this.gefaehrdungsbeurteilungControllerListVorlagenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Items einer Gefährdungsbeurteilung aktualisieren (FR3, FR4)
     */
    async gefaehrdungsbeurteilungControllerUpdateItemsVAlphaRaw(requestParameters: GefaehrdungsbeurteilungControllerUpdateItemsVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling gefaehrdungsbeurteilungControllerUpdateItemsVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gefaehrdungsbeurteilungControllerUpdateItemsVAlpha().'
            );
        }

        if (requestParameters['updateGefaehrdungsbeurteilungItemsDto'] == null) {
            throw new runtime.RequiredError(
                'updateGefaehrdungsbeurteilungItemsDto',
                'Required parameter "updateGefaehrdungsbeurteilungItemsDto" was null or undefined when calling gefaehrdungsbeurteilungControllerUpdateItemsVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/gefaehrdungsbeurteilungen/{id}/items`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGefaehrdungsbeurteilungItemsDtoToJSON(requestParameters['updateGefaehrdungsbeurteilungItemsDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Items einer Gefährdungsbeurteilung aktualisieren (FR3, FR4)
     */
    async gefaehrdungsbeurteilungControllerUpdateItemsVAlpha(requestParameters: GefaehrdungsbeurteilungControllerUpdateItemsVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GefaehrdungsbeurteilungControllerCreateBeurteilungVAlpha201Response> {
        const response = await this.gefaehrdungsbeurteilungControllerUpdateItemsVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * PSA-Profil-Toggle gleichzeitig auf mehrere Einheiten anwenden (Bulk)
     */
    async psaProfilControllerBulkChangePsaProfilVAlphaRaw(requestParameters: PsaProfilControllerBulkChangePsaProfilVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PsaProfilControllerChangePsaProfilVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerBulkChangePsaProfilVAlpha().'
            );
        }

        if (requestParameters['bulkChangePsaProfilDto'] == null) {
            throw new runtime.RequiredError(
                'bulkChangePsaProfilDto',
                'Required parameter "bulkChangePsaProfilDto" was null or undefined when calling psaProfilControllerBulkChangePsaProfilVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/bulk-aendern`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkChangePsaProfilDtoToJSON(requestParameters['bulkChangePsaProfilDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PsaProfilControllerChangePsaProfilVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * PSA-Profil-Toggle gleichzeitig auf mehrere Einheiten anwenden (Bulk)
     */
    async psaProfilControllerBulkChangePsaProfilVAlpha(requestParameters: PsaProfilControllerBulkChangePsaProfilVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PsaProfilControllerChangePsaProfilVAlpha201Response> {
        const response = await this.psaProfilControllerBulkChangePsaProfilVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * PSA-Profil-Toggle einer Einheit ausführen
     */
    async psaProfilControllerChangePsaProfilVAlphaRaw(requestParameters: PsaProfilControllerChangePsaProfilVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PsaProfilControllerChangePsaProfilVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerChangePsaProfilVAlpha().'
            );
        }

        if (requestParameters['einheitId'] == null) {
            throw new runtime.RequiredError(
                'einheitId',
                'Required parameter "einheitId" was null or undefined when calling psaProfilControllerChangePsaProfilVAlpha().'
            );
        }

        if (requestParameters['changePsaProfilDto'] == null) {
            throw new runtime.RequiredError(
                'changePsaProfilDto',
                'Required parameter "changePsaProfilDto" was null or undefined when calling psaProfilControllerChangePsaProfilVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/einheiten/{einheitId}/change`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"einheitId"}}`, encodeURIComponent(String(requestParameters['einheitId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePsaProfilDtoToJSON(requestParameters['changePsaProfilDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PsaProfilControllerChangePsaProfilVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * PSA-Profil-Toggle einer Einheit ausführen
     */
    async psaProfilControllerChangePsaProfilVAlpha(requestParameters: PsaProfilControllerChangePsaProfilVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PsaProfilControllerChangePsaProfilVAlpha201Response> {
        const response = await this.psaProfilControllerChangePsaProfilVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aktive PSA-Profile einer Einheit laden
     */
    async psaProfilControllerGetPsaProfileVAlphaRaw(requestParameters: PsaProfilControllerGetPsaProfileVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PsaProfilControllerGetPsaProfileVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerGetPsaProfileVAlpha().'
            );
        }

        if (requestParameters['einheitId'] == null) {
            throw new runtime.RequiredError(
                'einheitId',
                'Required parameter "einheitId" was null or undefined when calling psaProfilControllerGetPsaProfileVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/einheiten/{einheitId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"einheitId"}}`, encodeURIComponent(String(requestParameters['einheitId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PsaProfilControllerGetPsaProfileVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Aktive PSA-Profile einer Einheit laden
     */
    async psaProfilControllerGetPsaProfileVAlpha(requestParameters: PsaProfilControllerGetPsaProfileVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PsaProfilControllerGetPsaProfileVAlpha200Response> {
        const response = await this.psaProfilControllerGetPsaProfileVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Offene PSA-Bekanntgaben des Einsatzes auflisten (pending/partial) — AC15
     */
    async psaProfilControllerListOffeneBekanntgabenVAlphaRaw(requestParameters: PsaProfilControllerListOffeneBekanntgabenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PsaProfilControllerListOffeneBekanntgabenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerListOffeneBekanntgabenVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['seit'] != null) {
            queryParameters['seit'] = requestParameters['seit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/propagation-groups/offene-bekanntgaben`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PsaProfilControllerListOffeneBekanntgabenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Offene PSA-Bekanntgaben des Einsatzes auflisten (pending/partial) — AC15
     */
    async psaProfilControllerListOffeneBekanntgabenVAlpha(requestParameters: PsaProfilControllerListOffeneBekanntgabenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PsaProfilControllerListOffeneBekanntgabenVAlpha200Response> {
        const response = await this.psaProfilControllerListOffeneBekanntgabenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Offene Ausrüstungs-Lücken-Rückmeldungen eines Einsatzes auflisten
     */
    async psaProfilControllerListOffeneRueckmeldungenVAlphaRaw(requestParameters: PsaProfilControllerListOffeneRueckmeldungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PsaProfilControllerListOffeneRueckmeldungenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerListOffeneRueckmeldungenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/rueckmeldungen/offen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PsaProfilControllerListOffeneRueckmeldungenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Offene Ausrüstungs-Lücken-Rückmeldungen eines Einsatzes auflisten
     */
    async psaProfilControllerListOffeneRueckmeldungenVAlpha(requestParameters: PsaProfilControllerListOffeneRueckmeldungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PsaProfilControllerListOffeneRueckmeldungenVAlpha200Response> {
        const response = await this.psaProfilControllerListOffeneRueckmeldungenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Quittungs-Stand einer PSA-Bekanntgabe-Gruppe auflisten (Sender-View) — AC8
     */
    async psaProfilControllerListQuittungenVAlphaRaw(requestParameters: PsaProfilControllerListQuittungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PsaProfilControllerListQuittungenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerListQuittungenVAlpha().'
            );
        }

        if (requestParameters['propagationGroupId'] == null) {
            throw new runtime.RequiredError(
                'propagationGroupId',
                'Required parameter "propagationGroupId" was null or undefined when calling psaProfilControllerListQuittungenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/propagation-groups/{propagationGroupId}/quittungen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"propagationGroupId"}}`, encodeURIComponent(String(requestParameters['propagationGroupId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PsaProfilControllerListQuittungenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Quittungs-Stand einer PSA-Bekanntgabe-Gruppe auflisten (Sender-View) — AC8
     */
    async psaProfilControllerListQuittungenVAlpha(requestParameters: PsaProfilControllerListQuittungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PsaProfilControllerListQuittungenVAlpha200Response> {
        const response = await this.psaProfilControllerListQuittungenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ausrüstungs-Lücke zu einer PSA-Bekanntgabe melden — Story 3.6 AC6
     */
    async psaProfilControllerMeldeLueckeVAlphaRaw(requestParameters: PsaProfilControllerMeldeLueckeVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerMeldeLueckeVAlpha().'
            );
        }

        if (requestParameters['propagationGroupId'] == null) {
            throw new runtime.RequiredError(
                'propagationGroupId',
                'Required parameter "propagationGroupId" was null or undefined when calling psaProfilControllerMeldeLueckeVAlpha().'
            );
        }

        if (requestParameters['meldeLueckeDto'] == null) {
            throw new runtime.RequiredError(
                'meldeLueckeDto',
                'Required parameter "meldeLueckeDto" was null or undefined when calling psaProfilControllerMeldeLueckeVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/propagation-groups/{propagationGroupId}/luecke-melden`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"propagationGroupId"}}`, encodeURIComponent(String(requestParameters['propagationGroupId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MeldeLueckeDtoToJSON(requestParameters['meldeLueckeDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ausrüstungs-Lücke zu einer PSA-Bekanntgabe melden — Story 3.6 AC6
     */
    async psaProfilControllerMeldeLueckeVAlpha(requestParameters: PsaProfilControllerMeldeLueckeVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.psaProfilControllerMeldeLueckeVAlphaRaw(requestParameters, initOverrides);
    }

    /**
     * PSA-Profil-Änderung durch eine konkrete Einheit quittieren — AC1/AC2/AC3
     */
    async psaProfilControllerQuittierenVAlphaRaw(requestParameters: PsaProfilControllerQuittierenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling psaProfilControllerQuittierenVAlpha().'
            );
        }

        if (requestParameters['propagationGroupId'] == null) {
            throw new runtime.RequiredError(
                'propagationGroupId',
                'Required parameter "propagationGroupId" was null or undefined when calling psaProfilControllerQuittierenVAlpha().'
            );
        }

        if (requestParameters['ackPsaQuittungDto'] == null) {
            throw new runtime.RequiredError(
                'ackPsaQuittungDto',
                'Required parameter "ackPsaQuittungDto" was null or undefined when calling psaProfilControllerQuittierenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/psa-profile/propagation-groups/{propagationGroupId}/quittieren`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"propagationGroupId"}}`, encodeURIComponent(String(requestParameters['propagationGroupId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AckPsaQuittungDtoToJSON(requestParameters['ackPsaQuittungDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * PSA-Profil-Änderung durch eine konkrete Einheit quittieren — AC1/AC2/AC3
     */
    async psaProfilControllerQuittierenVAlpha(requestParameters: PsaProfilControllerQuittierenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.psaProfilControllerQuittierenVAlphaRaw(requestParameters, initOverrides);
    }

    /**
     * Neue Sicherheitsregel anlegen (einsatzweit oder Fanout an Einheiten)
     */
    async sicherheitsregelControllerCreateRegelnVAlphaRaw(requestParameters: SicherheitsregelControllerCreateRegelnVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherheitsregelControllerListRegelnVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherheitsregelControllerCreateRegelnVAlpha().'
            );
        }

        if (requestParameters['createSicherheitsregelDto'] == null) {
            throw new runtime.RequiredError(
                'createSicherheitsregelDto',
                'Required parameter "createSicherheitsregelDto" was null or undefined when calling sicherheitsregelControllerCreateRegelnVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherheitsregeln`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSicherheitsregelDtoToJSON(requestParameters['createSicherheitsregelDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherheitsregelControllerListRegelnVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Neue Sicherheitsregel anlegen (einsatzweit oder Fanout an Einheiten)
     */
    async sicherheitsregelControllerCreateRegelnVAlpha(requestParameters: SicherheitsregelControllerCreateRegelnVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherheitsregelControllerListRegelnVAlpha200Response> {
        const response = await this.sicherheitsregelControllerCreateRegelnVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Eine Sicherheitsregel per ID abrufen
     */
    async sicherheitsregelControllerGetRegelVAlphaRaw(requestParameters: SicherheitsregelControllerGetRegelVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherheitsregelControllerGetRegelVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherheitsregelControllerGetRegelVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sicherheitsregelControllerGetRegelVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherheitsregeln/{id}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherheitsregelControllerGetRegelVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Eine Sicherheitsregel per ID abrufen
     */
    async sicherheitsregelControllerGetRegelVAlpha(requestParameters: SicherheitsregelControllerGetRegelVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherheitsregelControllerGetRegelVAlpha200Response> {
        const response = await this.sicherheitsregelControllerGetRegelVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Quittungen einer Sicherheitsregel auflisten (Sender-View)
     */
    async sicherheitsregelControllerListQuittungenVAlphaRaw(requestParameters: SicherheitsregelControllerListQuittungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherheitsregelControllerListQuittungenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherheitsregelControllerListQuittungenVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sicherheitsregelControllerListQuittungenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherheitsregeln/{id}/quittungen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherheitsregelControllerListQuittungenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Quittungen einer Sicherheitsregel auflisten (Sender-View)
     */
    async sicherheitsregelControllerListQuittungenVAlpha(requestParameters: SicherheitsregelControllerListQuittungenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherheitsregelControllerListQuittungenVAlpha200Response> {
        const response = await this.sicherheitsregelControllerListQuittungenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aktive Sicherheitsregeln des Einsatzes auflisten
     */
    async sicherheitsregelControllerListRegelnVAlphaRaw(requestParameters: SicherheitsregelControllerListRegelnVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherheitsregelControllerListRegelnVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherheitsregelControllerListRegelnVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['einheitId'] != null) {
            queryParameters['einheitId'] = requestParameters['einheitId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherheitsregeln`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherheitsregelControllerListRegelnVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Aktive Sicherheitsregeln des Einsatzes auflisten
     */
    async sicherheitsregelControllerListRegelnVAlpha(requestParameters: SicherheitsregelControllerListRegelnVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherheitsregelControllerListRegelnVAlpha200Response> {
        const response = await this.sicherheitsregelControllerListRegelnVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sicherheitsregel durch eine konkrete Einheit quittieren — AC2/AC3/AC4
     */
    async sicherheitsregelControllerQuittierenVAlphaRaw(requestParameters: SicherheitsregelControllerQuittierenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherheitsregelControllerQuittierenVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sicherheitsregelControllerQuittierenVAlpha().'
            );
        }

        if (requestParameters['ackSicherheitsregelDto'] == null) {
            throw new runtime.RequiredError(
                'ackSicherheitsregelDto',
                'Required parameter "ackSicherheitsregelDto" was null or undefined when calling sicherheitsregelControllerQuittierenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherheitsregeln/{id}/quittieren`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AckSicherheitsregelDtoToJSON(requestParameters['ackSicherheitsregelDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sicherheitsregel durch eine konkrete Einheit quittieren — AC2/AC3/AC4
     */
    async sicherheitsregelControllerQuittierenVAlpha(requestParameters: SicherheitsregelControllerQuittierenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sicherheitsregelControllerQuittierenVAlphaRaw(requestParameters, initOverrides);
    }

    /**
     * Sicherheitsregel aktualisieren (In-Place oder Re-Wire) — AC3/AC4/AC10
     */
    async sicherheitsregelControllerUpdateRegelVAlphaRaw(requestParameters: SicherheitsregelControllerUpdateRegelVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherheitsregelControllerListRegelnVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherheitsregelControllerUpdateRegelVAlpha().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sicherheitsregelControllerUpdateRegelVAlpha().'
            );
        }

        if (requestParameters['updateSicherheitsregelDto'] == null) {
            throw new runtime.RequiredError(
                'updateSicherheitsregelDto',
                'Required parameter "updateSicherheitsregelDto" was null or undefined when calling sicherheitsregelControllerUpdateRegelVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherheitsregeln/{id}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSicherheitsregelDtoToJSON(requestParameters['updateSicherheitsregelDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherheitsregelControllerListRegelnVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Sicherheitsregel aktualisieren (In-Place oder Re-Wire) — AC3/AC4/AC10
     */
    async sicherheitsregelControllerUpdateRegelVAlpha(requestParameters: SicherheitsregelControllerUpdateRegelVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherheitsregelControllerListRegelnVAlpha200Response> {
        const response = await this.sicherheitsregelControllerUpdateRegelVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sicherungsposten auflösen (Pflicht-Begründung — UX-DR27)
     */
    async sicherungspostenControllerAufloeseSicherungspostenVAlphaRaw(requestParameters: SicherungspostenControllerAufloeseSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherungspostenControllerCreateSicherungspostenVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherungspostenControllerAufloeseSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['postenId'] == null) {
            throw new runtime.RequiredError(
                'postenId',
                'Required parameter "postenId" was null or undefined when calling sicherungspostenControllerAufloeseSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['aufloeseSicherungspostenDto'] == null) {
            throw new runtime.RequiredError(
                'aufloeseSicherungspostenDto',
                'Required parameter "aufloeseSicherungspostenDto" was null or undefined when calling sicherungspostenControllerAufloeseSicherungspostenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherungsposten/{postenId}/aufloesen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"postenId"}}`, encodeURIComponent(String(requestParameters['postenId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AufloeseSicherungspostenDtoToJSON(requestParameters['aufloeseSicherungspostenDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherungspostenControllerCreateSicherungspostenVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Sicherungsposten auflösen (Pflicht-Begründung — UX-DR27)
     */
    async sicherungspostenControllerAufloeseSicherungspostenVAlpha(requestParameters: SicherungspostenControllerAufloeseSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherungspostenControllerCreateSicherungspostenVAlpha201Response> {
        const response = await this.sicherungspostenControllerAufloeseSicherungspostenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Neuen Sicherungsposten anlegen
     */
    async sicherungspostenControllerCreateSicherungspostenVAlphaRaw(requestParameters: SicherungspostenControllerCreateSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherungspostenControllerCreateSicherungspostenVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherungspostenControllerCreateSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['createSicherungspostenDto'] == null) {
            throw new runtime.RequiredError(
                'createSicherungspostenDto',
                'Required parameter "createSicherungspostenDto" was null or undefined when calling sicherungspostenControllerCreateSicherungspostenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherungsposten`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSicherungspostenDtoToJSON(requestParameters['createSicherungspostenDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherungspostenControllerCreateSicherungspostenVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Neuen Sicherungsposten anlegen
     */
    async sicherungspostenControllerCreateSicherungspostenVAlpha(requestParameters: SicherungspostenControllerCreateSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherungspostenControllerCreateSicherungspostenVAlpha201Response> {
        const response = await this.sicherungspostenControllerCreateSicherungspostenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lädt einen Sicherungsposten samt Persistenz-Metadaten für die Detail-Ansicht (Story 4.4 — bidirektionale Navigation Karte ↔ Detail). Cross-Einsatz-Zugriff liefert 404 (kein 403), damit die Existenz fremder Posten nicht leakt.
     * Sicherungsposten per ID laden (Detail-Ansicht)
     */
    async sicherungspostenControllerGetSicherungspostenVAlphaRaw(requestParameters: SicherungspostenControllerGetSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherungspostenControllerCreateSicherungspostenVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherungspostenControllerGetSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['postenId'] == null) {
            throw new runtime.RequiredError(
                'postenId',
                'Required parameter "postenId" was null or undefined when calling sicherungspostenControllerGetSicherungspostenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherungsposten/{postenId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"postenId"}}`, encodeURIComponent(String(requestParameters['postenId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherungspostenControllerCreateSicherungspostenVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Lädt einen Sicherungsposten samt Persistenz-Metadaten für die Detail-Ansicht (Story 4.4 — bidirektionale Navigation Karte ↔ Detail). Cross-Einsatz-Zugriff liefert 404 (kein 403), damit die Existenz fremder Posten nicht leakt.
     * Sicherungsposten per ID laden (Detail-Ansicht)
     */
    async sicherungspostenControllerGetSicherungspostenVAlpha(requestParameters: SicherungspostenControllerGetSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherungspostenControllerCreateSicherungspostenVAlpha201Response> {
        const response = await this.sicherungspostenControllerGetSicherungspostenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sicherungsposten eines Einsatzes auflisten (Status-Filter AKTIV/AUFGELOEST)
     */
    async sicherungspostenControllerListSicherungspostenVAlphaRaw(requestParameters: SicherungspostenControllerListSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherungspostenControllerListSicherungspostenVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherungspostenControllerListSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling sicherungspostenControllerListSicherungspostenVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherungsposten`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherungspostenControllerListSicherungspostenVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Sicherungsposten eines Einsatzes auflisten (Status-Filter AKTIV/AUFGELOEST)
     */
    async sicherungspostenControllerListSicherungspostenVAlpha(requestParameters: SicherungspostenControllerListSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherungspostenControllerListSicherungspostenVAlpha200Response> {
        const response = await this.sicherungspostenControllerListSicherungspostenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sicherungsposten aktualisieren (Optimistic-Concurrency)
     */
    async sicherungspostenControllerUpdateSicherungspostenVAlphaRaw(requestParameters: SicherungspostenControllerUpdateSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SicherungspostenControllerCreateSicherungspostenVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling sicherungspostenControllerUpdateSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['postenId'] == null) {
            throw new runtime.RequiredError(
                'postenId',
                'Required parameter "postenId" was null or undefined when calling sicherungspostenControllerUpdateSicherungspostenVAlpha().'
            );
        }

        if (requestParameters['updateSicherungspostenDto'] == null) {
            throw new runtime.RequiredError(
                'updateSicherungspostenDto',
                'Required parameter "updateSicherungspostenDto" was null or undefined when calling sicherungspostenControllerUpdateSicherungspostenVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sicherungsposten/{postenId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"postenId"}}`, encodeURIComponent(String(requestParameters['postenId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSicherungspostenDtoToJSON(requestParameters['updateSicherungspostenDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SicherungspostenControllerCreateSicherungspostenVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Sicherungsposten aktualisieren (Optimistic-Concurrency)
     */
    async sicherungspostenControllerUpdateSicherungspostenVAlpha(requestParameters: SicherungspostenControllerUpdateSicherungspostenVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SicherungspostenControllerCreateSicherungspostenVAlpha201Response> {
        const response = await this.sicherungspostenControllerUpdateSicherungspostenVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Liste offener Sync-Konflikte für den Einsatz — Story 3.10 (FR50, UX-DR6)
     */
    async syncConflictControllerListSyncConflictsVAlphaRaw(requestParameters: SyncConflictControllerListSyncConflictsVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncConflictControllerListSyncConflictsVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling syncConflictControllerListSyncConflictsVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['entityType'] != null) {
            queryParameters['entityType'] = requestParameters['entityType'];
        }

        if (requestParameters['einheitId'] != null) {
            queryParameters['einheitId'] = requestParameters['einheitId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sync-conflicts`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyncConflictControllerListSyncConflictsVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Liste offener Sync-Konflikte für den Einsatz — Story 3.10 (FR50, UX-DR6)
     */
    async syncConflictControllerListSyncConflictsVAlpha(requestParameters: SyncConflictControllerListSyncConflictsVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncConflictControllerListSyncConflictsVAlpha200Response> {
        const response = await this.syncConflictControllerListSyncConflictsVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sync-Konflikt aus 409-Mutation melden — Story 3.9 (FR50)
     */
    async syncConflictControllerReportSyncConflictVAlphaRaw(requestParameters: SyncConflictControllerReportSyncConflictVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncConflictControllerReportSyncConflictVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling syncConflictControllerReportSyncConflictVAlpha().'
            );
        }

        if (requestParameters['reportSyncConflictDto'] == null) {
            throw new runtime.RequiredError(
                'reportSyncConflictDto',
                'Required parameter "reportSyncConflictDto" was null or undefined when calling syncConflictControllerReportSyncConflictVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sync-conflicts`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReportSyncConflictDtoToJSON(requestParameters['reportSyncConflictDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyncConflictControllerReportSyncConflictVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Sync-Konflikt aus 409-Mutation melden — Story 3.9 (FR50)
     */
    async syncConflictControllerReportSyncConflictVAlpha(requestParameters: SyncConflictControllerReportSyncConflictVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncConflictControllerReportSyncConflictVAlpha200Response> {
        const response = await this.syncConflictControllerReportSyncConflictVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sync-Konflikt auflösen — Story 3.10 (FR50, UX-DR6)
     */
    async syncConflictControllerResolveSyncConflictVAlphaRaw(requestParameters: SyncConflictControllerResolveSyncConflictVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncConflictControllerResolveSyncConflictVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling syncConflictControllerResolveSyncConflictVAlpha().'
            );
        }

        if (requestParameters['syncConflictId'] == null) {
            throw new runtime.RequiredError(
                'syncConflictId',
                'Required parameter "syncConflictId" was null or undefined when calling syncConflictControllerResolveSyncConflictVAlpha().'
            );
        }

        if (requestParameters['resolveSyncConflictDto'] == null) {
            throw new runtime.RequiredError(
                'resolveSyncConflictDto',
                'Required parameter "resolveSyncConflictDto" was null or undefined when calling syncConflictControllerResolveSyncConflictVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsaetze/{einsatzId}/sicherheit/eigenschutz/sync-conflicts/{syncConflictId}/resolve`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"syncConflictId"}}`, encodeURIComponent(String(requestParameters['syncConflictId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ResolveSyncConflictDtoToJSON(requestParameters['resolveSyncConflictDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyncConflictControllerResolveSyncConflictVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Sync-Konflikt auflösen — Story 3.10 (FR50, UX-DR6)
     */
    async syncConflictControllerResolveSyncConflictVAlpha(requestParameters: SyncConflictControllerResolveSyncConflictVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncConflictControllerResolveSyncConflictVAlpha200Response> {
        const response = await this.syncConflictControllerResolveSyncConflictVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const EigenschutzVorfallControllerExportVorfallVAlphaFormatEnum = {
    Pdf: 'pdf',
    Json: 'json'
} as const;
export type EigenschutzVorfallControllerExportVorfallVAlphaFormatEnum = typeof EigenschutzVorfallControllerExportVorfallVAlphaFormatEnum[keyof typeof EigenschutzVorfallControllerExportVorfallVAlphaFormatEnum];
/**
 * @export
 */
export const SicherungspostenControllerListSicherungspostenVAlphaStatusEnum = {
    Aktiv: 'AKTIV',
    Aufgeloest: 'AUFGELOEST'
} as const;
export type SicherungspostenControllerListSicherungspostenVAlphaStatusEnum = typeof SicherungspostenControllerListSicherungspostenVAlphaStatusEnum[keyof typeof SicherungspostenControllerListSicherungspostenVAlphaStatusEnum];
/**
 * @export
 */
export const SyncConflictControllerListSyncConflictsVAlphaEntityTypeEnum = {
    PsaProfilZuweisung: 'PSA_PROFIL_ZUWEISUNG',
    GefaehrdungsbeurteilungItem: 'GEFAEHRDUNGSBEURTEILUNG_ITEM'
} as const;
export type SyncConflictControllerListSyncConflictsVAlphaEntityTypeEnum = typeof SyncConflictControllerListSyncConflictsVAlphaEntityTypeEnum[keyof typeof SyncConflictControllerListSyncConflictsVAlphaEntityTypeEnum];
