/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CreateEinsatzDto,
  EinsatzControllerCreateVAlpha200Response,
  EinsatzControllerFindAllVAlpha200Response,
  EinsatzControllerGetCompletenessVAlpha200Response,
  UpdateEinsatzDto,
} from '../models/index';
import {
  CreateEinsatzDtoFromJSON,
  CreateEinsatzDtoToJSON,
  EinsatzControllerCreateVAlpha200ResponseFromJSON,
  EinsatzControllerCreateVAlpha200ResponseToJSON,
  EinsatzControllerFindAllVAlpha200ResponseFromJSON,
  EinsatzControllerFindAllVAlpha200ResponseToJSON,
  EinsatzControllerGetCompletenessVAlpha200ResponseFromJSON,
  EinsatzControllerGetCompletenessVAlpha200ResponseToJSON,
  UpdateEinsatzDtoFromJSON,
  UpdateEinsatzDtoToJSON,
} from '../models/index';

export interface EinsatzControllerArchiveVAlphaRequest {
  id: string;
}

export interface EinsatzControllerCreateVAlphaRequest {
  createEinsatzDto: CreateEinsatzDto;
}

export interface EinsatzControllerFindAllVAlphaRequest {
  status?: EinsatzControllerFindAllVAlphaStatusEnum;
  includeCompleteness?: boolean;
  page?: number;
  limit?: number;
  search?: string;
}

export interface EinsatzControllerFindOneVAlphaRequest {
  id: string;
}

export interface EinsatzControllerGetCompletenessVAlphaRequest {
  id: string;
  refresh?: boolean;
}

export interface EinsatzControllerUpdateVAlphaRequest {
  id: string;
  updateEinsatzDto: UpdateEinsatzDto;
}

/**
 *
 */
export class EinsatzApi extends runtime.BaseAPI {
  /**
   * Markiert einen Einsatz als ARCHIVIERT. Einsätze werden gemäß No-Delete Policy niemals physisch gelöscht.
   * Einsatz archivieren (Soft-Delete)
   */
  async einsatzControllerArchiveVAlphaRaw(
    requestParameters: EinsatzControllerArchiveVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzControllerCreateVAlpha200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling einsatzControllerArchiveVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz/{id}/archive`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzControllerCreateVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Markiert einen Einsatz als ARCHIVIERT. Einsätze werden gemäß No-Delete Policy niemals physisch gelöscht.
   * Einsatz archivieren (Soft-Delete)
   */
  async einsatzControllerArchiveVAlpha(
    requestParameters: EinsatzControllerArchiveVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzControllerCreateVAlpha200Response> {
    const response = await this.einsatzControllerArchiveVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Erstellt einen neuen Einsatz mit automatisch generiertem Namen. Alle Felder sind optional.
   * Neuen Einsatz erstellen
   */
  async einsatzControllerCreateVAlphaRaw(
    requestParameters: EinsatzControllerCreateVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzControllerCreateVAlpha200Response>> {
    if (requestParameters['createEinsatzDto'] == null) {
      throw new runtime.RequiredError('createEinsatzDto', 'Required parameter "createEinsatzDto" was null or undefined when calling einsatzControllerCreateVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateEinsatzDtoToJSON(requestParameters['createEinsatzDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzControllerCreateVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Erstellt einen neuen Einsatz mit automatisch generiertem Namen. Alle Felder sind optional.
   * Neuen Einsatz erstellen
   */
  async einsatzControllerCreateVAlpha(
    requestParameters: EinsatzControllerCreateVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzControllerCreateVAlpha200Response> {
    const response = await this.einsatzControllerCreateVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Gibt eine paginierte Liste aller Einsätze zurück, optional gefiltert nach Status.
   * Alle Einsätze abrufen
   */
  async einsatzControllerFindAllVAlphaRaw(
    requestParameters: EinsatzControllerFindAllVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzControllerFindAllVAlpha200Response>> {
    const queryParameters: any = {};

    if (requestParameters['status'] != null) {
      queryParameters['status'] = requestParameters['status'];
    }

    if (requestParameters['includeCompleteness'] != null) {
      queryParameters['includeCompleteness'] = requestParameters['includeCompleteness'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['search'] != null) {
      queryParameters['search'] = requestParameters['search'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzControllerFindAllVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Gibt eine paginierte Liste aller Einsätze zurück, optional gefiltert nach Status.
   * Alle Einsätze abrufen
   */
  async einsatzControllerFindAllVAlpha(
    requestParameters: EinsatzControllerFindAllVAlphaRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzControllerFindAllVAlpha200Response> {
    const response = await this.einsatzControllerFindAllVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Gibt einen einzelnen Einsatz mit allen Details zurück.
   * Einzelnen Einsatz abrufen
   */
  async einsatzControllerFindOneVAlphaRaw(
    requestParameters: EinsatzControllerFindOneVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzControllerCreateVAlpha200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling einsatzControllerFindOneVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzControllerCreateVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Gibt einen einzelnen Einsatz mit allen Details zurück.
   * Einzelnen Einsatz abrufen
   */
  async einsatzControllerFindOneVAlpha(
    requestParameters: EinsatzControllerFindOneVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzControllerCreateVAlpha200Response> {
    const response = await this.einsatzControllerFindOneVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Berechnet und gibt die Vollständigkeit eines Einsatzes zurück.
   * Vollständigkeits-Check für Einsatz
   */
  async einsatzControllerGetCompletenessVAlphaRaw(
    requestParameters: EinsatzControllerGetCompletenessVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzControllerGetCompletenessVAlpha200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling einsatzControllerGetCompletenessVAlpha().');
    }

    const queryParameters: any = {};

    if (requestParameters['refresh'] != null) {
      queryParameters['refresh'] = requestParameters['refresh'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz/{id}/completeness`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzControllerGetCompletenessVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Berechnet und gibt die Vollständigkeit eines Einsatzes zurück.
   * Vollständigkeits-Check für Einsatz
   */
  async einsatzControllerGetCompletenessVAlpha(
    requestParameters: EinsatzControllerGetCompletenessVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzControllerGetCompletenessVAlpha200Response> {
    const response = await this.einsatzControllerGetCompletenessVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Aktualisiert einen bestehenden Einsatz. Der Name wird automatisch neu generiert.
   * Einsatz aktualisieren
   */
  async einsatzControllerUpdateVAlphaRaw(
    requestParameters: EinsatzControllerUpdateVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzControllerCreateVAlpha200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling einsatzControllerUpdateVAlpha().');
    }

    if (requestParameters['updateEinsatzDto'] == null) {
      throw new runtime.RequiredError('updateEinsatzDto', 'Required parameter "updateEinsatzDto" was null or undefined when calling einsatzControllerUpdateVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateEinsatzDtoToJSON(requestParameters['updateEinsatzDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzControllerCreateVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Aktualisiert einen bestehenden Einsatz. Der Name wird automatisch neu generiert.
   * Einsatz aktualisieren
   */
  async einsatzControllerUpdateVAlpha(
    requestParameters: EinsatzControllerUpdateVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzControllerCreateVAlpha200Response> {
    const response = await this.einsatzControllerUpdateVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const EinsatzControllerFindAllVAlphaStatusEnum = {
  Angelegt: 'ANGELEGT',
  InBearbeitung: 'IN_BEARBEITUNG',
  Abgeschlossen: 'ABGESCHLOSSEN',
  Archiviert: 'ARCHIVIERT',
} as const;
export type EinsatzControllerFindAllVAlphaStatusEnum = (typeof EinsatzControllerFindAllVAlphaStatusEnum)[keyof typeof EinsatzControllerFindAllVAlphaStatusEnum];
