/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.39
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  EinsatzPersonenControllerFindAllVAlpha200Response,
  EinsatzPersonenControllerRegistrierePersonVAlpha201Response,
  EinsatzPersonenControllerWeiseZuFahrzeugVAlpha200Response,
  RegistrierePersonDto,
  RegistrierePersonViaQrCodeDto,
  WeisePersonZuFahrzeugZuDto,
} from '../models/index';
import {
  EinsatzPersonenControllerFindAllVAlpha200ResponseFromJSON,
  EinsatzPersonenControllerFindAllVAlpha200ResponseToJSON,
  EinsatzPersonenControllerRegistrierePersonVAlpha201ResponseFromJSON,
  EinsatzPersonenControllerRegistrierePersonVAlpha201ResponseToJSON,
  EinsatzPersonenControllerWeiseZuFahrzeugVAlpha200ResponseFromJSON,
  EinsatzPersonenControllerWeiseZuFahrzeugVAlpha200ResponseToJSON,
  RegistrierePersonDtoFromJSON,
  RegistrierePersonDtoToJSON,
  RegistrierePersonViaQrCodeDtoFromJSON,
  RegistrierePersonViaQrCodeDtoToJSON,
  WeisePersonZuFahrzeugZuDtoFromJSON,
  WeisePersonZuFahrzeugZuDtoToJSON,
} from '../models/index';

export interface EinsatzPersonenControllerEntferneVonFahrzeugVAlphaRequest {
  einsatzId: string;
  personId: string;
}

export interface EinsatzPersonenControllerFindAllVAlphaRequest {
  einsatzId: string;
}

export interface EinsatzPersonenControllerRegistrierePersonVAlphaRequest {
  einsatzId: string;
  registrierePersonDto: RegistrierePersonDto;
}

export interface EinsatzPersonenControllerRegistriereViaQrVAlphaRequest {
  einsatzId: string;
  registrierePersonViaQrCodeDto: RegistrierePersonViaQrCodeDto;
}

export interface EinsatzPersonenControllerWeiseZuFahrzeugVAlphaRequest {
  einsatzId: string;
  personId: string;
  weisePersonZuFahrzeugZuDto: WeisePersonZuFahrzeugZuDto;
}

/**
 *
 */
export class EinsatzPersonenApi extends runtime.BaseAPI {
  /**
   * Person von Fahrzeug entfernen
   */
  async einsatzPersonenControllerEntferneVonFahrzeugVAlphaRaw(
    requestParameters: EinsatzPersonenControllerEntferneVonFahrzeugVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling einsatzPersonenControllerEntferneVonFahrzeugVAlpha().');
    }

    if (requestParameters['personId'] == null) {
      throw new runtime.RequiredError('personId', 'Required parameter "personId" was null or undefined when calling einsatzPersonenControllerEntferneVonFahrzeugVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v-alpha/einsaetze/{einsatzId}/personen/{personId}/fahrzeug`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'personId'}}`, encodeURIComponent(String(requestParameters['personId']))),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Person von Fahrzeug entfernen
   */
  async einsatzPersonenControllerEntferneVonFahrzeugVAlpha(
    requestParameters: EinsatzPersonenControllerEntferneVonFahrzeugVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzPersonenControllerEntferneVonFahrzeugVAlphaRaw(requestParameters, initOverrides);
  }

  /**
   * Alle Personen eines Einsatzes auflisten
   */
  async einsatzPersonenControllerFindAllVAlphaRaw(
    requestParameters: EinsatzPersonenControllerFindAllVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzPersonenControllerFindAllVAlpha200Response>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling einsatzPersonenControllerFindAllVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v-alpha/einsaetze/{einsatzId}/personen`.replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzPersonenControllerFindAllVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Alle Personen eines Einsatzes auflisten
   */
  async einsatzPersonenControllerFindAllVAlpha(
    requestParameters: EinsatzPersonenControllerFindAllVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzPersonenControllerFindAllVAlpha200Response> {
    const response = await this.einsatzPersonenControllerFindAllVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Person für Einsatz registrieren
   */
  async einsatzPersonenControllerRegistrierePersonVAlphaRaw(
    requestParameters: EinsatzPersonenControllerRegistrierePersonVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzPersonenControllerRegistrierePersonVAlpha201Response>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling einsatzPersonenControllerRegistrierePersonVAlpha().');
    }

    if (requestParameters['registrierePersonDto'] == null) {
      throw new runtime.RequiredError('registrierePersonDto', 'Required parameter "registrierePersonDto" was null or undefined when calling einsatzPersonenControllerRegistrierePersonVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/v-alpha/einsaetze/{einsatzId}/personen`.replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RegistrierePersonDtoToJSON(requestParameters['registrierePersonDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzPersonenControllerRegistrierePersonVAlpha201ResponseFromJSON(jsonValue));
  }

  /**
   * Person für Einsatz registrieren
   */
  async einsatzPersonenControllerRegistrierePersonVAlpha(
    requestParameters: EinsatzPersonenControllerRegistrierePersonVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzPersonenControllerRegistrierePersonVAlpha201Response> {
    const response = await this.einsatzPersonenControllerRegistrierePersonVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Person via QR-Code registrieren (DRK-Format)
   */
  async einsatzPersonenControllerRegistriereViaQrVAlphaRaw(
    requestParameters: EinsatzPersonenControllerRegistriereViaQrVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzPersonenControllerRegistrierePersonVAlpha201Response>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling einsatzPersonenControllerRegistriereViaQrVAlpha().');
    }

    if (requestParameters['registrierePersonViaQrCodeDto'] == null) {
      throw new runtime.RequiredError(
        'registrierePersonViaQrCodeDto',
        'Required parameter "registrierePersonViaQrCodeDto" was null or undefined when calling einsatzPersonenControllerRegistriereViaQrVAlpha().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/v-alpha/einsaetze/{einsatzId}/personen/qr`.replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RegistrierePersonViaQrCodeDtoToJSON(requestParameters['registrierePersonViaQrCodeDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzPersonenControllerRegistrierePersonVAlpha201ResponseFromJSON(jsonValue));
  }

  /**
   * Person via QR-Code registrieren (DRK-Format)
   */
  async einsatzPersonenControllerRegistriereViaQrVAlpha(
    requestParameters: EinsatzPersonenControllerRegistriereViaQrVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzPersonenControllerRegistrierePersonVAlpha201Response> {
    const response = await this.einsatzPersonenControllerRegistriereViaQrVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Person zu Fahrzeug zuweisen
   */
  async einsatzPersonenControllerWeiseZuFahrzeugVAlphaRaw(
    requestParameters: EinsatzPersonenControllerWeiseZuFahrzeugVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EinsatzPersonenControllerWeiseZuFahrzeugVAlpha200Response>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling einsatzPersonenControllerWeiseZuFahrzeugVAlpha().');
    }

    if (requestParameters['personId'] == null) {
      throw new runtime.RequiredError('personId', 'Required parameter "personId" was null or undefined when calling einsatzPersonenControllerWeiseZuFahrzeugVAlpha().');
    }

    if (requestParameters['weisePersonZuFahrzeugZuDto'] == null) {
      throw new runtime.RequiredError(
        'weisePersonZuFahrzeugZuDto',
        'Required parameter "weisePersonZuFahrzeugZuDto" was null or undefined when calling einsatzPersonenControllerWeiseZuFahrzeugVAlpha().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/v-alpha/einsaetze/{einsatzId}/personen/{personId}/fahrzeug`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'personId'}}`, encodeURIComponent(String(requestParameters['personId']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: WeisePersonZuFahrzeugZuDtoToJSON(requestParameters['weisePersonZuFahrzeugZuDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzPersonenControllerWeiseZuFahrzeugVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Person zu Fahrzeug zuweisen
   */
  async einsatzPersonenControllerWeiseZuFahrzeugVAlpha(
    requestParameters: EinsatzPersonenControllerWeiseZuFahrzeugVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EinsatzPersonenControllerWeiseZuFahrzeugVAlpha200Response> {
    const response = await this.einsatzPersonenControllerWeiseZuFahrzeugVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
