/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.69-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EinsatzTeilnehmerControllerGetAllTeilnehmerVAlpha200Response,
  EinsatzTeilnehmerControllerJoinEinsatzVAlpha201Response,
  JoinEinsatzDto,
} from '../models/index';
import {
    EinsatzTeilnehmerControllerGetAllTeilnehmerVAlpha200ResponseFromJSON,
    EinsatzTeilnehmerControllerGetAllTeilnehmerVAlpha200ResponseToJSON,
    EinsatzTeilnehmerControllerJoinEinsatzVAlpha201ResponseFromJSON,
    EinsatzTeilnehmerControllerJoinEinsatzVAlpha201ResponseToJSON,
    JoinEinsatzDtoFromJSON,
    JoinEinsatzDtoToJSON,
} from '../models/index';

export interface EinsatzTeilnehmerControllerGetAllTeilnehmerVAlphaRequest {
    einsatzId: string;
}

export interface EinsatzTeilnehmerControllerGetMyTeilnahmeVAlphaRequest {
    einsatzId: string;
}

export interface EinsatzTeilnehmerControllerJoinEinsatzVAlphaRequest {
    einsatzId: string;
    joinEinsatzDto: JoinEinsatzDto;
}

/**
 * 
 */
export class EinsatzTeilnehmerApi extends runtime.BaseAPI {

    /**
     * Gibt alle aktiven Teilnehmer des Einsatzes zurück. Inkl. Person-Daten für ETB-Autocomplete.
     * Alle Einsatz-Teilnehmer abrufen
     */
    async einsatzTeilnehmerControllerGetAllTeilnehmerVAlphaRaw(requestParameters: EinsatzTeilnehmerControllerGetAllTeilnehmerVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EinsatzTeilnehmerControllerGetAllTeilnehmerVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling einsatzTeilnehmerControllerGetAllTeilnehmerVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/teilnahme`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzTeilnehmerControllerGetAllTeilnehmerVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Gibt alle aktiven Teilnehmer des Einsatzes zurück. Inkl. Person-Daten für ETB-Autocomplete.
     * Alle Einsatz-Teilnehmer abrufen
     */
    async einsatzTeilnehmerControllerGetAllTeilnehmerVAlpha(requestParameters: EinsatzTeilnehmerControllerGetAllTeilnehmerVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EinsatzTeilnehmerControllerGetAllTeilnehmerVAlpha200Response> {
        const response = await this.einsatzTeilnehmerControllerGetAllTeilnehmerVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gibt die aktive Teilnahme des aktuellen Users am Einsatz zurück. Inkl. Person-Daten für ETB Auto-Fill.
     * Eigene Einsatz-Teilnahme abrufen
     */
    async einsatzTeilnehmerControllerGetMyTeilnahmeVAlphaRaw(requestParameters: EinsatzTeilnehmerControllerGetMyTeilnahmeVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EinsatzTeilnehmerControllerJoinEinsatzVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling einsatzTeilnehmerControllerGetMyTeilnahmeVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/teilnahme/me`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzTeilnehmerControllerJoinEinsatzVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Gibt die aktive Teilnahme des aktuellen Users am Einsatz zurück. Inkl. Person-Daten für ETB Auto-Fill.
     * Eigene Einsatz-Teilnahme abrufen
     */
    async einsatzTeilnehmerControllerGetMyTeilnahmeVAlpha(requestParameters: EinsatzTeilnehmerControllerGetMyTeilnahmeVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EinsatzTeilnehmerControllerJoinEinsatzVAlpha201Response> {
        const response = await this.einsatzTeilnehmerControllerGetMyTeilnahmeVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Tritt dem Einsatz mit einer EinsatzPerson bei. Bei erneutem Aufruf wird die verknüpfte Person aktualisiert.
     * Einsatz beitreten
     */
    async einsatzTeilnehmerControllerJoinEinsatzVAlphaRaw(requestParameters: EinsatzTeilnehmerControllerJoinEinsatzVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EinsatzTeilnehmerControllerJoinEinsatzVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling einsatzTeilnehmerControllerJoinEinsatzVAlpha().'
            );
        }

        if (requestParameters['joinEinsatzDto'] == null) {
            throw new runtime.RequiredError(
                'joinEinsatzDto',
                'Required parameter "joinEinsatzDto" was null or undefined when calling einsatzTeilnehmerControllerJoinEinsatzVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/teilnahme`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinEinsatzDtoToJSON(requestParameters['joinEinsatzDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EinsatzTeilnehmerControllerJoinEinsatzVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Tritt dem Einsatz mit einer EinsatzPerson bei. Bei erneutem Aufruf wird die verknüpfte Person aktualisiert.
     * Einsatz beitreten
     */
    async einsatzTeilnehmerControllerJoinEinsatzVAlpha(requestParameters: EinsatzTeilnehmerControllerJoinEinsatzVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EinsatzTeilnehmerControllerJoinEinsatzVAlpha201Response> {
        const response = await this.einsatzTeilnehmerControllerJoinEinsatzVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
