/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateErinnerungDto, ErinnerungControllerCreateVAlpha201Response, ErinnerungControllerGetByEinsatzVAlpha200Response } from '../models/index';
import {
  CreateErinnerungDtoFromJSON,
  CreateErinnerungDtoToJSON,
  ErinnerungControllerCreateVAlpha201ResponseFromJSON,
  ErinnerungControllerCreateVAlpha201ResponseToJSON,
  ErinnerungControllerGetByEinsatzVAlpha200ResponseFromJSON,
  ErinnerungControllerGetByEinsatzVAlpha200ResponseToJSON,
} from '../models/index';

export interface ErinnerungControllerCreateVAlphaRequest {
  einsatzId: string;
  createErinnerungDto: CreateErinnerungDto;
}

export interface ErinnerungControllerGetByEinsatzVAlphaRequest {
  einsatzId: string;
}

/**
 *
 */
export class ErinnerungenApi extends runtime.BaseAPI {
  /**
   * Erstellt eine neue Erinnerung mit Titel und Fälligkeitszeitpunkt. Status wird auf GEPLANT gesetzt.
   * Neue Erinnerung erstellen
   */
  async erinnerungControllerCreateVAlphaRaw(
    requestParameters: ErinnerungControllerCreateVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ErinnerungControllerCreateVAlpha201Response>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling erinnerungControllerCreateVAlpha().');
    }

    if (requestParameters['createErinnerungDto'] == null) {
      throw new runtime.RequiredError('createErinnerungDto', 'Required parameter "createErinnerungDto" was null or undefined when calling erinnerungControllerCreateVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz/{einsatzId}/erinnerungen`.replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateErinnerungDtoToJSON(requestParameters['createErinnerungDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ErinnerungControllerCreateVAlpha201ResponseFromJSON(jsonValue));
  }

  /**
   * Erstellt eine neue Erinnerung mit Titel und Fälligkeitszeitpunkt. Status wird auf GEPLANT gesetzt.
   * Neue Erinnerung erstellen
   */
  async erinnerungControllerCreateVAlpha(
    requestParameters: ErinnerungControllerCreateVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ErinnerungControllerCreateVAlpha201Response> {
    const response = await this.erinnerungControllerCreateVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Gibt alle Erinnerungen des Einsatzes sortiert nach Fälligkeit (aufsteigend) zurück.
   * Alle Erinnerungen eines Einsatzes abrufen
   */
  async erinnerungControllerGetByEinsatzVAlphaRaw(
    requestParameters: ErinnerungControllerGetByEinsatzVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ErinnerungControllerGetByEinsatzVAlpha200Response>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError('einsatzId', 'Required parameter "einsatzId" was null or undefined when calling erinnerungControllerGetByEinsatzVAlpha().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v-alpha/einsatz/{einsatzId}/erinnerungen`.replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ErinnerungControllerGetByEinsatzVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Gibt alle Erinnerungen des Einsatzes sortiert nach Fälligkeit (aufsteigend) zurück.
   * Alle Erinnerungen eines Einsatzes abrufen
   */
  async erinnerungControllerGetByEinsatzVAlpha(
    requestParameters: ErinnerungControllerGetByEinsatzVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ErinnerungControllerGetByEinsatzVAlpha200Response> {
    const response = await this.erinnerungControllerGetByEinsatzVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
