/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application
 *
 * The version of the OpenAPI document: 1.0.0-alpha.36
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { StammFahrzeugeControllerFindAllVAlpha200Response } from '../models/index';
import { StammFahrzeugeControllerFindAllVAlpha200ResponseFromJSON, StammFahrzeugeControllerFindAllVAlpha200ResponseToJSON } from '../models/index';

export interface StammFahrzeugeControllerFindAllVAlphaRequest {
  includeArchived?: boolean;
}

/**
 *
 */
export class KraefteStammFahrzeugeApi extends runtime.BaseAPI {
  /**
   * Alle StammFahrzeuge auflisten
   */
  async stammFahrzeugeControllerFindAllVAlphaRaw(
    requestParameters: StammFahrzeugeControllerFindAllVAlphaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StammFahrzeugeControllerFindAllVAlpha200Response>> {
    const queryParameters: any = {};

    if (requestParameters['includeArchived'] != null) {
      queryParameters['includeArchived'] = requestParameters['includeArchived'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v-alpha/kraefte/stamm-fahrzeuge`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => StammFahrzeugeControllerFindAllVAlpha200ResponseFromJSON(jsonValue));
  }

  /**
   * Alle StammFahrzeuge auflisten
   */
  async stammFahrzeugeControllerFindAllVAlpha(
    requestParameters: StammFahrzeugeControllerFindAllVAlphaRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StammFahrzeugeControllerFindAllVAlpha200Response> {
    const response = await this.stammFahrzeugeControllerFindAllVAlphaRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
