/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateNotizDto,
  NotizControllerCreateVAlpha201Response,
  NotizControllerGetByEinsatzVAlpha200Response,
  UpdateNotizDto,
} from '../models/index';
import {
    CreateNotizDtoFromJSON,
    CreateNotizDtoToJSON,
    NotizControllerCreateVAlpha201ResponseFromJSON,
    NotizControllerCreateVAlpha201ResponseToJSON,
    NotizControllerGetByEinsatzVAlpha200ResponseFromJSON,
    NotizControllerGetByEinsatzVAlpha200ResponseToJSON,
    UpdateNotizDtoFromJSON,
    UpdateNotizDtoToJSON,
} from '../models/index';

export interface NotizControllerCreateVAlphaRequest {
    einsatzId: string;
    createNotizDto: CreateNotizDto;
}

export interface NotizControllerDeleteVAlphaRequest {
    einsatzId: string;
    notizId: string;
}

export interface NotizControllerGetByEinsatzVAlphaRequest {
    einsatzId: string;
}

export interface NotizControllerUpdateVAlphaRequest {
    einsatzId: string;
    notizId: string;
    updateNotizDto: UpdateNotizDto;
}

/**
 * 
 */
export class NotizenApi extends runtime.BaseAPI {

    /**
     * Neue Notiz im Einsatz erstellen
     */
    async notizControllerCreateVAlphaRaw(requestParameters: NotizControllerCreateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotizControllerCreateVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling notizControllerCreateVAlpha().'
            );
        }

        if (requestParameters['createNotizDto'] == null) {
            throw new runtime.RequiredError(
                'createNotizDto',
                'Required parameter "createNotizDto" was null or undefined when calling notizControllerCreateVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/notizen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNotizDtoToJSON(requestParameters['createNotizDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotizControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Neue Notiz im Einsatz erstellen
     */
    async notizControllerCreateVAlpha(requestParameters: NotizControllerCreateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotizControllerCreateVAlpha201Response> {
        const response = await this.notizControllerCreateVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Notiz loeschen (Soft-Delete)
     */
    async notizControllerDeleteVAlphaRaw(requestParameters: NotizControllerDeleteVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling notizControllerDeleteVAlpha().'
            );
        }

        if (requestParameters['notizId'] == null) {
            throw new runtime.RequiredError(
                'notizId',
                'Required parameter "notizId" was null or undefined when calling notizControllerDeleteVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/notizen/{notizId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"notizId"}}`, encodeURIComponent(String(requestParameters['notizId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Notiz loeschen (Soft-Delete)
     */
    async notizControllerDeleteVAlpha(requestParameters: NotizControllerDeleteVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notizControllerDeleteVAlphaRaw(requestParameters, initOverrides);
    }

    /**
     * Alle Notizen eines Einsatzes abrufen
     */
    async notizControllerGetByEinsatzVAlphaRaw(requestParameters: NotizControllerGetByEinsatzVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotizControllerGetByEinsatzVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling notizControllerGetByEinsatzVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/notizen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotizControllerGetByEinsatzVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Alle Notizen eines Einsatzes abrufen
     */
    async notizControllerGetByEinsatzVAlpha(requestParameters: NotizControllerGetByEinsatzVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotizControllerGetByEinsatzVAlpha200Response> {
        const response = await this.notizControllerGetByEinsatzVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Notiz aktualisieren
     */
    async notizControllerUpdateVAlphaRaw(requestParameters: NotizControllerUpdateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotizControllerCreateVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling notizControllerUpdateVAlpha().'
            );
        }

        if (requestParameters['notizId'] == null) {
            throw new runtime.RequiredError(
                'notizId',
                'Required parameter "notizId" was null or undefined when calling notizControllerUpdateVAlpha().'
            );
        }

        if (requestParameters['updateNotizDto'] == null) {
            throw new runtime.RequiredError(
                'updateNotizDto',
                'Required parameter "updateNotizDto" was null or undefined when calling notizControllerUpdateVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/notizen/{notizId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"notizId"}}`, encodeURIComponent(String(requestParameters['notizId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateNotizDtoToJSON(requestParameters['updateNotizDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotizControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Notiz aktualisieren
     */
    async notizControllerUpdateVAlpha(requestParameters: NotizControllerUpdateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotizControllerCreateVAlpha201Response> {
        const response = await this.notizControllerUpdateVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
