/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.93-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTaktischesZeichenDto,
  PlatziereZeichenDto,
  TaktischeZeichenControllerCreateVAlpha201Response,
  TaktischeZeichenControllerFindAllVAlpha200Response,
  TaktischeZeichenControllerGetKatalogVAlpha200Response,
  UpdateTaktischesZeichenDto,
} from '../models/index';
import {
    CreateTaktischesZeichenDtoFromJSON,
    CreateTaktischesZeichenDtoToJSON,
    PlatziereZeichenDtoFromJSON,
    PlatziereZeichenDtoToJSON,
    TaktischeZeichenControllerCreateVAlpha201ResponseFromJSON,
    TaktischeZeichenControllerCreateVAlpha201ResponseToJSON,
    TaktischeZeichenControllerFindAllVAlpha200ResponseFromJSON,
    TaktischeZeichenControllerFindAllVAlpha200ResponseToJSON,
    TaktischeZeichenControllerGetKatalogVAlpha200ResponseFromJSON,
    TaktischeZeichenControllerGetKatalogVAlpha200ResponseToJSON,
    UpdateTaktischesZeichenDtoFromJSON,
    UpdateTaktischesZeichenDtoToJSON,
} from '../models/index';

export interface TaktischeZeichenControllerCreateVAlphaRequest {
    einsatzId: string;
    createTaktischesZeichenDto: CreateTaktischesZeichenDto;
}

export interface TaktischeZeichenControllerFindAllVAlphaRequest {
    einsatzId: string;
}

export interface TaktischeZeichenControllerGetKatalogVAlphaRequest {
    einsatzId: string;
    suche?: string;
    kategorie?: string;
}

export interface TaktischeZeichenControllerPlaceOrMoveVAlphaRequest {
    einsatzId: string;
    zeichenId: string;
    platziereZeichenDto: PlatziereZeichenDto;
}

export interface TaktischeZeichenControllerRemoveVAlphaRequest {
    einsatzId: string;
    zeichenId: string;
}

export interface TaktischeZeichenControllerUpdateVAlphaRequest {
    einsatzId: string;
    zeichenId: string;
    updateTaktischesZeichenDto: UpdateTaktischesZeichenDto;
}

/**
 * 
 */
export class TaktischeZeichenApi extends runtime.BaseAPI {

    /**
     * Taktisches Zeichen erstellen
     */
    async taktischeZeichenControllerCreateVAlphaRaw(requestParameters: TaktischeZeichenControllerCreateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaktischeZeichenControllerCreateVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling taktischeZeichenControllerCreateVAlpha().'
            );
        }

        if (requestParameters['createTaktischesZeichenDto'] == null) {
            throw new runtime.RequiredError(
                'createTaktischesZeichenDto',
                'Required parameter "createTaktischesZeichenDto" was null or undefined when calling taktischeZeichenControllerCreateVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/taktische-zeichen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTaktischesZeichenDtoToJSON(requestParameters['createTaktischesZeichenDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaktischeZeichenControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Taktisches Zeichen erstellen
     */
    async taktischeZeichenControllerCreateVAlpha(requestParameters: TaktischeZeichenControllerCreateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaktischeZeichenControllerCreateVAlpha201Response> {
        const response = await this.taktischeZeichenControllerCreateVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Alle taktischen Zeichen eines Einsatzes abrufen
     */
    async taktischeZeichenControllerFindAllVAlphaRaw(requestParameters: TaktischeZeichenControllerFindAllVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaktischeZeichenControllerFindAllVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling taktischeZeichenControllerFindAllVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/taktische-zeichen`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaktischeZeichenControllerFindAllVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Alle taktischen Zeichen eines Einsatzes abrufen
     */
    async taktischeZeichenControllerFindAllVAlpha(requestParameters: TaktischeZeichenControllerFindAllVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaktischeZeichenControllerFindAllVAlpha200Response> {
        const response = await this.taktischeZeichenControllerFindAllVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Default-Zeichen für Einheitentypen
     */
    async taktischeZeichenControllerGetDefaultsEinheitentypenVAlphaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/taktische-zeichen/defaults/einheitentypen`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Default-Zeichen für Einheitentypen
     */
    async taktischeZeichenControllerGetDefaultsEinheitentypenVAlpha(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taktischeZeichenControllerGetDefaultsEinheitentypenVAlphaRaw(initOverrides);
    }

    /**
     * Default-Zeichen für Fahrzeugtypen
     */
    async taktischeZeichenControllerGetDefaultsFahrzeugtypenVAlphaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/taktische-zeichen/defaults/fahrzeugtypen`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Default-Zeichen für Fahrzeugtypen
     */
    async taktischeZeichenControllerGetDefaultsFahrzeugtypenVAlpha(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taktischeZeichenControllerGetDefaultsFahrzeugtypenVAlphaRaw(initOverrides);
    }

    /**
     * Zeichen-Katalog abrufen
     */
    async taktischeZeichenControllerGetKatalogVAlphaRaw(requestParameters: TaktischeZeichenControllerGetKatalogVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaktischeZeichenControllerGetKatalogVAlpha200Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling taktischeZeichenControllerGetKatalogVAlpha().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['suche'] != null) {
            queryParameters['suche'] = requestParameters['suche'];
        }

        if (requestParameters['kategorie'] != null) {
            queryParameters['kategorie'] = requestParameters['kategorie'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/taktische-zeichen/katalog`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaktischeZeichenControllerGetKatalogVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Zeichen-Katalog abrufen
     */
    async taktischeZeichenControllerGetKatalogVAlpha(requestParameters: TaktischeZeichenControllerGetKatalogVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaktischeZeichenControllerGetKatalogVAlpha200Response> {
        const response = await this.taktischeZeichenControllerGetKatalogVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Taktisches Zeichen auf Karte platzieren
     */
    async taktischeZeichenControllerPlaceOrMoveVAlphaRaw(requestParameters: TaktischeZeichenControllerPlaceOrMoveVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaktischeZeichenControllerCreateVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling taktischeZeichenControllerPlaceOrMoveVAlpha().'
            );
        }

        if (requestParameters['zeichenId'] == null) {
            throw new runtime.RequiredError(
                'zeichenId',
                'Required parameter "zeichenId" was null or undefined when calling taktischeZeichenControllerPlaceOrMoveVAlpha().'
            );
        }

        if (requestParameters['platziereZeichenDto'] == null) {
            throw new runtime.RequiredError(
                'platziereZeichenDto',
                'Required parameter "platziereZeichenDto" was null or undefined when calling taktischeZeichenControllerPlaceOrMoveVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/taktische-zeichen/{zeichenId}/position`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"zeichenId"}}`, encodeURIComponent(String(requestParameters['zeichenId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlatziereZeichenDtoToJSON(requestParameters['platziereZeichenDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaktischeZeichenControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Taktisches Zeichen auf Karte platzieren
     */
    async taktischeZeichenControllerPlaceOrMoveVAlpha(requestParameters: TaktischeZeichenControllerPlaceOrMoveVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaktischeZeichenControllerCreateVAlpha201Response> {
        const response = await this.taktischeZeichenControllerPlaceOrMoveVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Taktisches Zeichen entfernen
     */
    async taktischeZeichenControllerRemoveVAlphaRaw(requestParameters: TaktischeZeichenControllerRemoveVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling taktischeZeichenControllerRemoveVAlpha().'
            );
        }

        if (requestParameters['zeichenId'] == null) {
            throw new runtime.RequiredError(
                'zeichenId',
                'Required parameter "zeichenId" was null or undefined when calling taktischeZeichenControllerRemoveVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/taktische-zeichen/{zeichenId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"zeichenId"}}`, encodeURIComponent(String(requestParameters['zeichenId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Taktisches Zeichen entfernen
     */
    async taktischeZeichenControllerRemoveVAlpha(requestParameters: TaktischeZeichenControllerRemoveVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taktischeZeichenControllerRemoveVAlphaRaw(requestParameters, initOverrides);
    }

    /**
     * Taktisches Zeichen aktualisieren
     */
    async taktischeZeichenControllerUpdateVAlphaRaw(requestParameters: TaktischeZeichenControllerUpdateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaktischeZeichenControllerCreateVAlpha201Response>> {
        if (requestParameters['einsatzId'] == null) {
            throw new runtime.RequiredError(
                'einsatzId',
                'Required parameter "einsatzId" was null or undefined when calling taktischeZeichenControllerUpdateVAlpha().'
            );
        }

        if (requestParameters['zeichenId'] == null) {
            throw new runtime.RequiredError(
                'zeichenId',
                'Required parameter "zeichenId" was null or undefined when calling taktischeZeichenControllerUpdateVAlpha().'
            );
        }

        if (requestParameters['updateTaktischesZeichenDto'] == null) {
            throw new runtime.RequiredError(
                'updateTaktischesZeichenDto',
                'Required parameter "updateTaktischesZeichenDto" was null or undefined when calling taktischeZeichenControllerUpdateVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v-alpha/einsatz/{einsatzId}/taktische-zeichen/{zeichenId}`.replace(`{${"einsatzId"}}`, encodeURIComponent(String(requestParameters['einsatzId']))).replace(`{${"zeichenId"}}`, encodeURIComponent(String(requestParameters['zeichenId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTaktischesZeichenDtoToJSON(requestParameters['updateTaktischesZeichenDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaktischeZeichenControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Taktisches Zeichen aktualisieren
     */
    async taktischeZeichenControllerUpdateVAlpha(requestParameters: TaktischeZeichenControllerUpdateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaktischeZeichenControllerCreateVAlpha201Response> {
        const response = await this.taktischeZeichenControllerUpdateVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
