/* tslint:disable */
/* eslint-disable */
/**
 * BlueLight Hub API (Alpha)
 * BlueLight Hub API for the BlueLight Hub application.  ## Server-Access-Token (X-Server-Access-Token)  Alle API-Endpunkte (außer /health und /setup) erfordern einen gültigen Server-Access-Token im Header:  ``` X-Server-Access-Token: <plaintext_token> ```  **Multi-Token Support:** - Mehrere aktive Tokens gleichzeitig möglich - Jedes Token hat einen eindeutigen Namen zur Identifikation - `lastUsedAt` wird bei jeder erfolgreichen Validierung aktualisiert - Tokens können individuell deaktiviert/reaktiviert/rotiert werden  **Token-Namenskonventionen (Best Practices):** - `Desktop Hauptwache` - für Desktop-App der Hauptwache - `Mobile SEG Nord` - für Mobile App der SEG Nord - `Integration Server` - für automatisierte Systeme - Bei Rotation: Datum im Namen (z.B. \"Desktop HW 2026-01\")
 *
 * The version of the OpenAPI document: 1.0.0-alpha.65-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateUserDto,
  DeleteUserDto,
  LockUserDto,
  UpdateUserDto,
  UserManagementControllerCreateVAlpha201Response,
  UserManagementControllerFindAllVAlpha200Response,
  UserManagementControllerRemoveVAlpha200Response,
} from '../models/index';
import {
    CreateUserDtoFromJSON,
    CreateUserDtoToJSON,
    DeleteUserDtoFromJSON,
    DeleteUserDtoToJSON,
    LockUserDtoFromJSON,
    LockUserDtoToJSON,
    UpdateUserDtoFromJSON,
    UpdateUserDtoToJSON,
    UserManagementControllerCreateVAlpha201ResponseFromJSON,
    UserManagementControllerCreateVAlpha201ResponseToJSON,
    UserManagementControllerFindAllVAlpha200ResponseFromJSON,
    UserManagementControllerFindAllVAlpha200ResponseToJSON,
    UserManagementControllerRemoveVAlpha200ResponseFromJSON,
    UserManagementControllerRemoveVAlpha200ResponseToJSON,
} from '../models/index';

export interface UserManagementControllerCreateVAlphaRequest {
    createUserDto: CreateUserDto;
}

export interface UserManagementControllerLockVAlphaRequest {
    id: string;
    lockUserDto?: LockUserDto;
}

export interface UserManagementControllerRemoveVAlphaRequest {
    id: string;
    deleteUserDto?: DeleteUserDto;
}

export interface UserManagementControllerUnlockVAlphaRequest {
    id: string;
}

export interface UserManagementControllerUpdateVAlphaRequest {
    id: string;
    updateUserDto: UpdateUserDto;
}

/**
 * 
 */
export class UserManagementApi extends runtime.BaseAPI {

    /**
     * Neuen Benutzer erstellen
     */
    async userManagementControllerCreateVAlphaRaw(requestParameters: UserManagementControllerCreateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserManagementControllerCreateVAlpha201Response>> {
        if (requestParameters['createUserDto'] == null) {
            throw new runtime.RequiredError(
                'createUserDto',
                'Required parameter "createUserDto" was null or undefined when calling userManagementControllerCreateVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("admin-jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v-alpha/admin/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserDtoToJSON(requestParameters['createUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserManagementControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Neuen Benutzer erstellen
     */
    async userManagementControllerCreateVAlpha(requestParameters: UserManagementControllerCreateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserManagementControllerCreateVAlpha201Response> {
        const response = await this.userManagementControllerCreateVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Alle Benutzer auflisten
     */
    async userManagementControllerFindAllVAlphaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserManagementControllerFindAllVAlpha200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("admin-jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v-alpha/admin/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserManagementControllerFindAllVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Alle Benutzer auflisten
     */
    async userManagementControllerFindAllVAlpha(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserManagementControllerFindAllVAlpha200Response> {
        const response = await this.userManagementControllerFindAllVAlphaRaw(initOverrides);
        return await response.value();
    }

    /**
     * Benutzer manuell sperren
     */
    async userManagementControllerLockVAlphaRaw(requestParameters: UserManagementControllerLockVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserManagementControllerCreateVAlpha201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userManagementControllerLockVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("admin-jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v-alpha/admin/users/{id}/lock`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LockUserDtoToJSON(requestParameters['lockUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserManagementControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Benutzer manuell sperren
     */
    async userManagementControllerLockVAlpha(requestParameters: UserManagementControllerLockVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserManagementControllerCreateVAlpha201Response> {
        const response = await this.userManagementControllerLockVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Benutzer löschen oder herabstufen
     */
    async userManagementControllerRemoveVAlphaRaw(requestParameters: UserManagementControllerRemoveVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserManagementControllerRemoveVAlpha200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userManagementControllerRemoveVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("admin-jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v-alpha/admin/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteUserDtoToJSON(requestParameters['deleteUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserManagementControllerRemoveVAlpha200ResponseFromJSON(jsonValue));
    }

    /**
     * Benutzer löschen oder herabstufen
     */
    async userManagementControllerRemoveVAlpha(requestParameters: UserManagementControllerRemoveVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserManagementControllerRemoveVAlpha200Response> {
        const response = await this.userManagementControllerRemoveVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Benutzer entsperren
     */
    async userManagementControllerUnlockVAlphaRaw(requestParameters: UserManagementControllerUnlockVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserManagementControllerCreateVAlpha201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userManagementControllerUnlockVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("admin-jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v-alpha/admin/users/{id}/unlock`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserManagementControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Benutzer entsperren
     */
    async userManagementControllerUnlockVAlpha(requestParameters: UserManagementControllerUnlockVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserManagementControllerCreateVAlpha201Response> {
        const response = await this.userManagementControllerUnlockVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Benutzer aktualisieren
     */
    async userManagementControllerUpdateVAlphaRaw(requestParameters: UserManagementControllerUpdateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserManagementControllerCreateVAlpha201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userManagementControllerUpdateVAlpha().'
            );
        }

        if (requestParameters['updateUserDto'] == null) {
            throw new runtime.RequiredError(
                'updateUserDto',
                'Required parameter "updateUserDto" was null or undefined when calling userManagementControllerUpdateVAlpha().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("admin-jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v-alpha/admin/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserDtoToJSON(requestParameters['updateUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserManagementControllerCreateVAlpha201ResponseFromJSON(jsonValue));
    }

    /**
     * Benutzer aktualisieren
     */
    async userManagementControllerUpdateVAlpha(requestParameters: UserManagementControllerUpdateVAlphaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserManagementControllerCreateVAlpha201Response> {
        const response = await this.userManagementControllerUpdateVAlphaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
